// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object describes the types of gifts that can be gifted to a user or a chat.
     *
     * @param unlimited_gifts True, if unlimited regular gifts are accepted
     * @param limited_gifts True, if limited regular gifts are accepted
     * @param unique_gifts True, if unique gifts or gifts that can be upgraded to unique for free are accepted
     * @param premium_subscription True, if a Telegram Premium subscription is accepted
     * @param gifts_from_channels True, if transfers of unique gifts from channels are accepted
     */
    struct AcceptedGiftTypes : public TelegramModel {
        virtual ~AcceptedGiftTypes() = default;
        // True, if unlimited regular gifts are accepted
        bool unlimited_gifts;

        // True, if limited regular gifts are accepted
        bool limited_gifts;

        // True, if unique gifts or gifts that can be upgraded to unique for free are accepted
        bool unique_gifts;

        // True, if a Telegram Premium subscription is accepted
        bool premium_subscription;

        // True, if transfers of unique gifts from channels are accepted
        bool gifts_from_channels;
    };
}
