// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "AffiliateInfo.hpp"
#include "User.hpp"
#include "Chat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const AffiliateInfo& value) {
        j = json::object();
        j["affiliate_user"] = value.affiliate_user;
        j["affiliate_chat"] = value.affiliate_chat;
        j["commission_per_mille"] = value.commission_per_mille;
        j["amount"] = value.amount;
        j["nanostar_amount"] = value.nanostar_amount;
    }

    void from_json(const json& j, AffiliateInfo& value) {
        if (j.contains("affiliate_user")) {
            j.at("affiliate_user").get_to(value.affiliate_user);
        }
        if (j.contains("affiliate_chat")) {
            j.at("affiliate_chat").get_to(value.affiliate_chat);
        }
        if (j.contains("commission_per_mille")) {
            j.at("commission_per_mille").get_to(value.commission_per_mille);
        }
        if (j.contains("amount")) {
            j.at("amount").get_to(value.amount);
        }
        if (j.contains("nanostar_amount")) {
            j.at("nanostar_amount").get_to(value.nanostar_amount);
        }
    }
}
