// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "AffiliateInfo.hpp"
#include "User.hpp"
#include "Chat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json AffiliateInfo::to_json() const {
        json j;
        j["affiliate_user"] = affiliate_user->to_json();
        j["affiliate_chat"] = affiliate_chat->to_json();
        j["commission_per_mille"] = commission_per_mille;
        j["amount"] = amount;
        j["nanostar_amount"] = nanostar_amount;
        return j.dump();
    }
    std::shared_ptr<AffiliateInfo> AffiliateInfo::from_json(const json& data) {
        auto result(std::make_shared<AffiliateInfo>());
        result->affiliate_user = User::from_json(data["affiliate_user"]);
        result->affiliate_chat = Chat::from_json(data["affiliate_chat"]);
        result->commission_per_mille = data["commission_per_mille"].get<std::int64_t>();
        result->amount = data["amount"].get<std::int64_t>();
        result->nanostar_amount = data["nanostar_amount"].get<std::int64_t>();
        return result;
    }
}
