// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    struct InlineQueryResult;

    using json = nlohmann::json;

    /**
     * Use this method to set the result of an interaction with a Web App and send a corresponding message on behalf of the user to the chat from which the query originated. On success, a SentWebAppMessage object is returned.
     *
     * @param web_app_query_id Unique identifier for the query to be answered
     * @param result A JSON-serialized object describing the message to be sent
     */
    struct AnswerWebAppQueryRequest {
        // Unique identifier for the query to be answered
        std::string web_app_query_id;

        // A JSON-serialized object describing the message to be sent
        std::shared_ptr<InlineQueryResult> result;
    };
}
