// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Audio.hpp"
#include "PhotoSize.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Audio::to_json() const {
        json j;
        j["file_id"] = file_id;
        j["file_unique_id"] = file_unique_id;
        j["duration"] = duration;
        j["performer"] = performer;
        j["title"] = title;
        j["file_name"] = file_name;
        j["mime_type"] = mime_type;
        j["file_size"] = file_size;
        j["thumbnail"] = thumbnail->to_json();
        return j.dump();
    }
    std::shared_ptr<Audio> Audio::from_json(const json& data) {
        auto result(std::make_shared<Audio>());
        result->file_id = data["file_id"].get<std::string>();
        result->file_unique_id = data["file_unique_id"].get<std::string>();
        result->duration = data["duration"].get<std::int64_t>();
        result->performer = data["performer"].get<std::string>();
        result->title = data["title"].get<std::string>();
        result->file_name = data["file_name"].get<std::string>();
        result->mime_type = data["mime_type"].get<std::string>();
        result->file_size = data["file_size"].get<std::int64_t>();
        result->thumbnail = std::shared_ptr<PhotoSize>::from_json(data["thumbnail"]);
        return result;
    }
}
