// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BackgroundFillSolid.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BackgroundFillSolid::to_json() const {
        json j;
        j["type"] = type_;
        j["color"] = color;
        return j.dump();
    }
    std::shared_ptr<BackgroundFillSolid> BackgroundFillSolid::from_json(const json& data) {
        auto result(std::make_shared<BackgroundFillSolid>());
        result->type_ = data["type_"].get<std::string>();
        result->color = data["color"].get<std::int64_t>();
        return result;
    }
}
