// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct BackgroundTypeFill;
    struct BackgroundTypeWallpaper;
    struct BackgroundTypePattern;
    struct BackgroundTypeChatTheme;

    using json = nlohmann::json;

    struct BackgroundType : public TelegramModel {
        virtual ~BackgroundType() = default;
    };
}
