// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BackgroundFillSolid.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const BackgroundFillSolid& value) {
        j = json::object();
        j["type"] = value.type_;
        j["color"] = value.color;
    }

    void from_json(const json& j, BackgroundFillSolid& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("color")) {
            j.at("color").get_to(value.color);
        }
    }
}
