// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "BackgroundType.hpp"

namespace tgbot {

    struct Document;
    struct BackgroundFill;

    using json = nlohmann::json;

    /**
     * The background is a .PNG or .TGV (gzipped subset of SVG with MIME type “application/x-tgwallpattern”) pattern to be combined with the background fill chosen by the user.
     *
     * @param type Type of the background, always “pattern”
     * @param document Document with the pattern
     * @param fill The background fill that is combined with the pattern
     * @param intensity Intensity of the pattern when it is shown above the filled background; 0-100
     * @param is_inverted Optional. True, if the background fill must be applied only to the pattern itself. All other pixels are black in this case. For dark themes only
     * @param is_moving Optional. True, if the background moves slightly when the device is tilted
     */
    struct BackgroundTypePattern : public BackgroundType {
        virtual ~BackgroundTypePattern() = default;
        // Type of the background, always “pattern”
        std::string type_;

        // Document with the pattern
        std::shared_ptr<Document> document;

        // The background fill that is combined with the pattern
        std::shared_ptr<BackgroundFill> fill;

        // Intensity of the pattern when it is shown above the filled background; 0-100
        std::int64_t intensity;

        // Optional. True, if the background fill must be applied only to the pattern itself. All other pixels are black in this case. For dark themes only
        bool is_inverted;

        // Optional. True, if the background moves slightly when the device is tilted
        bool is_moving;

        json to_json() const override;
        static std::shared_ptr<BackgroundTypePattern> from_json(const json& data);
    };
}
