// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BackgroundTypeWallpaper.hpp"
#include "Document.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BackgroundTypeWallpaper::to_json() const {
        json j;
        j["type"] = type_;
        j["document"] = document->to_json();
        j["dark_theme_dimming"] = dark_theme_dimming;
        j["is_blurred"] = is_blurred;
        j["is_moving"] = is_moving;
        return j.dump();
    }
    std::shared_ptr<BackgroundTypeWallpaper> BackgroundTypeWallpaper::from_json(const json& data) {
        auto result(std::make_shared<BackgroundTypeWallpaper>());
        result->type_ = data["type_"].get<std::string>();
        result->document = Document::from_json(data["document"]);
        result->dark_theme_dimming = data["dark_theme_dimming"].get<std::int64_t>();
        result->is_blurred = data["is_blurred"].get<bool>();
        result->is_moving = data["is_moving"].get<bool>();
        return result;
    }
}
