// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BackgroundTypeFill.hpp"
#include "BackgroundFill.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BackgroundTypeFill::to_json() const {
        json j;
        j["type"] = type_;
        j["fill"] = fill->to_json();
        j["dark_theme_dimming"] = dark_theme_dimming;
        return j.dump();
    }
    std::shared_ptr<BackgroundTypeFill> BackgroundTypeFill::from_json(const json& data) {
        auto result(std::make_shared<BackgroundTypeFill>());
        result->type_ = data["type_"].get<std::string>();
        result->fill = BackgroundFill::from_json(data["fill"]);
        result->dark_theme_dimming = data["dark_theme_dimming"].get<std::int64_t>();
        return result;
    }
}
