// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Birthdate.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Birthdate::to_json() const {
        json j;
        j["day"] = day;
        j["month"] = month;
        j["year"] = year;
        return j.dump();
    }
    std::shared_ptr<Birthdate> Birthdate::from_json(const json& data) {
        auto result(std::make_shared<Birthdate>());
        result->day = data["day"].get<std::int64_t>();
        result->month = data["month"].get<std::int64_t>();
        result->year = data["year"].get<std::int64_t>();
        return result;
    }
}
