// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "BotCommandScope.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents the default scope of bot commands. Default commands are used if no commands with a narrower scope are specified for the user.
     *
     * @param type Scope type, must be default
     */
    struct BotCommandScopeDefault : public BotCommandScope {
        virtual ~BotCommandScopeDefault() = default;
        // Scope type, must be default
        std::string type_;

        json to_json() const override;
        static std::shared_ptr<BotCommandScopeDefault> from_json(const json& data);
    };
}
