// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "BotCommandScope.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents the scope of bot commands, covering a specific chat.
     *
     * @param type Scope type, must be chat
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername). Channel direct messages chats and channel chats aren't supported.
     */
    struct BotCommandScopeChat : public BotCommandScope {
        virtual ~BotCommandScopeChat() = default;
        // Scope type, must be chat
        std::string type_;

        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername). Channel direct messages chats and channel chats aren't supported.
        ChatId chat_id;
    };
}
