// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "BotCommandScope.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents the scope of bot commands, covering all group and supergroup chats.
     *
     * @param type Scope type, must be all_group_chats
     */
    struct BotCommandScopeAllGroupChats : public BotCommandScope {
        virtual ~BotCommandScopeAllGroupChats() = default;
        // Scope type, must be all_group_chats
        std::string type_;
    };
}
