// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BotCommand.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BotCommand::to_json() const {
        json j;
        j["command"] = command;
        j["description"] = description;
        return j.dump();
    }
    std::shared_ptr<BotCommand> BotCommand::from_json(const json& data) {
        auto result(std::make_shared<BotCommand>());
        result->command = data["command"].get<std::string>();
        result->description = data["description"].get<std::string>();
        return result;
    }
}
