// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BotCommandScopeChat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BotCommandScopeChat::to_json() const {
        json j;
        j["type"] = type_;
        j["chat_id"] = chat_id.to_json();
        return j.dump();
    }
    std::shared_ptr<BotCommandScopeChat> BotCommandScopeChat::from_json(const json& data) {
        auto result(std::make_shared<BotCommandScopeChat>());
        result->type_ = data["type_"].get<std::string>();
        result->chat_id = ChatId::from_json(data["chat_id"]);
        return result;
    }
}
