// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BotDescription.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BotDescription::to_json() const {
        json j;
        j["description"] = description;
        return j.dump();
    }
    std::shared_ptr<BotDescription> BotDescription::from_json(const json& data) {
        auto result(std::make_shared<BotDescription>());
        result->description = data["description"].get<std::string>();
        return result;
    }
}
