// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BotShortDescription.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json BotShortDescription::to_json() const {
        json j;
        j["short_description"] = short_description;
        return j.dump();
    }
    std::shared_ptr<BotShortDescription> BotShortDescription::from_json(const json& data) {
        auto result(std::make_shared<BotShortDescription>());
        result->short_description = data["short_description"].get<std::string>();
        return result;
    }
}
