// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BusinessConnection.hpp"
#include "User.hpp"
#include "BusinessBotRights.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const BusinessConnection& value) {
        j = json::object();
        j["id"] = value.id;
        j["user"] = value.user;
        j["user_chat_id"] = value.user_chat_id;
        j["date"] = value.date;
        j["rights"] = value.rights;
        j["is_enabled"] = value.is_enabled;
    }

    void from_json(const json& j, BusinessConnection& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("user")) {
            j.at("user").get_to(value.user);
        }
        if (j.contains("user_chat_id")) {
            j.at("user_chat_id").get_to(value.user_chat_id);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("rights")) {
            j.at("rights").get_to(value.rights);
        }
        if (j.contains("is_enabled")) {
            j.at("is_enabled").get_to(value.is_enabled);
        }
    }
}
