// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "BusinessLocation.hpp"
#include "Location.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const BusinessLocation& value) {
        j = json::object();
        j["address"] = value.address;
        j["location"] = value.location;
    }

    void from_json(const json& j, BusinessLocation& value) {
        if (j.contains("address")) {
            j.at("address").get_to(value.address);
        }
        if (j.contains("location")) {
            j.at("location").get_to(value.location);
        }
    }
}
