// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Location;

    using json = nlohmann::json;

    /**
     * Contains information about the location of a Telegram Business account.
     *
     * @param address Address of the business
     * @param location Optional. Location of the business
     */
    struct BusinessLocation : public TelegramModel {
        virtual ~BusinessLocation() = default;
        // Address of the business
        std::string address;

        // Optional. Location of the business
        std::shared_ptr<Location> location;
    };
}
