// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Sticker;

    using json = nlohmann::json;

    /**
     * Contains information about the start page settings of a Telegram Business account.
     *
     * @param title Optional. Title text of the business intro
     * @param message Optional. Message text of the business intro
     * @param sticker Optional. Sticker of the business intro
     */
    struct BusinessIntro : public TelegramModel {
        virtual ~BusinessIntro() = default;
        // Optional. Title text of the business intro
        std::string title;

        // Optional. Message text of the business intro
        std::string message;

        // Optional. Sticker of the business intro
        std::shared_ptr<Sticker> sticker;

        json to_json() const override;
        static std::shared_ptr<BusinessIntro> from_json(const json& data);
    };
}
