// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "BusinessOpeningHoursInterval.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes the opening hours of a business.
     *
     * @param time_zone_name Unique name of the time zone for which the opening hours are defined
     * @param opening_hours List of time intervals describing business opening hours
     */
    struct BusinessOpeningHours : public TelegramModel {
        virtual ~BusinessOpeningHours() = default;
        // Unique name of the time zone for which the opening hours are defined
        std::string time_zone_name;

        // List of time intervals describing business opening hours
        std::vector<std::shared_ptr<BusinessOpeningHoursInterval>> opening_hours;

        json to_json() const override;
        static std::shared_ptr<BusinessOpeningHours> from_json(const json& data);
    };
}
