// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "ChatBoostSource.hpp"

namespace tgbot {

    struct User;

    using json = nlohmann::json;

    /**
     * The boost was obtained by subscribing to Telegram Premium or by gifting a Telegram Premium subscription to another user.
     *
     * @param source Source of the boost, always “premium”
     * @param user User that boosted the chat
     */
    struct ChatBoostSourcePremium : public ChatBoostSource {
        virtual ~ChatBoostSourcePremium() = default;
        // Source of the boost, always “premium”
        std::string source;

        // User that boosted the chat
        std::shared_ptr<User> user;
    };
}
