// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Location;

    using json = nlohmann::json;

    /**
     * Represents a location to which a chat is connected.
     *
     * @param location The location to which the supergroup is connected. Can't be a live location.
     * @param address Location address; 1-64 characters, as defined by the chat owner
     */
    struct ChatLocation : public TelegramModel {
        virtual ~ChatLocation() = default;
        // The location to which the supergroup is connected. Can't be a live location.
        std::shared_ptr<Location> location;

        // Location address; 1-64 characters, as defined by the chat owner
        std::string address;
    };
}
