// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatLocation.hpp"
#include "Location.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatLocation::to_json() const {
        json j;
        j["location"] = location->to_json();
        j["address"] = address;
        return j.dump();
    }
    std::shared_ptr<ChatLocation> ChatLocation::from_json(const json& data) {
        auto result(std::make_shared<ChatLocation>());
        result->location = std::shared_ptr<Location>::from_json(data["location"]);
        result->address = data["address"].get<std::string>();
        return result;
    }
}
