// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatBoost.hpp"
#include "ChatBoostSource.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatBoost::to_json() const {
        json j;
        j["boost_id"] = boost_id;
        j["add_date"] = add_date;
        j["expiration_date"] = expiration_date;
        j["source"] = source->to_json();
        return j.dump();
    }
    std::shared_ptr<ChatBoost> ChatBoost::from_json(const json& data) {
        auto result(std::make_shared<ChatBoost>());
        result->boost_id = data["boost_id"].get<std::string>();
        result->add_date = data["add_date"].get<std::int64_t>();
        result->expiration_date = data["expiration_date"].get<std::int64_t>();
        result->source = ChatBoostSource::from_json(data["source"]);
        return result;
    }
}
