// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatMemberAdministrator.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatMemberAdministrator::to_json() const {
        json j;
        j["status"] = status;
        j["user"] = user->to_json();
        j["can_be_edited"] = can_be_edited;
        j["is_anonymous"] = is_anonymous;
        j["can_manage_chat"] = can_manage_chat;
        j["can_delete_messages"] = can_delete_messages;
        j["can_manage_video_chats"] = can_manage_video_chats;
        j["can_restrict_members"] = can_restrict_members;
        j["can_promote_members"] = can_promote_members;
        j["can_change_info"] = can_change_info;
        j["can_invite_users"] = can_invite_users;
        j["can_post_stories"] = can_post_stories;
        j["can_edit_stories"] = can_edit_stories;
        j["can_delete_stories"] = can_delete_stories;
        j["can_post_messages"] = can_post_messages;
        j["can_edit_messages"] = can_edit_messages;
        j["can_pin_messages"] = can_pin_messages;
        j["can_manage_topics"] = can_manage_topics;
        j["can_manage_direct_messages"] = can_manage_direct_messages;
        j["custom_title"] = custom_title;
        return j.dump();
    }
    std::shared_ptr<ChatMemberAdministrator> ChatMemberAdministrator::from_json(const json& data) {
        auto result(std::make_shared<ChatMemberAdministrator>());
        result->status = data["status"].get<std::string>();
        result->user = User::from_json(data["user"]);
        result->can_be_edited = data["can_be_edited"].get<bool>();
        result->is_anonymous = data["is_anonymous"].get<bool>();
        result->can_manage_chat = data["can_manage_chat"].get<bool>();
        result->can_delete_messages = data["can_delete_messages"].get<bool>();
        result->can_manage_video_chats = data["can_manage_video_chats"].get<bool>();
        result->can_restrict_members = data["can_restrict_members"].get<bool>();
        result->can_promote_members = data["can_promote_members"].get<bool>();
        result->can_change_info = data["can_change_info"].get<bool>();
        result->can_invite_users = data["can_invite_users"].get<bool>();
        result->can_post_stories = data["can_post_stories"].get<bool>();
        result->can_edit_stories = data["can_edit_stories"].get<bool>();
        result->can_delete_stories = data["can_delete_stories"].get<bool>();
        result->can_post_messages = data["can_post_messages"].get<bool>();
        result->can_edit_messages = data["can_edit_messages"].get<bool>();
        result->can_pin_messages = data["can_pin_messages"].get<bool>();
        result->can_manage_topics = data["can_manage_topics"].get<bool>();
        result->can_manage_direct_messages = data["can_manage_direct_messages"].get<bool>();
        result->custom_title = data["custom_title"].get<std::string>();
        return result;
    }
}
