// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatBackground.hpp"
#include "BackgroundType.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatBackground::to_json() const {
        json j;
        j["type"] = type_->to_json();
        return j.dump();
    }
    std::shared_ptr<ChatBackground> ChatBackground::from_json(const json& data) {
        auto result(std::make_shared<ChatBackground>());
        result->type_ = std::shared_ptr<BackgroundType>::from_json(data["type_"]);
        return result;
    }
}
