// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatMemberMember.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatMemberMember::to_json() const {
        json j;
        j["status"] = status;
        j["user"] = user->to_json();
        j["until_date"] = until_date;
        return j.dump();
    }
    std::shared_ptr<ChatMemberMember> ChatMemberMember::from_json(const json& data) {
        auto result(std::make_shared<ChatMemberMember>());
        result->status = data["status"].get<std::string>();
        result->user = User::from_json(data["user"]);
        result->until_date = data["until_date"].get<std::int64_t>();
        return result;
    }
}
