// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChatInviteLink.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChatInviteLink::to_json() const {
        json j;
        j["invite_link"] = invite_link;
        j["creator"] = creator->to_json();
        j["creates_join_request"] = creates_join_request;
        j["is_primary"] = is_primary;
        j["is_revoked"] = is_revoked;
        j["name"] = name;
        j["expire_date"] = expire_date;
        j["member_limit"] = member_limit;
        j["pending_join_request_count"] = pending_join_request_count;
        j["subscription_period"] = subscription_period;
        j["subscription_price"] = subscription_price;
        return j.dump();
    }
    std::shared_ptr<ChatInviteLink> ChatInviteLink::from_json(const json& data) {
        auto result(std::make_shared<ChatInviteLink>());
        result->invite_link = data["invite_link"].get<std::string>();
        result->creator = std::shared_ptr<User>::from_json(data["creator"]);
        result->creates_join_request = data["creates_join_request"].get<bool>();
        result->is_primary = data["is_primary"].get<bool>();
        result->is_revoked = data["is_revoked"].get<bool>();
        result->name = data["name"].get<std::string>();
        result->expire_date = data["expire_date"].get<std::int64_t>();
        result->member_limit = data["member_limit"].get<std::int64_t>();
        result->pending_join_request_count = data["pending_join_request_count"].get<std::int64_t>();
        result->subscription_period = data["subscription_period"].get<std::int64_t>();
        result->subscription_price = data["subscription_price"].get<std::int64_t>();
        return result;
    }
}
