// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "ChatMember.hpp"

namespace tgbot {

    struct User;

    using json = nlohmann::json;

    /**
     * Represents a chat member that isn't currently a member of the chat, but may join it themselves.
     *
     * @param status The member's status in the chat, always “left”
     * @param user Information about the user
     */
    struct ChatMemberLeft : public ChatMember {
        virtual ~ChatMemberLeft() = default;
        // The member's status in the chat, always “left”
        std::string status;

        // Information about the user
        std::shared_ptr<User> user;

        json to_json() const override;
        static std::shared_ptr<ChatMemberLeft> from_json(const json& data);
    };
}
