// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Chat;
    struct ChatBoost;

    using json = nlohmann::json;

    /**
     * This object represents a boost added to a chat or changed.
     *
     * @param chat Chat which was boosted
     * @param boost Information about the chat boost
     */
    struct ChatBoostUpdated : public TelegramModel {
        virtual ~ChatBoostUpdated() = default;
        // Chat which was boosted
        std::shared_ptr<Chat> chat;

        // Information about the chat boost
        std::shared_ptr<ChatBoost> boost;

        json to_json() const override;
        static std::shared_ptr<ChatBoostUpdated> from_json(const json& data);
    };
}
