// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"
#include "ChecklistTask.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes a checklist.
     *
     * @param title Title of the checklist
     * @param title_entities Optional. Special entities that appear in the checklist title
     * @param tasks List of tasks in the checklist
     * @param others_can_add_tasks Optional. True, if users other than the creator of the list can add tasks to the list
     * @param others_can_mark_tasks_as_done Optional. True, if users other than the creator of the list can mark tasks as done or not done
     */
    struct Checklist : public TelegramModel {
        virtual ~Checklist() = default;
        // Title of the checklist
        std::string title;

        // Optional. Special entities that appear in the checklist title
        std::vector<std::shared_ptr<MessageEntity>> title_entities;

        // List of tasks in the checklist
        std::vector<std::shared_ptr<ChecklistTask>> tasks;

        // Optional. True, if users other than the creator of the list can add tasks to the list
        bool others_can_add_tasks;

        // Optional. True, if users other than the creator of the list can mark tasks as done or not done
        bool others_can_mark_tasks_as_done;

        json to_json() const override;
        static std::shared_ptr<Checklist> from_json(const json& data);
    };
}
