// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Message;

    using json = nlohmann::json;

    /**
     * Describes a service message about checklist tasks marked as done or not done.
     *
     * @param checklist_message Optional. Message containing the checklist whose tasks were marked as done or not done. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     * @param marked_as_done_task_ids Optional. Identifiers of the tasks that were marked as done
     * @param marked_as_not_done_task_ids Optional. Identifiers of the tasks that were marked as not done
     */
    struct ChecklistTasksDone : public TelegramModel {
        virtual ~ChecklistTasksDone() = default;
        // Optional. Message containing the checklist whose tasks were marked as done or not done. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        std::shared_ptr<Message> checklist_message;

        // Optional. Identifiers of the tasks that were marked as done
        std::vector<std::int64_t> marked_as_done_task_ids;

        // Optional. Identifiers of the tasks that were marked as not done
        std::vector<std::int64_t> marked_as_not_done_task_ids;
    };
}
