// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ChosenInlineResult.hpp"
#include "User.hpp"
#include "Location.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ChosenInlineResult::to_json() const {
        json j;
        j["result_id"] = result_id;
        j["from"] = from->to_json();
        j["location"] = location->to_json();
        j["inline_message_id"] = inline_message_id;
        j["query"] = query;
        return j.dump();
    }
    std::shared_ptr<ChosenInlineResult> ChosenInlineResult::from_json(const json& data) {
        auto result(std::make_shared<ChosenInlineResult>());
        result->result_id = data["result_id"].get<std::string>();
        result->from = User::from_json(data["from"]);
        result->location = Location::from_json(data["location"]);
        result->inline_message_id = data["inline_message_id"].get<std::string>();
        result->query = data["query"].get<std::string>();
        return result;
    }
}
