// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Use this method to create a subscription invite link for a channel chat. The bot must have the can_invite_users administrator rights. The link can be edited using the method editChatSubscriptionInviteLink or revoked using the method revokeChatInviteLink. Returns the new invite link as a ChatInviteLink object.
     *
     * @param chat_id Unique identifier for the target channel chat or username of the target channel (in the format @channelusername)
     * @param name Invite link name; 0-32 characters
     * @param subscription_period The number of seconds the subscription will be active for before the next payment. Currently, it must always be 2592000 (30 days).
     * @param subscription_price The amount of Telegram Stars a user must pay initially and after each subsequent subscription period to be a member of the chat; 1-10000
     */
    struct CreateChatSubscriptionInviteLinkRequest {
        // Unique identifier for the target channel chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Invite link name; 0-32 characters
        std::string name;

        // The number of seconds the subscription will be active for before the next payment. Currently, it must always be 2592000 (30 days).
        std::int64_t subscription_period;

        // The amount of Telegram Stars a user must pay initially and after each subsequent subscription period to be a member of the chat; 1-10000
        std::int64_t subscription_price;
    };
}
