// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Dice.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const Dice& value) {
        j = json::object();
        j["emoji"] = value.emoji;
        j["value"] = value.value;
    }

    void from_json(const json& j, Dice& value) {
        if (j.contains("emoji")) {
            j.at("emoji").get_to(value.emoji);
        }
        if (j.contains("value")) {
            j.at("value").get_to(value.value);
        }
    }
}
