// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "DirectMessagesTopic.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const DirectMessagesTopic& value) {
        j = json::object();
        j["topic_id"] = value.topic_id;
        j["user"] = value.user;
    }

    void from_json(const json& j, DirectMessagesTopic& value) {
        if (j.contains("topic_id")) {
            j.at("topic_id").get_to(value.topic_id);
        }
        if (j.contains("user")) {
            j.at("user").get_to(value.user);
        }
    }
}
