// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Document.hpp"
#include "PhotoSize.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const Document& value) {
        j = json::object();
        j["file_id"] = value.file_id;
        j["file_unique_id"] = value.file_unique_id;
        j["thumbnail"] = value.thumbnail;
        j["file_name"] = value.file_name;
        j["mime_type"] = value.mime_type;
        j["file_size"] = value.file_size;
    }

    void from_json(const json& j, Document& value) {
        if (j.contains("file_id")) {
            j.at("file_id").get_to(value.file_id);
        }
        if (j.contains("file_unique_id")) {
            j.at("file_unique_id").get_to(value.file_unique_id);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("file_name")) {
            j.at("file_name").get_to(value.file_name);
        }
        if (j.contains("mime_type")) {
            j.at("mime_type").get_to(value.mime_type);
        }
        if (j.contains("file_size")) {
            j.at("file_size").get_to(value.file_size);
        }
    }
}
