// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Document.hpp"
#include "PhotoSize.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Document::to_json() const {
        json j;
        j["file_id"] = file_id;
        j["file_unique_id"] = file_unique_id;
        j["thumbnail"] = thumbnail->to_json();
        j["file_name"] = file_name;
        j["mime_type"] = mime_type;
        j["file_size"] = file_size;
        return j.dump();
    }
    std::shared_ptr<Document> Document::from_json(const json& data) {
        auto result(std::make_shared<Document>());
        result->file_id = data["file_id"].get<std::string>();
        result->file_unique_id = data["file_unique_id"].get<std::string>();
        result->thumbnail = std::shared_ptr<PhotoSize>::from_json(data["thumbnail"]);
        result->file_name = data["file_name"].get<std::string>();
        result->mime_type = data["mime_type"].get<std::string>();
        result->file_size = data["file_size"].get<std::int64_t>();
        return result;
    }
}
