// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    struct InputMedia;
    struct InlineKeyboardMarkup;

    using json = nlohmann::json;

    /**
     * Use this method to edit animation, audio, document, photo, or video messages, or to add media to text messages. If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise. When an inline message is edited, a new file can't be uploaded; use a previously uploaded file via its file_id or specify a URL. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned. Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message to be edited was sent
     * @param chat_id Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Required if inline_message_id is not specified. Identifier of the message to edit
     * @param inline_message_id Required if chat_id and message_id are not specified. Identifier of the inline message
     * @param media A JSON-serialized object for a new media content of the message
     * @param reply_markup A JSON-serialized object for a new inline keyboard.
     */
    struct EditMessageMediaRequest {
        // Unique identifier of the business connection on behalf of which the message to be edited was sent
        BusinessConnectionId business_connection_id;

        // Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Required if inline_message_id is not specified. Identifier of the message to edit
        MessageId message_id;

        // Required if chat_id and message_id are not specified. Identifier of the inline message
        std::string inline_message_id;

        // A JSON-serialized object for a new media content of the message
        std::shared_ptr<InputMedia> media;

        // A JSON-serialized object for a new inline keyboard.
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;
    };
}
