// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    struct InlineKeyboardMarkup;

    using json = nlohmann::json;

    /**
     * Use this method to edit only the reply markup of messages. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned. Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message to be edited was sent
     * @param chat_id Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Required if inline_message_id is not specified. Identifier of the message to edit
     * @param inline_message_id Required if chat_id and message_id are not specified. Identifier of the inline message
     * @param reply_markup A JSON-serialized object for an inline keyboard.
     */
    struct EditMessageReplyMarkupRequest {
        // Unique identifier of the business connection on behalf of which the message to be edited was sent
        BusinessConnectionId business_connection_id;

        // Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Required if inline_message_id is not specified. Identifier of the message to edit
        MessageId message_id;

        // Required if chat_id and message_id are not specified. Identifier of the inline message
        std::string inline_message_id;

        // A JSON-serialized object for an inline keyboard.
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;
    };
}
