// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "PhotoSize.hpp"

namespace tgbot {

    struct MessageOrigin;
    struct Chat;
    struct LinkPreviewOptions;
    struct Animation;
    struct Audio;
    struct Document;
    struct PaidMediaInfo;
    struct Sticker;
    struct Story;
    struct Video;
    struct VideoNote;
    struct Voice;
    struct Checklist;
    struct Contact;
    struct Dice;
    struct Game;
    struct Giveaway;
    struct GiveawayWinners;
    struct Invoice;
    struct Location;
    struct Poll;
    struct Venue;

    using json = nlohmann::json;

    /**
     * This object contains information about a message that is being replied to, which may come from another chat or forum topic.
     *
     * @param origin Origin of the message replied to by the given message
     * @param chat Optional. Chat the original message belongs to. Available only if the chat is a supergroup or a channel.
     * @param message_id Optional. Unique message identifier inside the original chat. Available only if the original chat is a supergroup or a channel.
     * @param link_preview_options Optional. Options used for link preview generation for the original message, if it is a text message
     * @param animation Optional. Message is an animation, information about the animation
     * @param audio Optional. Message is an audio file, information about the file
     * @param document Optional. Message is a general file, information about the file
     * @param paid_media Optional. Message contains paid media; information about the paid media
     * @param photo Optional. Message is a photo, available sizes of the photo
     * @param sticker Optional. Message is a sticker, information about the sticker
     * @param story Optional. Message is a forwarded story
     * @param video Optional. Message is a video, information about the video
     * @param video_note Optional. Message is a video note, information about the video message
     * @param voice Optional. Message is a voice message, information about the file
     * @param has_media_spoiler Optional. True, if the message media is covered by a spoiler animation
     * @param checklist Optional. Message is a checklist
     * @param contact Optional. Message is a shared contact, information about the contact
     * @param dice Optional. Message is a dice with random value
     * @param game Optional. Message is a game, information about the game. More about games »
     * @param giveaway Optional. Message is a scheduled giveaway, information about the giveaway
     * @param giveaway_winners Optional. A giveaway with public winners was completed
     * @param invoice Optional. Message is an invoice for a payment, information about the invoice. More about payments »
     * @param location Optional. Message is a shared location, information about the location
     * @param poll Optional. Message is a native poll, information about the poll
     * @param venue Optional. Message is a venue, information about the venue
     */
    struct ExternalReplyInfo : public TelegramModel {
        virtual ~ExternalReplyInfo() = default;
        // Origin of the message replied to by the given message
        std::shared_ptr<MessageOrigin> origin;

        // Optional. Chat the original message belongs to. Available only if the chat is a supergroup or a channel.
        std::shared_ptr<Chat> chat;

        // Optional. Unique message identifier inside the original chat. Available only if the original chat is a supergroup or a channel.
        MessageId message_id;

        // Optional. Options used for link preview generation for the original message, if it is a text message
        std::shared_ptr<LinkPreviewOptions> link_preview_options;

        // Optional. Message is an animation, information about the animation
        std::shared_ptr<Animation> animation;

        // Optional. Message is an audio file, information about the file
        std::shared_ptr<Audio> audio;

        // Optional. Message is a general file, information about the file
        std::shared_ptr<Document> document;

        // Optional. Message contains paid media; information about the paid media
        std::shared_ptr<PaidMediaInfo> paid_media;

        // Optional. Message is a photo, available sizes of the photo
        std::vector<std::shared_ptr<PhotoSize>> photo;

        // Optional. Message is a sticker, information about the sticker
        std::shared_ptr<Sticker> sticker;

        // Optional. Message is a forwarded story
        std::shared_ptr<Story> story;

        // Optional. Message is a video, information about the video
        std::shared_ptr<Video> video;

        // Optional. Message is a video note, information about the video message
        std::shared_ptr<VideoNote> video_note;

        // Optional. Message is a voice message, information about the file
        std::shared_ptr<Voice> voice;

        // Optional. True, if the message media is covered by a spoiler animation
        bool has_media_spoiler;

        // Optional. Message is a checklist
        std::shared_ptr<Checklist> checklist;

        // Optional. Message is a shared contact, information about the contact
        std::shared_ptr<Contact> contact;

        // Optional. Message is a dice with random value
        std::shared_ptr<Dice> dice;

        // Optional. Message is a game, information about the game. More about games »
        std::shared_ptr<Game> game;

        // Optional. Message is a scheduled giveaway, information about the giveaway
        std::shared_ptr<Giveaway> giveaway;

        // Optional. A giveaway with public winners was completed
        std::shared_ptr<GiveawayWinners> giveaway_winners;

        // Optional. Message is an invoice for a payment, information about the invoice. More about payments »
        std::shared_ptr<Invoice> invoice;

        // Optional. Message is a shared location, information about the location
        std::shared_ptr<Location> location;

        // Optional. Message is a native poll, information about the poll
        std::shared_ptr<Poll> poll;

        // Optional. Message is a venue, information about the venue
        std::shared_ptr<Venue> venue;

        json to_json() const override;
        static std::shared_ptr<ExternalReplyInfo> from_json(const json& data);
    };
}
