// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ExternalReplyInfo.hpp"
#include "MessageOrigin.hpp"
#include "Chat.hpp"
#include "LinkPreviewOptions.hpp"
#include "Animation.hpp"
#include "Audio.hpp"
#include "Document.hpp"
#include "PaidMediaInfo.hpp"
#include "Sticker.hpp"
#include "Story.hpp"
#include "Video.hpp"
#include "VideoNote.hpp"
#include "Voice.hpp"
#include "Checklist.hpp"
#include "Contact.hpp"
#include "Dice.hpp"
#include "Game.hpp"
#include "Giveaway.hpp"
#include "GiveawayWinners.hpp"
#include "Invoice.hpp"
#include "Location.hpp"
#include "Poll.hpp"
#include "Venue.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ExternalReplyInfo::to_json() const {
        json j;
        j["origin"] = origin->to_json();
        j["chat"] = chat->to_json();
        j["message_id"] = message_id.to_json();
        j["link_preview_options"] = link_preview_options->to_json();
        j["animation"] = animation->to_json();
        j["audio"] = audio->to_json();
        j["document"] = document->to_json();
        j["paid_media"] = paid_media->to_json();
        std::vector<json> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : photo) {
            photo_values.push_back(e->to_json());
        }
        j["photo"] = photo_values;
        j["sticker"] = sticker->to_json();
        j["story"] = story->to_json();
        j["video"] = video->to_json();
        j["video_note"] = video_note->to_json();
        j["voice"] = voice->to_json();
        j["has_media_spoiler"] = has_media_spoiler;
        j["checklist"] = checklist->to_json();
        j["contact"] = contact->to_json();
        j["dice"] = dice->to_json();
        j["game"] = game->to_json();
        j["giveaway"] = giveaway->to_json();
        j["giveaway_winners"] = giveaway_winners->to_json();
        j["invoice"] = invoice->to_json();
        j["location"] = location->to_json();
        j["poll"] = poll->to_json();
        j["venue"] = venue->to_json();
        return j.dump();
    }
    std::shared_ptr<ExternalReplyInfo> ExternalReplyInfo::from_json(const json& data) {
        auto result(std::make_shared<ExternalReplyInfo>());
        result->origin = MessageOrigin::from_json(data["origin"]);
        result->chat = Chat::from_json(data["chat"]);
        result->message_id = MessageId::from_json(data["message_id"]);
        result->link_preview_options = LinkPreviewOptions::from_json(data["link_preview_options"]);
        result->animation = Animation::from_json(data["animation"]);
        result->audio = Audio::from_json(data["audio"]);
        result->document = Document::from_json(data["document"]);
        result->paid_media = PaidMediaInfo::from_json(data["paid_media"]);
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : data["photo"]) {
            photo_values.push_back(std::vector<std::shared_ptr<PhotoSize>>::from_json(e));
        }
        result->photo = photo_values;
        result->sticker = Sticker::from_json(data["sticker"]);
        result->story = Story::from_json(data["story"]);
        result->video = Video::from_json(data["video"]);
        result->video_note = VideoNote::from_json(data["video_note"]);
        result->voice = Voice::from_json(data["voice"]);
        result->has_media_spoiler = data["has_media_spoiler"].get<bool>();
        result->checklist = Checklist::from_json(data["checklist"]);
        result->contact = Contact::from_json(data["contact"]);
        result->dice = Dice::from_json(data["dice"]);
        result->game = Game::from_json(data["game"]);
        result->giveaway = Giveaway::from_json(data["giveaway"]);
        result->giveaway_winners = GiveawayWinners::from_json(data["giveaway_winners"]);
        result->invoice = Invoice::from_json(data["invoice"]);
        result->location = Location::from_json(data["location"]);
        result->poll = Poll::from_json(data["poll"]);
        result->venue = Venue::from_json(data["venue"]);
        return result;
    }
}
