// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents a forum topic.
     *
     * @param message_thread_id Unique identifier of the forum topic
     * @param name Name of the topic
     * @param icon_color Color of the topic icon in RGB format
     * @param icon_custom_emoji_id Optional. Unique identifier of the custom emoji shown as the topic icon
     */
    struct ForumTopic : public TelegramModel {
        virtual ~ForumTopic() = default;
        // Unique identifier of the forum topic
        MessageThreadId message_thread_id;

        // Name of the topic
        std::string name;

        // Color of the topic icon in RGB format
        std::int64_t icon_color;

        // Optional. Unique identifier of the custom emoji shown as the topic icon
        std::string icon_custom_emoji_id;

        json to_json() const override;
        static std::shared_ptr<ForumTopic> from_json(const json& data);
    };
}
