// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ForumTopicEdited.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ForumTopicEdited::to_json() const {
        json j;
        j["name"] = name;
        j["icon_custom_emoji_id"] = icon_custom_emoji_id;
        return j.dump();
    }
    std::shared_ptr<ForumTopicEdited> ForumTopicEdited::from_json(const json& data) {
        auto result(std::make_shared<ForumTopicEdited>());
        result->name = data["name"].get<std::string>();
        result->icon_custom_emoji_id = data["icon_custom_emoji_id"].get<std::string>();
        return result;
    }
}
