// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ForumTopicCreated.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json ForumTopicCreated::to_json() const {
        json j;
        j["name"] = name;
        j["icon_color"] = icon_color;
        j["icon_custom_emoji_id"] = icon_custom_emoji_id;
        return j.dump();
    }
    std::shared_ptr<ForumTopicCreated> ForumTopicCreated::from_json(const json& data) {
        auto result(std::make_shared<ForumTopicCreated>());
        result->name = data["name"].get<std::string>();
        result->icon_color = data["icon_color"].get<std::int64_t>();
        result->icon_custom_emoji_id = data["icon_custom_emoji_id"].get<std::string>();
        return result;
    }
}
