// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Use this method to forward multiple messages of any kind. If some of the specified messages can't be found or forwarded, they are skipped. Service messages and messages with protected content can't be forwarded. Album grouping is kept for forwarded messages. On success, an array of MessageId of the sent messages is returned.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_thread_id Unique identifier for the target message thread (topic) of the forum; for forum supergroups only
     * @param direct_messages_topic_id Identifier of the direct messages topic to which the messages will be forwarded; required if the messages are forwarded to a direct messages chat
     * @param from_chat_id Unique identifier for the chat where the original messages were sent (or channel username in the format @channelusername)
     * @param message_ids A JSON-serialized list of 1-100 identifiers of messages in the chat from_chat_id to forward. The identifiers must be specified in a strictly increasing order.
     * @param disable_notification Sends the messages silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the forwarded messages from forwarding and saving
     */
    struct ForwardMessagesRequest {
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Unique identifier for the target message thread (topic) of the forum; for forum supergroups only
        MessageThreadId message_thread_id;

        // Identifier of the direct messages topic to which the messages will be forwarded; required if the messages are forwarded to a direct messages chat
        std::int64_t direct_messages_topic_id;

        // Unique identifier for the chat where the original messages were sent (or channel username in the format @channelusername)
        ChatId from_chat_id;

        // A JSON-serialized list of 1-100 identifiers of messages in the chat from_chat_id to forward. The identifiers must be specified in a strictly increasing order.
        std::vector<MessageId> message_ids;

        // Sends the messages silently. Users will receive a notification with no sound.
        bool disable_notification;

        // Protects the contents of the forwarded messages from forwarding and saving
        bool protect_content;
    };
}
