// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Game.hpp"
#include "Animation.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Game::to_json() const {
        json j;
        j["title"] = title;
        j["description"] = description;
        std::vector<json> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : photo) {
            photo_values.push_back(e->to_json());
        }
        j["photo"] = photo_values;
        j["text"] = text;
        std::vector<json> text_entities_values;
        text_entities_values.reserve(text_entities.size());
        for (auto& e : text_entities) {
            text_entities_values.push_back(e->to_json());
        }
        j["text_entities"] = text_entities_values;
        j["animation"] = animation->to_json();
        return j.dump();
    }
    std::shared_ptr<Game> Game::from_json(const json& data) {
        auto result(std::make_shared<Game>());
        result->title = data["title"].get<std::string>();
        result->description = data["description"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : data["photo"]) {
            photo_values.push_back(std::vector<std::shared_ptr<PhotoSize>>::from_json(e));
        }
        result->photo = photo_values;
        result->text = data["text"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> text_entities_values;
        text_entities_values.reserve(text_entities.size());
        for (auto& e : data["text_entities"]) {
            text_entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->text_entities = text_entities_values;
        result->animation = std::shared_ptr<Animation>::from_json(data["animation"]);
        return result;
    }
}
