// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct Gift;

    using json = nlohmann::json;

    /**
     * Describes a service message about a regular gift that was sent or received.
     *
     * @param gift Information about the gift
     * @param owned_gift_id Optional. Unique identifier of the received gift for the bot; only present for gifts received on behalf of business accounts
     * @param convert_star_count Optional. Number of Telegram Stars that can be claimed by the receiver by converting the gift; omitted if conversion to Telegram Stars is impossible
     * @param prepaid_upgrade_star_count Optional. Number of Telegram Stars that were prepaid by the sender for the ability to upgrade the gift
     * @param can_be_upgraded Optional. True, if the gift can be upgraded to a unique gift
     * @param text Optional. Text of the message that was added to the gift
     * @param entities Optional. Special entities that appear in the text
     * @param is_private Optional. True, if the sender and gift text are shown only to the gift receiver; otherwise, everyone will be able to see them
     */
    struct GiftInfo : public TelegramModel {
        virtual ~GiftInfo() = default;
        // Information about the gift
        std::shared_ptr<Gift> gift;

        // Optional. Unique identifier of the received gift for the bot; only present for gifts received on behalf of business accounts
        std::string owned_gift_id;

        // Optional. Number of Telegram Stars that can be claimed by the receiver by converting the gift; omitted if conversion to Telegram Stars is impossible
        std::int64_t convert_star_count;

        // Optional. Number of Telegram Stars that were prepaid by the sender for the ability to upgrade the gift
        std::int64_t prepaid_upgrade_star_count;

        // Optional. True, if the gift can be upgraded to a unique gift
        bool can_be_upgraded;

        // Optional. Text of the message that was added to the gift
        std::string text;

        // Optional. Special entities that appear in the text
        std::vector<std::shared_ptr<MessageEntity>> entities;

        // Optional. True, if the sender and gift text are shown only to the gift receiver; otherwise, everyone will be able to see them
        bool is_private;

        json to_json() const override;
        static std::shared_ptr<GiftInfo> from_json(const json& data);
    };
}
