// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Sticker;
    struct Chat;

    using json = nlohmann::json;

    /**
     * This object represents a gift that can be sent by the bot.
     *
     * @param id Unique identifier of the gift
     * @param sticker The sticker that represents the gift
     * @param star_count The number of Telegram Stars that must be paid to send the sticker
     * @param upgrade_star_count Optional. The number of Telegram Stars that must be paid to upgrade the gift to a unique one
     * @param total_count Optional. The total number of the gifts of this type that can be sent; for limited gifts only
     * @param remaining_count Optional. The number of remaining gifts of this type that can be sent; for limited gifts only
     * @param publisher_chat Optional. Information about the chat that published the gift
     */
    struct Gift : public TelegramModel {
        virtual ~Gift() = default;
        // Unique identifier of the gift
        std::string id;

        // The sticker that represents the gift
        std::shared_ptr<Sticker> sticker;

        // The number of Telegram Stars that must be paid to send the sticker
        std::int64_t star_count;

        // Optional. The number of Telegram Stars that must be paid to upgrade the gift to a unique one
        std::int64_t upgrade_star_count;

        // Optional. The total number of the gifts of this type that can be sent; for limited gifts only
        std::int64_t total_count;

        // Optional. The number of remaining gifts of this type that can be sent; for limited gifts only
        std::int64_t remaining_count;

        // Optional. Information about the chat that published the gift
        std::shared_ptr<Chat> publisher_chat;

        json to_json() const override;
        static std::shared_ptr<Gift> from_json(const json& data);
    };
}
