// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "GiveawayCreated.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const GiveawayCreated& value) {
        j = json::object();
        j["prize_star_count"] = value.prize_star_count;
    }

    void from_json(const json& j, GiveawayCreated& value) {
        if (j.contains("prize_star_count")) {
            j.at("prize_star_count").get_to(value.prize_star_count);
        }
    }
}
