// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InlineQueryResult.hpp"
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct InlineKeyboardMarkup;
    struct InputMessageContent;

    using json = nlohmann::json;

    /**
     * Represents a link to a video animation (H.264/MPEG-4 AVC video without sound). By default, this animated MPEG-4 file will be sent by the user with optional caption. Alternatively, you can use input_message_content to send a message with the specified content instead of the animation.
     *
     * @param type Type of the result, must be mpeg4_gif
     * @param id Unique identifier for this result, 1-64 bytes
     * @param mpeg4_url A valid URL for the MPEG4 file
     * @param mpeg4_width Optional. Video width
     * @param mpeg4_height Optional. Video height
     * @param mpeg4_duration Optional. Video duration in seconds
     * @param thumbnail_url URL of the static (JPEG or GIF) or animated (MPEG4) thumbnail for the result
     * @param thumbnail_mime_type Optional. MIME type of the thumbnail, must be one of “image/jpeg”, “image/gif”, or “video/mp4”. Defaults to “image/jpeg”
     * @param title Optional. Title for the result
     * @param caption Optional. Caption of the MPEG-4 file to be sent, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param show_caption_above_media Optional. Pass True, if the caption must be shown above the message media
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the video animation
     */
    struct InlineQueryResultMpeg4Gif : public InlineQueryResult {
        virtual ~InlineQueryResultMpeg4Gif() = default;
        // Type of the result, must be mpeg4_gif
        std::string type_;

        // Unique identifier for this result, 1-64 bytes
        std::string id;

        // A valid URL for the MPEG4 file
        std::string mpeg4_url;

        // Optional. Video width
        std::int64_t mpeg4_width;

        // Optional. Video height
        std::int64_t mpeg4_height;

        // Optional. Video duration in seconds
        std::int64_t mpeg4_duration;

        // URL of the static (JPEG or GIF) or animated (MPEG4) thumbnail for the result
        std::string thumbnail_url;

        // Optional. MIME type of the thumbnail, must be one of “image/jpeg”, “image/gif”, or “video/mp4”. Defaults to “image/jpeg”
        std::string thumbnail_mime_type;

        // Optional. Title for the result
        std::string title;

        // Optional. Caption of the MPEG-4 file to be sent, 0-1024 characters after entities parsing
        std::string caption;

        // Optional. Mode for parsing entities in the caption. See formatting options for more details.
        ParseMode parse_mode;

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<std::shared_ptr<MessageEntity>> caption_entities;

        // Optional. Pass True, if the caption must be shown above the message media
        bool show_caption_above_media;

        // Optional. Inline keyboard attached to the message
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;

        // Optional. Content of the message to be sent instead of the video animation
        std::shared_ptr<InputMessageContent> input_message_content;
    };
}
