// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InlineQueryResult.hpp"
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct InlineKeyboardMarkup;
    struct InputMessageContent;

    using json = nlohmann::json;

    /**
     * Represents a link to a voice recording in an .OGG container encoded with OPUS. By default, this voice recording will be sent by the user. Alternatively, you can use input_message_content to send a message with the specified content instead of the the voice message.
     *
     * @param type Type of the result, must be voice
     * @param id Unique identifier for this result, 1-64 bytes
     * @param voice_url A valid URL for the voice recording
     * @param title Recording title
     * @param caption Optional. Caption, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the voice message caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param voice_duration Optional. Recording duration in seconds
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the voice recording
     */
    struct InlineQueryResultVoice : public InlineQueryResult {
        virtual ~InlineQueryResultVoice() = default;
        // Type of the result, must be voice
        std::string type_;

        // Unique identifier for this result, 1-64 bytes
        std::string id;

        // A valid URL for the voice recording
        std::string voice_url;

        // Recording title
        std::string title;

        // Optional. Caption, 0-1024 characters after entities parsing
        std::string caption;

        // Optional. Mode for parsing entities in the voice message caption. See formatting options for more details.
        ParseMode parse_mode;

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<std::shared_ptr<MessageEntity>> caption_entities;

        // Optional. Recording duration in seconds
        std::int64_t voice_duration;

        // Optional. Inline keyboard attached to the message
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;

        // Optional. Content of the message to be sent instead of the voice recording
        std::shared_ptr<InputMessageContent> input_message_content;

        json to_json() const override;
        static std::shared_ptr<InlineQueryResultVoice> from_json(const json& data);
    };
}
