// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InlineQueryResultArticle.hpp"
#include "InputMessageContent.hpp"
#include "InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json InlineQueryResultArticle::to_json() const {
        json j;
        j["type"] = type_;
        j["id"] = id;
        j["title"] = title;
        j["input_message_content"] = input_message_content->to_json();
        j["reply_markup"] = reply_markup->to_json();
        j["url"] = url;
        j["description"] = description;
        j["thumbnail_url"] = thumbnail_url;
        j["thumbnail_width"] = thumbnail_width;
        j["thumbnail_height"] = thumbnail_height;
        return j.dump();
    }
    std::shared_ptr<InlineQueryResultArticle> InlineQueryResultArticle::from_json(const json& data) {
        auto result(std::make_shared<InlineQueryResultArticle>());
        result->type_ = data["type_"].get<std::string>();
        result->id = data["id"].get<std::string>();
        result->title = data["title"].get<std::string>();
        result->input_message_content = InputMessageContent::from_json(data["input_message_content"]);
        result->reply_markup = InlineKeyboardMarkup::from_json(data["reply_markup"]);
        result->url = data["url"].get<std::string>();
        result->description = data["description"].get<std::string>();
        result->thumbnail_url = data["thumbnail_url"].get<std::string>();
        result->thumbnail_width = data["thumbnail_width"].get<std::int64_t>();
        result->thumbnail_height = data["thumbnail_height"].get<std::int64_t>();
        return result;
    }
}
