// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InlineQueryResultCachedVideo.hpp"
#include "InlineKeyboardMarkup.hpp"
#include "InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InlineQueryResultCachedVideo& value) {
        j = json::object();
        j["type"] = value.type_;
        j["id"] = value.id;
        j["video_file_id"] = value.video_file_id;
        j["title"] = value.title;
        j["description"] = value.description;
        j["caption"] = value.caption;
        j["parse_mode"] = value.parse_mode;
        j["caption_entities"] = value.caption_entities;
        j["show_caption_above_media"] = value.show_caption_above_media;
        j["reply_markup"] = value.reply_markup;
        j["input_message_content"] = value.input_message_content;
    }

    void from_json(const json& j, InlineQueryResultCachedVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("video_file_id")) {
            j.at("video_file_id").get_to(value.video_file_id);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
    }
}
