// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InlineQueryResult.hpp"
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct InlineKeyboardMarkup;
    struct InputMessageContent;

    using json = nlohmann::json;

    /**
     * Represents a link to a file. By default, this file will be sent by the user with an optional caption. Alternatively, you can use input_message_content to send a message with the specified content instead of the file. Currently, only .PDF and .ZIP files can be sent using this method.
     *
     * @param type Type of the result, must be document
     * @param id Unique identifier for this result, 1-64 bytes
     * @param title Title for the result
     * @param caption Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the document caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param document_url A valid URL for the file
     * @param mime_type MIME type of the content of the file, either “application/pdf” or “application/zip”
     * @param description Optional. Short description of the result
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the file
     * @param thumbnail_url Optional. URL of the thumbnail (JPEG only) for the file
     * @param thumbnail_width Optional. Thumbnail width
     * @param thumbnail_height Optional. Thumbnail height
     */
    struct InlineQueryResultDocument : public InlineQueryResult {
        virtual ~InlineQueryResultDocument() = default;
        // Type of the result, must be document
        std::string type_;

        // Unique identifier for this result, 1-64 bytes
        std::string id;

        // Title for the result
        std::string title;

        // Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
        std::string caption;

        // Optional. Mode for parsing entities in the document caption. See formatting options for more details.
        ParseMode parse_mode;

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<std::shared_ptr<MessageEntity>> caption_entities;

        // A valid URL for the file
        std::string document_url;

        // MIME type of the content of the file, either “application/pdf” or “application/zip”
        std::string mime_type;

        // Optional. Short description of the result
        std::string description;

        // Optional. Inline keyboard attached to the message
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;

        // Optional. Content of the message to be sent instead of the file
        std::shared_ptr<InputMessageContent> input_message_content;

        // Optional. URL of the thumbnail (JPEG only) for the file
        std::string thumbnail_url;

        // Optional. Thumbnail width
        std::int64_t thumbnail_width;

        // Optional. Thumbnail height
        std::int64_t thumbnail_height;
    };
}
