// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct InlineQueryResultArticle;
    struct InlineQueryResultPhoto;
    struct InlineQueryResultGif;
    struct InlineQueryResultMpeg4Gif;
    struct InlineQueryResultVideo;
    struct InlineQueryResultAudio;
    struct InlineQueryResultVoice;
    struct InlineQueryResultDocument;
    struct InlineQueryResultLocation;
    struct InlineQueryResultVenue;
    struct InlineQueryResultContact;
    struct InlineQueryResultGame;
    struct InlineQueryResultCachedPhoto;
    struct InlineQueryResultCachedGif;
    struct InlineQueryResultCachedMpeg4Gif;
    struct InlineQueryResultCachedSticker;
    struct InlineQueryResultCachedDocument;
    struct InlineQueryResultCachedVideo;
    struct InlineQueryResultCachedVoice;
    struct InlineQueryResultCachedAudio;

    using json = nlohmann::json;

    struct InlineQueryResult : public TelegramModel {
        virtual ~InlineQueryResult() = default;
    };
}
