// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InlineQueryResult.hpp"

namespace tgbot {

    struct InlineKeyboardMarkup;
    struct InputMessageContent;

    using json = nlohmann::json;

    /**
     * Represents a contact with a phone number. By default, this contact will be sent by the user. Alternatively, you can use input_message_content to send a message with the specified content instead of the contact.
     *
     * @param type Type of the result, must be contact
     * @param id Unique identifier for this result, 1-64 Bytes
     * @param phone_number Contact's phone number
     * @param first_name Contact's first name
     * @param last_name Optional. Contact's last name
     * @param vcard Optional. Additional data about the contact in the form of a vCard, 0-2048 bytes
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the contact
     * @param thumbnail_url Optional. Url of the thumbnail for the result
     * @param thumbnail_width Optional. Thumbnail width
     * @param thumbnail_height Optional. Thumbnail height
     */
    struct InlineQueryResultContact : public InlineQueryResult {
        virtual ~InlineQueryResultContact() = default;
        // Type of the result, must be contact
        std::string type_;

        // Unique identifier for this result, 1-64 Bytes
        std::string id;

        // Contact's phone number
        std::string phone_number;

        // Contact's first name
        std::string first_name;

        // Optional. Contact's last name
        std::string last_name;

        // Optional. Additional data about the contact in the form of a vCard, 0-2048 bytes
        std::string vcard;

        // Optional. Inline keyboard attached to the message
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;

        // Optional. Content of the message to be sent instead of the contact
        std::shared_ptr<InputMessageContent> input_message_content;

        // Optional. Url of the thumbnail for the result
        std::string thumbnail_url;

        // Optional. Thumbnail width
        std::int64_t thumbnail_width;

        // Optional. Thumbnail height
        std::int64_t thumbnail_height;

        json to_json() const override;
        static std::shared_ptr<InlineQueryResultContact> from_json(const json& data);
    };
}
