// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InlineQueryResultDocument.hpp"
#include "InlineKeyboardMarkup.hpp"
#include "InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InlineQueryResultDocument& value) {
        j = json::object();
        j["type"] = value.type_;
        j["id"] = value.id;
        j["title"] = value.title;
        j["caption"] = value.caption;
        j["parse_mode"] = value.parse_mode;
        j["caption_entities"] = value.caption_entities;
        j["document_url"] = value.document_url;
        j["mime_type"] = value.mime_type;
        j["description"] = value.description;
        j["reply_markup"] = value.reply_markup;
        j["input_message_content"] = value.input_message_content;
        j["thumbnail_url"] = value.thumbnail_url;
        j["thumbnail_width"] = value.thumbnail_width;
        j["thumbnail_height"] = value.thumbnail_height;
    }

    void from_json(const json& j, InlineQueryResultDocument& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("document_url")) {
            j.at("document_url").get_to(value.document_url);
        }
        if (j.contains("mime_type")) {
            j.at("mime_type").get_to(value.mime_type);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("thumbnail_width")) {
            j.at("thumbnail_width").get_to(value.thumbnail_width);
        }
        if (j.contains("thumbnail_height")) {
            j.at("thumbnail_height").get_to(value.thumbnail_height);
        }
    }
}
