// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputMediaAnimation.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json InputMediaAnimation::to_json() const {
        json j;
        j["type"] = type_;
        j["media"] = media;
        j["thumbnail"] = thumbnail;
        j["caption"] = caption;
        j["parse_mode"] = parse_mode->to_json();
        std::vector<json> caption_entities_values;
        caption_entities_values.reserve(caption_entities.size());
        for (auto& e : caption_entities) {
            caption_entities_values.push_back(e->to_json());
        }
        j["caption_entities"] = caption_entities_values;
        j["show_caption_above_media"] = show_caption_above_media;
        j["width"] = width;
        j["height"] = height;
        j["duration"] = duration;
        j["has_spoiler"] = has_spoiler;
        return j.dump();
    }
    std::shared_ptr<InputMediaAnimation> InputMediaAnimation::from_json(const json& data) {
        auto result(std::make_shared<InputMediaAnimation>());
        result->type_ = data["type_"].get<std::string>();
        result->media = data["media"].get<std::string>();
        result->thumbnail = data["thumbnail"].get<std::string>();
        result->caption = data["caption"].get<std::string>();
        result->parse_mode = ParseMode::from_json(data["parse_mode"]);
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> caption_entities_values;
        caption_entities_values.reserve(caption_entities.size());
        for (auto& e : data["caption_entities"]) {
            caption_entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->caption_entities = caption_entities_values;
        result->show_caption_above_media = data["show_caption_above_media"].get<bool>();
        result->width = data["width"].get<std::int64_t>();
        result->height = data["height"].get<std::int64_t>();
        result->duration = data["duration"].get<std::int64_t>();
        result->has_spoiler = data["has_spoiler"].get<bool>();
        return result;
    }
}
