// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InputStoryContent.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes a photo to post as a story.
     *
     * @param type Type of the content, must be photo
     * @param photo The photo to post as a story. The photo must be of the size 1080x1920 and must not exceed 10 MB. The photo can't be reused and can only be uploaded as a new file, so you can pass “attach://<file_attach_name>” if the photo was uploaded using multipart/form-data under <file_attach_name>. More information on Sending Files »
     */
    struct InputStoryContentPhoto : public InputStoryContent {
        virtual ~InputStoryContentPhoto() = default;
        // Type of the content, must be photo
        std::string type_;

        // The photo to post as a story. The photo must be of the size 1080x1920 and must not exceed 10 MB. The photo can't be reused and can only be uploaded as a new file, so you can pass “attach://<file_attach_name>” if the photo was uploaded using multipart/form-data under <file_attach_name>. More information on Sending Files »
        std::string photo;
    };
}
