// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputLocationMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputLocationMessageContent& value) {
        j = json::object();
        j["latitude"] = value.latitude;
        j["longitude"] = value.longitude;
        j["horizontal_accuracy"] = value.horizontal_accuracy;
        j["live_period"] = value.live_period;
        j["heading"] = value.heading;
        j["proximity_alert_radius"] = value.proximity_alert_radius;
    }

    void from_json(const json& j, InputLocationMessageContent& value) {
        if (j.contains("latitude")) {
            j.at("latitude").get_to(value.latitude);
        }
        if (j.contains("longitude")) {
            j.at("longitude").get_to(value.longitude);
        }
        if (j.contains("horizontal_accuracy")) {
            j.at("horizontal_accuracy").get_to(value.horizontal_accuracy);
        }
        if (j.contains("live_period")) {
            j.at("live_period").get_to(value.live_period);
        }
        if (j.contains("heading")) {
            j.at("heading").get_to(value.heading);
        }
        if (j.contains("proximity_alert_radius")) {
            j.at("proximity_alert_radius").get_to(value.proximity_alert_radius);
        }
    }
}
