// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputStoryContentVideo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json InputStoryContentVideo::to_json() const {
        json j;
        j["type"] = type_;
        j["video"] = video;
        j["duration"] = duration;
        j["cover_frame_timestamp"] = cover_frame_timestamp;
        j["is_animation"] = is_animation;
        return j.dump();
    }
    std::shared_ptr<InputStoryContentVideo> InputStoryContentVideo::from_json(const json& data) {
        auto result(std::make_shared<InputStoryContentVideo>());
        result->type_ = data["type_"].get<std::string>();
        result->video = data["video"].get<std::string>();
        result->duration = data["duration"].get<double>();
        result->cover_frame_timestamp = data["cover_frame_timestamp"].get<double>();
        result->is_animation = data["is_animation"].get<bool>();
        return result;
    }
}
