// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputProfilePhotoStatic.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json InputProfilePhotoStatic::to_json() const {
        json j;
        j["type"] = type_;
        j["photo"] = photo;
        return j.dump();
    }
    std::shared_ptr<InputProfilePhotoStatic> InputProfilePhotoStatic::from_json(const json& data) {
        auto result(std::make_shared<InputProfilePhotoStatic>());
        result->type_ = data["type_"].get<std::string>();
        result->photo = data["photo"].get<std::string>();
        return result;
    }
}
