// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InputMessageContent.hpp"
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct LinkPreviewOptions;

    using json = nlohmann::json;

    /**
     * Represents the content of a text message to be sent as the result of an inline query.
     *
     * @param message_text Text of the message to be sent, 1-4096 characters
     * @param parse_mode Optional. Mode for parsing entities in the message text. See formatting options for more details.
     * @param entities Optional. List of special entities that appear in message text, which can be specified instead of parse_mode
     * @param link_preview_options Optional. Link preview generation options for the message
     */
    struct InputTextMessageContent : public InputMessageContent {
        virtual ~InputTextMessageContent() = default;
        // Text of the message to be sent, 1-4096 characters
        std::string message_text;

        // Optional. Mode for parsing entities in the message text. See formatting options for more details.
        ParseMode parse_mode;

        // Optional. List of special entities that appear in message text, which can be specified instead of parse_mode
        std::vector<std::shared_ptr<MessageEntity>> entities;

        // Optional. Link preview generation options for the message
        std::shared_ptr<LinkPreviewOptions> link_preview_options;

        json to_json() const override;
        static std::shared_ptr<InputTextMessageContent> from_json(const json& data);
    };
}
