// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "InputPaidMedia.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The paid media to send is a photo.
     *
     * @param type Type of the media, must be photo
     * @param media File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name. More information on Sending Files »
     */
    struct InputPaidMediaPhoto : public InputPaidMedia {
        virtual ~InputPaidMediaPhoto() = default;
        // Type of the media, must be photo
        std::string type_;

        // File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name. More information on Sending Files »
        std::string media;

        json to_json() const override;
        static std::shared_ptr<InputPaidMediaPhoto> from_json(const json& data);
    };
}
