// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputProfilePhotoAnimated.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json InputProfilePhotoAnimated::to_json() const {
        json j;
        j["type"] = type_;
        j["animation"] = animation;
        j["main_frame_timestamp"] = main_frame_timestamp;
        return j.dump();
    }
    std::shared_ptr<InputProfilePhotoAnimated> InputProfilePhotoAnimated::from_json(const json& data) {
        auto result(std::make_shared<InputProfilePhotoAnimated>());
        result->type_ = data["type_"].get<std::string>();
        result->animation = data["animation"].get<std::string>();
        result->main_frame_timestamp = data["main_frame_timestamp"].get<double>();
        return result;
    }
}
