// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputPaidMediaVideo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputPaidMediaVideo& value) {
        j = json::object();
        j["type"] = value.type_;
        j["media"] = value.media;
        j["thumbnail"] = value.thumbnail;
        j["cover"] = value.cover;
        j["start_timestamp"] = value.start_timestamp;
        j["width"] = value.width;
        j["height"] = value.height;
        j["duration"] = value.duration;
        j["supports_streaming"] = value.supports_streaming;
    }

    void from_json(const json& j, InputPaidMediaVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("cover")) {
            j.at("cover").get_to(value.cover);
        }
        if (j.contains("start_timestamp")) {
            j.at("start_timestamp").get_to(value.start_timestamp);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("supports_streaming")) {
            j.at("supports_streaming").get_to(value.supports_streaming);
        }
    }
}
