// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "InputContactMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputContactMessageContent& value) {
        j = json::object();
        j["phone_number"] = value.phone_number;
        j["first_name"] = value.first_name;
        j["last_name"] = value.last_name;
        j["vcard"] = value.vcard;
    }

    void from_json(const json& j, InputContactMessageContent& value) {
        if (j.contains("phone_number")) {
            j.at("phone_number").get_to(value.phone_number);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("vcard")) {
            j.at("vcard").get_to(value.vcard);
        }
    }
}
