// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct MaskPosition;

    using json = nlohmann::json;

    /**
     * This object describes a sticker to be added to a sticker set.
     *
     * @param sticker The added sticker. Pass a file_id as a String to send a file that already exists on the Telegram servers, pass an HTTP URL as a String for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new file using multipart/form-data under <file_attach_name> name. Animated and video stickers can't be uploaded via HTTP URL. More information on Sending Files »
     * @param format Format of the added sticker, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, “video” for a .WEBM video
     * @param emoji_list List of 1-20 emoji associated with the sticker
     * @param mask_position Optional. Position where the mask should be placed on faces. For “mask” stickers only.
     * @param keywords Optional. List of 0-20 search keywords for the sticker with total length of up to 64 characters. For “regular” and “custom_emoji” stickers only.
     */
    struct InputSticker : public TelegramModel {
        virtual ~InputSticker() = default;
        // The added sticker. Pass a file_id as a String to send a file that already exists on the Telegram servers, pass an HTTP URL as a String for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new file using multipart/form-data under <file_attach_name> name. Animated and video stickers can't be uploaded via HTTP URL. More information on Sending Files »
        std::string sticker;

        // Format of the added sticker, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, “video” for a .WEBM video
        std::string format;

        // List of 1-20 emoji associated with the sticker
        std::vector<std::string> emoji_list;

        // Optional. Position where the mask should be placed on faces. For “mask” stickers only.
        std::shared_ptr<MaskPosition> mask_position;

        // Optional. List of 0-20 search keywords for the sticker with total length of up to 64 characters. For “regular” and “custom_emoji” stickers only.
        std::vector<std::string> keywords;
    };
}
