// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes a task to add to a checklist.
     *
     * @param id Unique identifier of the task; must be positive and unique among all task identifiers currently present in the checklist
     * @param text Text of the task; 1-100 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the text. See formatting options for more details.
     * @param text_entities Optional. List of special entities that appear in the text, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
     */
    struct InputChecklistTask : public TelegramModel {
        virtual ~InputChecklistTask() = default;
        // Unique identifier of the task; must be positive and unique among all task identifiers currently present in the checklist
        std::int64_t id;

        // Text of the task; 1-100 characters after entities parsing
        std::string text;

        // Optional. Mode for parsing entities in the text. See formatting options for more details.
        ParseMode parse_mode;

        // Optional. List of special entities that appear in the text, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
        std::vector<std::shared_ptr<MessageEntity>> text_entities;

        json to_json() const override;
        static std::shared_ptr<InputChecklistTask> from_json(const json& data);
    };
}
