// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "KeyboardButtonRequestUsers.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json KeyboardButtonRequestUsers::to_json() const {
        json j;
        j["request_id"] = request_id;
        j["user_is_bot"] = user_is_bot;
        j["user_is_premium"] = user_is_premium;
        j["max_quantity"] = max_quantity;
        j["request_name"] = request_name;
        j["request_username"] = request_username;
        j["request_photo"] = request_photo;
        return j.dump();
    }
    std::shared_ptr<KeyboardButtonRequestUsers> KeyboardButtonRequestUsers::from_json(const json& data) {
        auto result(std::make_shared<KeyboardButtonRequestUsers>());
        result->request_id = data["request_id"].get<std::int64_t>();
        result->user_is_bot = data["user_is_bot"].get<bool>();
        result->user_is_premium = data["user_is_premium"].get<bool>();
        result->max_quantity = data["max_quantity"].get<std::int64_t>();
        result->request_name = data["request_name"].get<bool>();
        result->request_username = data["request_username"].get<bool>();
        result->request_photo = data["request_photo"].get<bool>();
        return result;
    }
}
