// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes the options used for link preview generation.
     *
     * @param is_disabled Optional. True, if the link preview is disabled
     * @param url Optional. URL to use for the link preview. If empty, then the first URL found in the message text will be used
     * @param prefer_small_media Optional. True, if the media in the link preview is supposed to be shrunk; ignored if the URL isn't explicitly specified or media size change isn't supported for the preview
     * @param prefer_large_media Optional. True, if the media in the link preview is supposed to be enlarged; ignored if the URL isn't explicitly specified or media size change isn't supported for the preview
     * @param show_above_text Optional. True, if the link preview must be shown above the message text; otherwise, the link preview will be shown below the message text
     */
    struct LinkPreviewOptions : public TelegramModel {
        virtual ~LinkPreviewOptions() = default;
        // Optional. True, if the link preview is disabled
        bool is_disabled;

        // Optional. URL to use for the link preview. If empty, then the first URL found in the message text will be used
        std::string url;

        // Optional. True, if the media in the link preview is supposed to be shrunk; ignored if the URL isn't explicitly specified or media size change isn't supported for the preview
        bool prefer_small_media;

        // Optional. True, if the media in the link preview is supposed to be enlarged; ignored if the URL isn't explicitly specified or media size change isn't supported for the preview
        bool prefer_large_media;

        // Optional. True, if the link preview must be shown above the message text; otherwise, the link preview will be shown below the message text
        bool show_above_text;

        json to_json() const override;
        static std::shared_ptr<LinkPreviewOptions> from_json(const json& data);
    };
}
