// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "MenuButton.hpp"

namespace tgbot {

    struct WebAppInfo;

    using json = nlohmann::json;

    /**
     * Represents a menu button, which launches a Web App.
     *
     * @param type Type of the button, must be web_app
     * @param text Text on the button
     * @param web_app Description of the Web App that will be launched when the user presses the button. The Web App will be able to send an arbitrary message on behalf of the user using the method answerWebAppQuery. Alternatively, a t.me link to a Web App of the bot can be specified in the object instead of the Web App's URL, in which case the Web App will be opened as if the user pressed the link.
     */
    struct MenuButtonWebApp : public MenuButton {
        virtual ~MenuButtonWebApp() = default;
        // Type of the button, must be web_app
        std::string type_;

        // Text on the button
        std::string text;

        // Description of the Web App that will be launched when the user presses the button. The Web App will be able to send an arbitrary message on behalf of the user using the method answerWebAppQuery. Alternatively, a t.me link to a Web App of the bot can be specified in the object instead of the Web App's URL, in which case the Web App will be opened as if the user pressed the link.
        std::shared_ptr<WebAppInfo> web_app;

        json to_json() const override;
        static std::shared_ptr<MenuButtonWebApp> from_json(const json& data);
    };
}
