// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "MenuButton.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes that no specific value for the menu button was set.
     *
     * @param type Type of the button, must be default
     */
    struct MenuButtonDefault : public MenuButton {
        virtual ~MenuButtonDefault() = default;
        // Type of the button, must be default
        std::string type_;

        json to_json() const override;
        static std::shared_ptr<MenuButtonDefault> from_json(const json& data);
    };
}
