// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "MenuButtonWebApp.hpp"
#include "WebAppInfo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json MenuButtonWebApp::to_json() const {
        json j;
        j["type"] = type_;
        j["text"] = text;
        j["web_app"] = web_app->to_json();
        return j.dump();
    }
    std::shared_ptr<MenuButtonWebApp> MenuButtonWebApp::from_json(const json& data) {
        auto result(std::make_shared<MenuButtonWebApp>());
        result->type_ = data["type_"].get<std::string>();
        result->text = data["text"].get<std::string>();
        result->web_app = std::shared_ptr<WebAppInfo>::from_json(data["web_app"]);
        return result;
    }
}
