// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "ReactionType.hpp"

namespace tgbot {

    struct Chat;
    struct User;

    using json = nlohmann::json;

    /**
     * This object represents a change of a reaction on a message performed by a user.
     *
     * @param chat The chat containing the message the user reacted to
     * @param message_id Unique identifier of the message inside the chat
     * @param user Optional. The user that changed the reaction, if the user isn't anonymous
     * @param actor_chat Optional. The chat on behalf of which the reaction was changed, if the user is anonymous
     * @param date Date of the change in Unix time
     * @param old_reaction Previous list of reaction types that were set by the user
     * @param new_reaction New list of reaction types that have been set by the user
     */
    struct MessageReactionUpdated : public TelegramModel {
        virtual ~MessageReactionUpdated() = default;
        // The chat containing the message the user reacted to
        std::shared_ptr<Chat> chat;

        // Unique identifier of the message inside the chat
        MessageId message_id;

        // Optional. The user that changed the reaction, if the user isn't anonymous
        std::shared_ptr<User> user;

        // Optional. The chat on behalf of which the reaction was changed, if the user is anonymous
        std::shared_ptr<Chat> actor_chat;

        // Date of the change in Unix time
        std::int64_t date;

        // Previous list of reaction types that were set by the user
        std::vector<std::shared_ptr<ReactionType>> old_reaction;

        // New list of reaction types that have been set by the user
        std::vector<std::shared_ptr<ReactionType>> new_reaction;

        json to_json() const override;
        static std::shared_ptr<MessageReactionUpdated> from_json(const json& data);
    };
}
