// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "MessageOrigin.hpp"

namespace tgbot {

    struct User;

    using json = nlohmann::json;

    /**
     * The message was originally sent by a known user.
     *
     * @param type Type of the message origin, always “user”
     * @param date Date the message was sent originally in Unix time
     * @param sender_user User that sent the message originally
     */
    struct MessageOriginUser : public MessageOrigin {
        virtual ~MessageOriginUser() = default;
        // Type of the message origin, always “user”
        std::string type_;

        // Date the message was sent originally in Unix time
        std::int64_t date;

        // User that sent the message originally
        std::shared_ptr<User> sender_user;
    };
}
