// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Message.hpp"
#include "DirectMessagesTopic.hpp"
#include "User.hpp"
#include "Chat.hpp"
#include "MessageOrigin.hpp"
#include "ExternalReplyInfo.hpp"
#include "TextQuote.hpp"
#include "Story.hpp"
#include "LinkPreviewOptions.hpp"
#include "SuggestedPostInfo.hpp"
#include "Animation.hpp"
#include "Audio.hpp"
#include "Document.hpp"
#include "PaidMediaInfo.hpp"
#include "Sticker.hpp"
#include "Video.hpp"
#include "VideoNote.hpp"
#include "Voice.hpp"
#include "Checklist.hpp"
#include "Contact.hpp"
#include "Dice.hpp"
#include "Game.hpp"
#include "Poll.hpp"
#include "Venue.hpp"
#include "Location.hpp"
#include "MessageAutoDeleteTimerChanged.hpp"
#include "MaybeInaccessibleMessage.hpp"
#include "Invoice.hpp"
#include "SuccessfulPayment.hpp"
#include "RefundedPayment.hpp"
#include "UsersShared.hpp"
#include "ChatShared.hpp"
#include "GiftInfo.hpp"
#include "UniqueGiftInfo.hpp"
#include "WriteAccessAllowed.hpp"
#include "PassportData.hpp"
#include "ProximityAlertTriggered.hpp"
#include "ChatBoostAdded.hpp"
#include "ChatBackground.hpp"
#include "ChecklistTasksDone.hpp"
#include "ChecklistTasksAdded.hpp"
#include "DirectMessagePriceChanged.hpp"
#include "ForumTopicCreated.hpp"
#include "ForumTopicEdited.hpp"
#include "GiveawayCreated.hpp"
#include "Giveaway.hpp"
#include "GiveawayWinners.hpp"
#include "GiveawayCompleted.hpp"
#include "PaidMessagePriceChanged.hpp"
#include "SuggestedPostApproved.hpp"
#include "SuggestedPostApprovalFailed.hpp"
#include "SuggestedPostDeclined.hpp"
#include "SuggestedPostPaid.hpp"
#include "SuggestedPostRefunded.hpp"
#include "VideoChatScheduled.hpp"
#include "VideoChatEnded.hpp"
#include "VideoChatParticipantsInvited.hpp"
#include "WebAppData.hpp"
#include "InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Message::to_json() const {
        json j;
        j["message_id"] = message_id.to_json();
        j["message_thread_id"] = message_thread_id.to_json();
        j["direct_messages_topic"] = direct_messages_topic->to_json();
        j["from"] = from->to_json();
        j["sender_chat"] = sender_chat->to_json();
        j["sender_boost_count"] = sender_boost_count;
        j["sender_business_bot"] = sender_business_bot->to_json();
        j["date"] = date;
        j["business_connection_id"] = business_connection_id.to_json();
        j["chat"] = chat->to_json();
        j["forward_origin"] = forward_origin->to_json();
        j["is_topic_message"] = is_topic_message;
        j["is_automatic_forward"] = is_automatic_forward;
        j["reply_to_message"] = reply_to_message->to_json();
        j["external_reply"] = external_reply->to_json();
        j["quote"] = quote->to_json();
        j["reply_to_story"] = reply_to_story->to_json();
        j["reply_to_checklist_task_id"] = reply_to_checklist_task_id;
        j["via_bot"] = via_bot->to_json();
        j["edit_date"] = edit_date;
        j["has_protected_content"] = has_protected_content;
        j["is_from_offline"] = is_from_offline;
        j["is_paid_post"] = is_paid_post;
        j["media_group_id"] = media_group_id;
        j["author_signature"] = author_signature;
        j["paid_star_count"] = paid_star_count;
        j["text"] = text;
        std::vector<json> entities_values;
        entities_values.reserve(entities.size());
        for (auto& e : entities) {
            entities_values.push_back(e->to_json());
        }
        j["entities"] = entities_values;
        j["link_preview_options"] = link_preview_options->to_json();
        j["suggested_post_info"] = suggested_post_info->to_json();
        j["effect_id"] = effect_id;
        j["animation"] = animation->to_json();
        j["audio"] = audio->to_json();
        j["document"] = document->to_json();
        j["paid_media"] = paid_media->to_json();
        std::vector<json> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : photo) {
            photo_values.push_back(e->to_json());
        }
        j["photo"] = photo_values;
        j["sticker"] = sticker->to_json();
        j["story"] = story->to_json();
        j["video"] = video->to_json();
        j["video_note"] = video_note->to_json();
        j["voice"] = voice->to_json();
        j["caption"] = caption;
        std::vector<json> caption_entities_values;
        caption_entities_values.reserve(caption_entities.size());
        for (auto& e : caption_entities) {
            caption_entities_values.push_back(e->to_json());
        }
        j["caption_entities"] = caption_entities_values;
        j["show_caption_above_media"] = show_caption_above_media;
        j["has_media_spoiler"] = has_media_spoiler;
        j["checklist"] = checklist->to_json();
        j["contact"] = contact->to_json();
        j["dice"] = dice->to_json();
        j["game"] = game->to_json();
        j["poll"] = poll->to_json();
        j["venue"] = venue->to_json();
        j["location"] = location->to_json();
        std::vector<json> new_chat_members_values;
        new_chat_members_values.reserve(new_chat_members.size());
        for (auto& e : new_chat_members) {
            new_chat_members_values.push_back(e->to_json());
        }
        j["new_chat_members"] = new_chat_members_values;
        j["left_chat_member"] = left_chat_member->to_json();
        j["new_chat_title"] = new_chat_title;
        std::vector<json> new_chat_photo_values;
        new_chat_photo_values.reserve(new_chat_photo.size());
        for (auto& e : new_chat_photo) {
            new_chat_photo_values.push_back(e->to_json());
        }
        j["new_chat_photo"] = new_chat_photo_values;
        j["delete_chat_photo"] = delete_chat_photo;
        j["group_chat_created"] = group_chat_created;
        j["supergroup_chat_created"] = supergroup_chat_created;
        j["channel_chat_created"] = channel_chat_created;
        j["message_auto_delete_timer_changed"] = message_auto_delete_timer_changed->to_json();
        j["migrate_to_chat_id"] = migrate_to_chat_id.to_json();
        j["migrate_from_chat_id"] = migrate_from_chat_id.to_json();
        j["pinned_message"] = pinned_message->to_json();
        j["invoice"] = invoice->to_json();
        j["successful_payment"] = successful_payment->to_json();
        j["refunded_payment"] = refunded_payment->to_json();
        j["users_shared"] = users_shared->to_json();
        j["chat_shared"] = chat_shared->to_json();
        j["gift"] = gift->to_json();
        j["unique_gift"] = unique_gift->to_json();
        j["connected_website"] = connected_website;
        j["write_access_allowed"] = write_access_allowed->to_json();
        j["passport_data"] = passport_data->to_json();
        j["proximity_alert_triggered"] = proximity_alert_triggered->to_json();
        j["boost_added"] = boost_added->to_json();
        j["chat_background_set"] = chat_background_set->to_json();
        j["checklist_tasks_done"] = checklist_tasks_done->to_json();
        j["checklist_tasks_added"] = checklist_tasks_added->to_json();
        j["direct_message_price_changed"] = direct_message_price_changed->to_json();
        j["forum_topic_created"] = forum_topic_created->to_json();
        j["forum_topic_edited"] = forum_topic_edited->to_json();
        j["forum_topic_closed"] = forum_topic_closed->to_json();
        j["forum_topic_reopened"] = forum_topic_reopened->to_json();
        j["general_forum_topic_hidden"] = general_forum_topic_hidden->to_json();
        j["general_forum_topic_unhidden"] = general_forum_topic_unhidden->to_json();
        j["giveaway_created"] = giveaway_created->to_json();
        j["giveaway"] = giveaway->to_json();
        j["giveaway_winners"] = giveaway_winners->to_json();
        j["giveaway_completed"] = giveaway_completed->to_json();
        j["paid_message_price_changed"] = paid_message_price_changed->to_json();
        j["suggested_post_approved"] = suggested_post_approved->to_json();
        j["suggested_post_approval_failed"] = suggested_post_approval_failed->to_json();
        j["suggested_post_declined"] = suggested_post_declined->to_json();
        j["suggested_post_paid"] = suggested_post_paid->to_json();
        j["suggested_post_refunded"] = suggested_post_refunded->to_json();
        j["video_chat_scheduled"] = video_chat_scheduled->to_json();
        j["video_chat_started"] = video_chat_started->to_json();
        j["video_chat_ended"] = video_chat_ended->to_json();
        j["video_chat_participants_invited"] = video_chat_participants_invited->to_json();
        j["web_app_data"] = web_app_data->to_json();
        j["reply_markup"] = reply_markup->to_json();
        return j.dump();
    }
    std::shared_ptr<Message> Message::from_json(const json& data) {
        auto result(std::make_shared<Message>());
        result->message_id = MessageId::from_json(data["message_id"]);
        result->message_thread_id = MessageThreadId::from_json(data["message_thread_id"]);
        result->direct_messages_topic = DirectMessagesTopic::from_json(data["direct_messages_topic"]);
        result->from = User::from_json(data["from"]);
        result->sender_chat = Chat::from_json(data["sender_chat"]);
        result->sender_boost_count = data["sender_boost_count"].get<std::int64_t>();
        result->sender_business_bot = User::from_json(data["sender_business_bot"]);
        result->date = data["date"].get<std::int64_t>();
        result->business_connection_id = BusinessConnectionId::from_json(data["business_connection_id"]);
        result->chat = Chat::from_json(data["chat"]);
        result->forward_origin = MessageOrigin::from_json(data["forward_origin"]);
        result->is_topic_message = data["is_topic_message"].get<bool>();
        result->is_automatic_forward = data["is_automatic_forward"].get<bool>();
        result->reply_to_message = Message::from_json(data["reply_to_message"]);
        result->external_reply = ExternalReplyInfo::from_json(data["external_reply"]);
        result->quote = TextQuote::from_json(data["quote"]);
        result->reply_to_story = Story::from_json(data["reply_to_story"]);
        result->reply_to_checklist_task_id = data["reply_to_checklist_task_id"].get<std::int64_t>();
        result->via_bot = User::from_json(data["via_bot"]);
        result->edit_date = data["edit_date"].get<std::int64_t>();
        result->has_protected_content = data["has_protected_content"].get<bool>();
        result->is_from_offline = data["is_from_offline"].get<bool>();
        result->is_paid_post = data["is_paid_post"].get<bool>();
        result->media_group_id = data["media_group_id"].get<std::string>();
        result->author_signature = data["author_signature"].get<std::string>();
        result->paid_star_count = data["paid_star_count"].get<std::int64_t>();
        result->text = data["text"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> entities_values;
        entities_values.reserve(entities.size());
        for (auto& e : data["entities"]) {
            entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->entities = entities_values;
        result->link_preview_options = LinkPreviewOptions::from_json(data["link_preview_options"]);
        result->suggested_post_info = SuggestedPostInfo::from_json(data["suggested_post_info"]);
        result->effect_id = data["effect_id"].get<std::string>();
        result->animation = Animation::from_json(data["animation"]);
        result->audio = Audio::from_json(data["audio"]);
        result->document = Document::from_json(data["document"]);
        result->paid_media = PaidMediaInfo::from_json(data["paid_media"]);
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : data["photo"]) {
            photo_values.push_back(std::vector<std::shared_ptr<PhotoSize>>::from_json(e));
        }
        result->photo = photo_values;
        result->sticker = Sticker::from_json(data["sticker"]);
        result->story = Story::from_json(data["story"]);
        result->video = Video::from_json(data["video"]);
        result->video_note = VideoNote::from_json(data["video_note"]);
        result->voice = Voice::from_json(data["voice"]);
        result->caption = data["caption"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> caption_entities_values;
        caption_entities_values.reserve(caption_entities.size());
        for (auto& e : data["caption_entities"]) {
            caption_entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->caption_entities = caption_entities_values;
        result->show_caption_above_media = data["show_caption_above_media"].get<bool>();
        result->has_media_spoiler = data["has_media_spoiler"].get<bool>();
        result->checklist = Checklist::from_json(data["checklist"]);
        result->contact = Contact::from_json(data["contact"]);
        result->dice = Dice::from_json(data["dice"]);
        result->game = Game::from_json(data["game"]);
        result->poll = Poll::from_json(data["poll"]);
        result->venue = Venue::from_json(data["venue"]);
        result->location = Location::from_json(data["location"]);
        std::vector<std::vector<std::shared_ptr<User>>> new_chat_members_values;
        new_chat_members_values.reserve(new_chat_members.size());
        for (auto& e : data["new_chat_members"]) {
            new_chat_members_values.push_back(std::vector<std::shared_ptr<User>>::from_json(e));
        }
        result->new_chat_members = new_chat_members_values;
        result->left_chat_member = User::from_json(data["left_chat_member"]);
        result->new_chat_title = data["new_chat_title"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> new_chat_photo_values;
        new_chat_photo_values.reserve(new_chat_photo.size());
        for (auto& e : data["new_chat_photo"]) {
            new_chat_photo_values.push_back(std::vector<std::shared_ptr<PhotoSize>>::from_json(e));
        }
        result->new_chat_photo = new_chat_photo_values;
        result->delete_chat_photo = data["delete_chat_photo"].get<bool>();
        result->group_chat_created = data["group_chat_created"].get<bool>();
        result->supergroup_chat_created = data["supergroup_chat_created"].get<bool>();
        result->channel_chat_created = data["channel_chat_created"].get<bool>();
        result->message_auto_delete_timer_changed = MessageAutoDeleteTimerChanged::from_json(data["message_auto_delete_timer_changed"]);
        result->migrate_to_chat_id = ChatId::from_json(data["migrate_to_chat_id"]);
        result->migrate_from_chat_id = ChatId::from_json(data["migrate_from_chat_id"]);
        result->pinned_message = MaybeInaccessibleMessage::from_json(data["pinned_message"]);
        result->invoice = Invoice::from_json(data["invoice"]);
        result->successful_payment = SuccessfulPayment::from_json(data["successful_payment"]);
        result->refunded_payment = RefundedPayment::from_json(data["refunded_payment"]);
        result->users_shared = UsersShared::from_json(data["users_shared"]);
        result->chat_shared = ChatShared::from_json(data["chat_shared"]);
        result->gift = GiftInfo::from_json(data["gift"]);
        result->unique_gift = UniqueGiftInfo::from_json(data["unique_gift"]);
        result->connected_website = data["connected_website"].get<std::string>();
        result->write_access_allowed = WriteAccessAllowed::from_json(data["write_access_allowed"]);
        result->passport_data = PassportData::from_json(data["passport_data"]);
        result->proximity_alert_triggered = ProximityAlertTriggered::from_json(data["proximity_alert_triggered"]);
        result->boost_added = ChatBoostAdded::from_json(data["boost_added"]);
        result->chat_background_set = ChatBackground::from_json(data["chat_background_set"]);
        result->checklist_tasks_done = ChecklistTasksDone::from_json(data["checklist_tasks_done"]);
        result->checklist_tasks_added = ChecklistTasksAdded::from_json(data["checklist_tasks_added"]);
        result->direct_message_price_changed = DirectMessagePriceChanged::from_json(data["direct_message_price_changed"]);
        result->forum_topic_created = ForumTopicCreated::from_json(data["forum_topic_created"]);
        result->forum_topic_edited = ForumTopicEdited::from_json(data["forum_topic_edited"]);
        result->forum_topic_closed = ForumTopicClosed::from_json(data["forum_topic_closed"]);
        result->forum_topic_reopened = ForumTopicReopened::from_json(data["forum_topic_reopened"]);
        result->general_forum_topic_hidden = GeneralForumTopicHidden::from_json(data["general_forum_topic_hidden"]);
        result->general_forum_topic_unhidden = GeneralForumTopicUnhidden::from_json(data["general_forum_topic_unhidden"]);
        result->giveaway_created = GiveawayCreated::from_json(data["giveaway_created"]);
        result->giveaway = Giveaway::from_json(data["giveaway"]);
        result->giveaway_winners = GiveawayWinners::from_json(data["giveaway_winners"]);
        result->giveaway_completed = GiveawayCompleted::from_json(data["giveaway_completed"]);
        result->paid_message_price_changed = PaidMessagePriceChanged::from_json(data["paid_message_price_changed"]);
        result->suggested_post_approved = SuggestedPostApproved::from_json(data["suggested_post_approved"]);
        result->suggested_post_approval_failed = SuggestedPostApprovalFailed::from_json(data["suggested_post_approval_failed"]);
        result->suggested_post_declined = SuggestedPostDeclined::from_json(data["suggested_post_declined"]);
        result->suggested_post_paid = SuggestedPostPaid::from_json(data["suggested_post_paid"]);
        result->suggested_post_refunded = SuggestedPostRefunded::from_json(data["suggested_post_refunded"]);
        result->video_chat_scheduled = VideoChatScheduled::from_json(data["video_chat_scheduled"]);
        result->video_chat_started = VideoChatStarted::from_json(data["video_chat_started"]);
        result->video_chat_ended = VideoChatEnded::from_json(data["video_chat_ended"]);
        result->video_chat_participants_invited = VideoChatParticipantsInvited::from_json(data["video_chat_participants_invited"]);
        result->web_app_data = WebAppData::from_json(data["web_app_data"]);
        result->reply_markup = InlineKeyboardMarkup::from_json(data["reply_markup"]);
        return result;
    }
}
