// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Message.hpp"
#include "DirectMessagesTopic.hpp"
#include "User.hpp"
#include "Chat.hpp"
#include "MessageOrigin.hpp"
#include "ExternalReplyInfo.hpp"
#include "TextQuote.hpp"
#include "Story.hpp"
#include "LinkPreviewOptions.hpp"
#include "SuggestedPostInfo.hpp"
#include "Animation.hpp"
#include "Audio.hpp"
#include "Document.hpp"
#include "PaidMediaInfo.hpp"
#include "Sticker.hpp"
#include "Video.hpp"
#include "VideoNote.hpp"
#include "Voice.hpp"
#include "Checklist.hpp"
#include "Contact.hpp"
#include "Dice.hpp"
#include "Game.hpp"
#include "Poll.hpp"
#include "Venue.hpp"
#include "Location.hpp"
#include "MessageAutoDeleteTimerChanged.hpp"
#include "MaybeInaccessibleMessage.hpp"
#include "Invoice.hpp"
#include "SuccessfulPayment.hpp"
#include "RefundedPayment.hpp"
#include "UsersShared.hpp"
#include "ChatShared.hpp"
#include "GiftInfo.hpp"
#include "UniqueGiftInfo.hpp"
#include "WriteAccessAllowed.hpp"
#include "PassportData.hpp"
#include "ProximityAlertTriggered.hpp"
#include "ChatBoostAdded.hpp"
#include "ChatBackground.hpp"
#include "ChecklistTasksDone.hpp"
#include "ChecklistTasksAdded.hpp"
#include "DirectMessagePriceChanged.hpp"
#include "ForumTopicCreated.hpp"
#include "ForumTopicEdited.hpp"
#include "GiveawayCreated.hpp"
#include "Giveaway.hpp"
#include "GiveawayWinners.hpp"
#include "GiveawayCompleted.hpp"
#include "PaidMessagePriceChanged.hpp"
#include "SuggestedPostApproved.hpp"
#include "SuggestedPostApprovalFailed.hpp"
#include "SuggestedPostDeclined.hpp"
#include "SuggestedPostPaid.hpp"
#include "SuggestedPostRefunded.hpp"
#include "VideoChatScheduled.hpp"
#include "VideoChatEnded.hpp"
#include "VideoChatParticipantsInvited.hpp"
#include "WebAppData.hpp"
#include "InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const Message& value) {
        j = json::object();
        j["message_id"] = value.message_id;
        j["message_thread_id"] = value.message_thread_id;
        j["direct_messages_topic"] = value.direct_messages_topic;
        j["from"] = value.from;
        j["sender_chat"] = value.sender_chat;
        j["sender_boost_count"] = value.sender_boost_count;
        j["sender_business_bot"] = value.sender_business_bot;
        j["date"] = value.date;
        j["business_connection_id"] = value.business_connection_id;
        j["chat"] = value.chat;
        j["forward_origin"] = value.forward_origin;
        j["is_topic_message"] = value.is_topic_message;
        j["is_automatic_forward"] = value.is_automatic_forward;
        j["reply_to_message"] = value.reply_to_message;
        j["external_reply"] = value.external_reply;
        j["quote"] = value.quote;
        j["reply_to_story"] = value.reply_to_story;
        j["reply_to_checklist_task_id"] = value.reply_to_checklist_task_id;
        j["via_bot"] = value.via_bot;
        j["edit_date"] = value.edit_date;
        j["has_protected_content"] = value.has_protected_content;
        j["is_from_offline"] = value.is_from_offline;
        j["is_paid_post"] = value.is_paid_post;
        j["media_group_id"] = value.media_group_id;
        j["author_signature"] = value.author_signature;
        j["paid_star_count"] = value.paid_star_count;
        j["text"] = value.text;
        j["entities"] = value.entities;
        j["link_preview_options"] = value.link_preview_options;
        j["suggested_post_info"] = value.suggested_post_info;
        j["effect_id"] = value.effect_id;
        j["animation"] = value.animation;
        j["audio"] = value.audio;
        j["document"] = value.document;
        j["paid_media"] = value.paid_media;
        j["photo"] = value.photo;
        j["sticker"] = value.sticker;
        j["story"] = value.story;
        j["video"] = value.video;
        j["video_note"] = value.video_note;
        j["voice"] = value.voice;
        j["caption"] = value.caption;
        j["caption_entities"] = value.caption_entities;
        j["show_caption_above_media"] = value.show_caption_above_media;
        j["has_media_spoiler"] = value.has_media_spoiler;
        j["checklist"] = value.checklist;
        j["contact"] = value.contact;
        j["dice"] = value.dice;
        j["game"] = value.game;
        j["poll"] = value.poll;
        j["venue"] = value.venue;
        j["location"] = value.location;
        j["new_chat_members"] = value.new_chat_members;
        j["left_chat_member"] = value.left_chat_member;
        j["new_chat_title"] = value.new_chat_title;
        j["new_chat_photo"] = value.new_chat_photo;
        j["delete_chat_photo"] = value.delete_chat_photo;
        j["group_chat_created"] = value.group_chat_created;
        j["supergroup_chat_created"] = value.supergroup_chat_created;
        j["channel_chat_created"] = value.channel_chat_created;
        j["message_auto_delete_timer_changed"] = value.message_auto_delete_timer_changed;
        j["migrate_to_chat_id"] = value.migrate_to_chat_id;
        j["migrate_from_chat_id"] = value.migrate_from_chat_id;
        j["pinned_message"] = value.pinned_message;
        j["invoice"] = value.invoice;
        j["successful_payment"] = value.successful_payment;
        j["refunded_payment"] = value.refunded_payment;
        j["users_shared"] = value.users_shared;
        j["chat_shared"] = value.chat_shared;
        j["gift"] = value.gift;
        j["unique_gift"] = value.unique_gift;
        j["gift_upgrade_sent"] = value.gift_upgrade_sent;
        j["connected_website"] = value.connected_website;
        j["write_access_allowed"] = value.write_access_allowed;
        j["passport_data"] = value.passport_data;
        j["proximity_alert_triggered"] = value.proximity_alert_triggered;
        j["boost_added"] = value.boost_added;
        j["chat_background_set"] = value.chat_background_set;
        j["checklist_tasks_done"] = value.checklist_tasks_done;
        j["checklist_tasks_added"] = value.checklist_tasks_added;
        j["direct_message_price_changed"] = value.direct_message_price_changed;
        j["forum_topic_created"] = value.forum_topic_created;
        j["forum_topic_edited"] = value.forum_topic_edited;
        j["forum_topic_closed"] = value.forum_topic_closed;
        j["forum_topic_reopened"] = value.forum_topic_reopened;
        j["general_forum_topic_hidden"] = value.general_forum_topic_hidden;
        j["general_forum_topic_unhidden"] = value.general_forum_topic_unhidden;
        j["giveaway_created"] = value.giveaway_created;
        j["giveaway"] = value.giveaway;
        j["giveaway_winners"] = value.giveaway_winners;
        j["giveaway_completed"] = value.giveaway_completed;
        j["paid_message_price_changed"] = value.paid_message_price_changed;
        j["suggested_post_approved"] = value.suggested_post_approved;
        j["suggested_post_approval_failed"] = value.suggested_post_approval_failed;
        j["suggested_post_declined"] = value.suggested_post_declined;
        j["suggested_post_paid"] = value.suggested_post_paid;
        j["suggested_post_refunded"] = value.suggested_post_refunded;
        j["video_chat_scheduled"] = value.video_chat_scheduled;
        j["video_chat_started"] = value.video_chat_started;
        j["video_chat_ended"] = value.video_chat_ended;
        j["video_chat_participants_invited"] = value.video_chat_participants_invited;
        j["web_app_data"] = value.web_app_data;
        j["reply_markup"] = value.reply_markup;
    }

    void from_json(const json& j, Message& value) {
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("message_thread_id")) {
            j.at("message_thread_id").get_to(value.message_thread_id);
        }
        if (j.contains("direct_messages_topic")) {
            j.at("direct_messages_topic").get_to(value.direct_messages_topic);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("sender_chat")) {
            j.at("sender_chat").get_to(value.sender_chat);
        }
        if (j.contains("sender_boost_count")) {
            j.at("sender_boost_count").get_to(value.sender_boost_count);
        }
        if (j.contains("sender_business_bot")) {
            j.at("sender_business_bot").get_to(value.sender_business_bot);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("chat")) {
            j.at("chat").get_to(value.chat);
        }
        if (j.contains("forward_origin")) {
            j.at("forward_origin").get_to(value.forward_origin);
        }
        if (j.contains("is_topic_message")) {
            j.at("is_topic_message").get_to(value.is_topic_message);
        }
        if (j.contains("is_automatic_forward")) {
            j.at("is_automatic_forward").get_to(value.is_automatic_forward);
        }
        if (j.contains("reply_to_message")) {
            j.at("reply_to_message").get_to(value.reply_to_message);
        }
        if (j.contains("external_reply")) {
            j.at("external_reply").get_to(value.external_reply);
        }
        if (j.contains("quote")) {
            j.at("quote").get_to(value.quote);
        }
        if (j.contains("reply_to_story")) {
            j.at("reply_to_story").get_to(value.reply_to_story);
        }
        if (j.contains("reply_to_checklist_task_id")) {
            j.at("reply_to_checklist_task_id").get_to(value.reply_to_checklist_task_id);
        }
        if (j.contains("via_bot")) {
            j.at("via_bot").get_to(value.via_bot);
        }
        if (j.contains("edit_date")) {
            j.at("edit_date").get_to(value.edit_date);
        }
        if (j.contains("has_protected_content")) {
            j.at("has_protected_content").get_to(value.has_protected_content);
        }
        if (j.contains("is_from_offline")) {
            j.at("is_from_offline").get_to(value.is_from_offline);
        }
        if (j.contains("is_paid_post")) {
            j.at("is_paid_post").get_to(value.is_paid_post);
        }
        if (j.contains("media_group_id")) {
            j.at("media_group_id").get_to(value.media_group_id);
        }
        if (j.contains("author_signature")) {
            j.at("author_signature").get_to(value.author_signature);
        }
        if (j.contains("paid_star_count")) {
            j.at("paid_star_count").get_to(value.paid_star_count);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("entities")) {
            j.at("entities").get_to(value.entities);
        }
        if (j.contains("link_preview_options")) {
            j.at("link_preview_options").get_to(value.link_preview_options);
        }
        if (j.contains("suggested_post_info")) {
            j.at("suggested_post_info").get_to(value.suggested_post_info);
        }
        if (j.contains("effect_id")) {
            j.at("effect_id").get_to(value.effect_id);
        }
        if (j.contains("animation")) {
            j.at("animation").get_to(value.animation);
        }
        if (j.contains("audio")) {
            j.at("audio").get_to(value.audio);
        }
        if (j.contains("document")) {
            j.at("document").get_to(value.document);
        }
        if (j.contains("paid_media")) {
            j.at("paid_media").get_to(value.paid_media);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("story")) {
            j.at("story").get_to(value.story);
        }
        if (j.contains("video")) {
            j.at("video").get_to(value.video);
        }
        if (j.contains("video_note")) {
            j.at("video_note").get_to(value.video_note);
        }
        if (j.contains("voice")) {
            j.at("voice").get_to(value.voice);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("has_media_spoiler")) {
            j.at("has_media_spoiler").get_to(value.has_media_spoiler);
        }
        if (j.contains("checklist")) {
            j.at("checklist").get_to(value.checklist);
        }
        if (j.contains("contact")) {
            j.at("contact").get_to(value.contact);
        }
        if (j.contains("dice")) {
            j.at("dice").get_to(value.dice);
        }
        if (j.contains("game")) {
            j.at("game").get_to(value.game);
        }
        if (j.contains("poll")) {
            j.at("poll").get_to(value.poll);
        }
        if (j.contains("venue")) {
            j.at("venue").get_to(value.venue);
        }
        if (j.contains("location")) {
            j.at("location").get_to(value.location);
        }
        if (j.contains("new_chat_members")) {
            j.at("new_chat_members").get_to(value.new_chat_members);
        }
        if (j.contains("left_chat_member")) {
            j.at("left_chat_member").get_to(value.left_chat_member);
        }
        if (j.contains("new_chat_title")) {
            j.at("new_chat_title").get_to(value.new_chat_title);
        }
        if (j.contains("new_chat_photo")) {
            j.at("new_chat_photo").get_to(value.new_chat_photo);
        }
        if (j.contains("delete_chat_photo")) {
            j.at("delete_chat_photo").get_to(value.delete_chat_photo);
        }
        if (j.contains("group_chat_created")) {
            j.at("group_chat_created").get_to(value.group_chat_created);
        }
        if (j.contains("supergroup_chat_created")) {
            j.at("supergroup_chat_created").get_to(value.supergroup_chat_created);
        }
        if (j.contains("channel_chat_created")) {
            j.at("channel_chat_created").get_to(value.channel_chat_created);
        }
        if (j.contains("message_auto_delete_timer_changed")) {
            j.at("message_auto_delete_timer_changed").get_to(value.message_auto_delete_timer_changed);
        }
        if (j.contains("migrate_to_chat_id")) {
            j.at("migrate_to_chat_id").get_to(value.migrate_to_chat_id);
        }
        if (j.contains("migrate_from_chat_id")) {
            j.at("migrate_from_chat_id").get_to(value.migrate_from_chat_id);
        }
        if (j.contains("pinned_message")) {
            j.at("pinned_message").get_to(value.pinned_message);
        }
        if (j.contains("invoice")) {
            j.at("invoice").get_to(value.invoice);
        }
        if (j.contains("successful_payment")) {
            j.at("successful_payment").get_to(value.successful_payment);
        }
        if (j.contains("refunded_payment")) {
            j.at("refunded_payment").get_to(value.refunded_payment);
        }
        if (j.contains("users_shared")) {
            j.at("users_shared").get_to(value.users_shared);
        }
        if (j.contains("chat_shared")) {
            j.at("chat_shared").get_to(value.chat_shared);
        }
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("unique_gift")) {
            j.at("unique_gift").get_to(value.unique_gift);
        }
        if (j.contains("gift_upgrade_sent")) {
            j.at("gift_upgrade_sent").get_to(value.gift_upgrade_sent);
        }
        if (j.contains("connected_website")) {
            j.at("connected_website").get_to(value.connected_website);
        }
        if (j.contains("write_access_allowed")) {
            j.at("write_access_allowed").get_to(value.write_access_allowed);
        }
        if (j.contains("passport_data")) {
            j.at("passport_data").get_to(value.passport_data);
        }
        if (j.contains("proximity_alert_triggered")) {
            j.at("proximity_alert_triggered").get_to(value.proximity_alert_triggered);
        }
        if (j.contains("boost_added")) {
            j.at("boost_added").get_to(value.boost_added);
        }
        if (j.contains("chat_background_set")) {
            j.at("chat_background_set").get_to(value.chat_background_set);
        }
        if (j.contains("checklist_tasks_done")) {
            j.at("checklist_tasks_done").get_to(value.checklist_tasks_done);
        }
        if (j.contains("checklist_tasks_added")) {
            j.at("checklist_tasks_added").get_to(value.checklist_tasks_added);
        }
        if (j.contains("direct_message_price_changed")) {
            j.at("direct_message_price_changed").get_to(value.direct_message_price_changed);
        }
        if (j.contains("forum_topic_created")) {
            j.at("forum_topic_created").get_to(value.forum_topic_created);
        }
        if (j.contains("forum_topic_edited")) {
            j.at("forum_topic_edited").get_to(value.forum_topic_edited);
        }
        if (j.contains("forum_topic_closed")) {
            j.at("forum_topic_closed").get_to(value.forum_topic_closed);
        }
        if (j.contains("forum_topic_reopened")) {
            j.at("forum_topic_reopened").get_to(value.forum_topic_reopened);
        }
        if (j.contains("general_forum_topic_hidden")) {
            j.at("general_forum_topic_hidden").get_to(value.general_forum_topic_hidden);
        }
        if (j.contains("general_forum_topic_unhidden")) {
            j.at("general_forum_topic_unhidden").get_to(value.general_forum_topic_unhidden);
        }
        if (j.contains("giveaway_created")) {
            j.at("giveaway_created").get_to(value.giveaway_created);
        }
        if (j.contains("giveaway")) {
            j.at("giveaway").get_to(value.giveaway);
        }
        if (j.contains("giveaway_winners")) {
            j.at("giveaway_winners").get_to(value.giveaway_winners);
        }
        if (j.contains("giveaway_completed")) {
            j.at("giveaway_completed").get_to(value.giveaway_completed);
        }
        if (j.contains("paid_message_price_changed")) {
            j.at("paid_message_price_changed").get_to(value.paid_message_price_changed);
        }
        if (j.contains("suggested_post_approved")) {
            j.at("suggested_post_approved").get_to(value.suggested_post_approved);
        }
        if (j.contains("suggested_post_approval_failed")) {
            j.at("suggested_post_approval_failed").get_to(value.suggested_post_approval_failed);
        }
        if (j.contains("suggested_post_declined")) {
            j.at("suggested_post_declined").get_to(value.suggested_post_declined);
        }
        if (j.contains("suggested_post_paid")) {
            j.at("suggested_post_paid").get_to(value.suggested_post_paid);
        }
        if (j.contains("suggested_post_refunded")) {
            j.at("suggested_post_refunded").get_to(value.suggested_post_refunded);
        }
        if (j.contains("video_chat_scheduled")) {
            j.at("video_chat_scheduled").get_to(value.video_chat_scheduled);
        }
        if (j.contains("video_chat_started")) {
            j.at("video_chat_started").get_to(value.video_chat_started);
        }
        if (j.contains("video_chat_ended")) {
            j.at("video_chat_ended").get_to(value.video_chat_ended);
        }
        if (j.contains("video_chat_participants_invited")) {
            j.at("video_chat_participants_invited").get_to(value.video_chat_participants_invited);
        }
        if (j.contains("web_app_data")) {
            j.at("web_app_data").get_to(value.web_app_data);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
