// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about a change in auto-delete timer settings.
     *
     * @param message_auto_delete_time New auto-delete time for messages in the chat; in seconds
     */
    struct MessageAutoDeleteTimerChanged : public TelegramModel {
        virtual ~MessageAutoDeleteTimerChanged() = default;
        // New auto-delete time for messages in the chat; in seconds
        std::int64_t message_auto_delete_time;

        json to_json() const override;
        static std::shared_ptr<MessageAutoDeleteTimerChanged> from_json(const json& data);
    };
}
