// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "MessageOriginChat.hpp"
#include "Chat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json MessageOriginChat::to_json() const {
        json j;
        j["type"] = type_;
        j["date"] = date;
        j["sender_chat"] = sender_chat->to_json();
        j["author_signature"] = author_signature;
        return j.dump();
    }
    std::shared_ptr<MessageOriginChat> MessageOriginChat::from_json(const json& data) {
        auto result(std::make_shared<MessageOriginChat>());
        result->type_ = data["type_"].get<std::string>();
        result->date = data["date"].get<std::int64_t>();
        result->sender_chat = std::shared_ptr<Chat>::from_json(data["sender_chat"]);
        result->author_signature = data["author_signature"].get<std::string>();
        return result;
    }
}
