// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "OrderInfo.hpp"
#include "ShippingAddress.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const OrderInfo& value) {
        j = json::object();
        j["name"] = value.name;
        j["phone_number"] = value.phone_number;
        j["email"] = value.email;
        j["shipping_address"] = value.shipping_address;
    }

    void from_json(const json& j, OrderInfo& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("phone_number")) {
            j.at("phone_number").get_to(value.phone_number);
        }
        if (j.contains("email")) {
            j.at("email").get_to(value.email);
        }
        if (j.contains("shipping_address")) {
            j.at("shipping_address").get_to(value.shipping_address);
        }
    }
}
