// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "OwnedGifts.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json OwnedGifts::to_json() const {
        json j;
        j["total_count"] = total_count;
        std::vector<json> gifts_values;
        gifts_values.reserve(gifts.size());
        for (auto& e : gifts) {
            gifts_values.push_back(e->to_json());
        }
        j["gifts"] = gifts_values;
        j["next_offset"] = next_offset;
        return j.dump();
    }
    std::shared_ptr<OwnedGifts> OwnedGifts::from_json(const json& data) {
        auto result(std::make_shared<OwnedGifts>());
        result->total_count = data["total_count"].get<std::int64_t>();
        std::vector<std::vector<std::shared_ptr<OwnedGift>>> gifts_values;
        gifts_values.reserve(gifts.size());
        for (auto& e : data["gifts"]) {
            gifts_values.push_back(std::vector<std::shared_ptr<OwnedGift>>::from_json(e));
        }
        result->gifts = gifts_values;
        result->next_offset = data["next_offset"].get<std::string>();
        return result;
    }
}
