// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "OwnedGiftRegular.hpp"
#include "Gift.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const OwnedGiftRegular& value) {
        j = json::object();
        j["type"] = value.type_;
        j["gift"] = value.gift;
        j["owned_gift_id"] = value.owned_gift_id;
        j["sender_user"] = value.sender_user;
        j["send_date"] = value.send_date;
        j["text"] = value.text;
        j["entities"] = value.entities;
        j["is_private"] = value.is_private;
        j["is_saved"] = value.is_saved;
        j["can_be_upgraded"] = value.can_be_upgraded;
        j["was_refunded"] = value.was_refunded;
        j["convert_star_count"] = value.convert_star_count;
        j["prepaid_upgrade_star_count"] = value.prepaid_upgrade_star_count;
        j["is_upgrade_separate"] = value.is_upgrade_separate;
        j["unique_gift_number"] = value.unique_gift_number;
    }

    void from_json(const json& j, OwnedGiftRegular& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("owned_gift_id")) {
            j.at("owned_gift_id").get_to(value.owned_gift_id);
        }
        if (j.contains("sender_user")) {
            j.at("sender_user").get_to(value.sender_user);
        }
        if (j.contains("send_date")) {
            j.at("send_date").get_to(value.send_date);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("entities")) {
            j.at("entities").get_to(value.entities);
        }
        if (j.contains("is_private")) {
            j.at("is_private").get_to(value.is_private);
        }
        if (j.contains("is_saved")) {
            j.at("is_saved").get_to(value.is_saved);
        }
        if (j.contains("can_be_upgraded")) {
            j.at("can_be_upgraded").get_to(value.can_be_upgraded);
        }
        if (j.contains("was_refunded")) {
            j.at("was_refunded").get_to(value.was_refunded);
        }
        if (j.contains("convert_star_count")) {
            j.at("convert_star_count").get_to(value.convert_star_count);
        }
        if (j.contains("prepaid_upgrade_star_count")) {
            j.at("prepaid_upgrade_star_count").get_to(value.prepaid_upgrade_star_count);
        }
        if (j.contains("is_upgrade_separate")) {
            j.at("is_upgrade_separate").get_to(value.is_upgrade_separate);
        }
        if (j.contains("unique_gift_number")) {
            j.at("unique_gift_number").get_to(value.unique_gift_number);
        }
    }
}
