// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "PaidMedia.hpp"
#include "PhotoSize.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The paid media is a photo.
     *
     * @param type Type of the paid media, always “photo”
     * @param photo The photo
     */
    struct PaidMediaPhoto : public PaidMedia {
        virtual ~PaidMediaPhoto() = default;
        // Type of the paid media, always “photo”
        std::string type_;

        // The photo
        std::vector<std::shared_ptr<PhotoSize>> photo;
    };
}
