// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PaidMediaPhoto.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PaidMediaPhoto::to_json() const {
        json j;
        j["type"] = type_;
        std::vector<json> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : photo) {
            photo_values.push_back(e->to_json());
        }
        j["photo"] = photo_values;
        return j.dump();
    }
    std::shared_ptr<PaidMediaPhoto> PaidMediaPhoto::from_json(const json& data) {
        auto result(std::make_shared<PaidMediaPhoto>());
        result->type_ = data["type_"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> photo_values;
        photo_values.reserve(photo.size());
        for (auto& e : data["photo"]) {
            photo_values.push_back(std::vector<std::shared_ptr<PhotoSize>>::from_json(e));
        }
        result->photo = photo_values;
        return result;
    }
}
