// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PaidMediaPreview.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PaidMediaPreview::to_json() const {
        json j;
        j["type"] = type_;
        j["width"] = width;
        j["height"] = height;
        j["duration"] = duration;
        return j.dump();
    }
    std::shared_ptr<PaidMediaPreview> PaidMediaPreview::from_json(const json& data) {
        auto result(std::make_shared<PaidMediaPreview>());
        result->type_ = data["type_"].get<std::string>();
        result->width = data["width"].get<std::int64_t>();
        result->height = data["height"].get<std::int64_t>();
        result->duration = data["duration"].get<std::int64_t>();
        return result;
    }
}
