// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PaidMediaPurchased.hpp"
#include "User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const PaidMediaPurchased& value) {
        j = json::object();
        j["from"] = value.from;
        j["paid_media_payload"] = value.paid_media_payload;
    }

    void from_json(const json& j, PaidMediaPurchased& value) {
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("paid_media_payload")) {
            j.at("paid_media_payload").get_to(value.paid_media_payload);
        }
    }
}
