// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "PassportElementError.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents an issue with the translated version of a document. The error is considered resolved when a file with the document translation change.
     *
     * @param source Error source, must be translation_files
     * @param type Type of element of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”
     * @param file_hashes List of base64-encoded file hashes
     * @param message Error message
     */
    struct PassportElementErrorTranslationFiles : public PassportElementError {
        virtual ~PassportElementErrorTranslationFiles() = default;
        // Error source, must be translation_files
        std::string source;

        // Type of element of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”
        std::string type_;

        // List of base64-encoded file hashes
        std::vector<std::string> file_hashes;

        // Error message
        std::string message;

        json to_json() const override;
        static std::shared_ptr<PassportElementErrorTranslationFiles> from_json(const json& data);
    };
}
