// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PassportData.hpp"
#include "EncryptedCredentials.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const PassportData& value) {
        j = json::object();
        j["data"] = value.data;
        j["credentials"] = value.credentials;
    }

    void from_json(const json& j, PassportData& value) {
        if (j.contains("data")) {
            j.at("data").get_to(value.data);
        }
        if (j.contains("credentials")) {
            j.at("credentials").get_to(value.credentials);
        }
    }
}
