// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PassportElementErrorDataField.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PassportElementErrorDataField::to_json() const {
        json j;
        j["source"] = source;
        j["type"] = type_;
        j["field_name"] = field_name;
        j["data_hash"] = data_hash;
        j["message"] = message;
        return j.dump();
    }
    std::shared_ptr<PassportElementErrorDataField> PassportElementErrorDataField::from_json(const json& data) {
        auto result(std::make_shared<PassportElementErrorDataField>());
        result->source = data["source"].get<std::string>();
        result->type_ = data["type_"].get<std::string>();
        result->field_name = data["field_name"].get<std::string>();
        result->data_hash = data["data_hash"].get<std::string>();
        result->message = data["message"].get<std::string>();
        return result;
    }
}
