// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PassportElementErrorFiles.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PassportElementErrorFiles::to_json() const {
        json j;
        j["source"] = source;
        j["type"] = type_;
        std::vector<json> file_hashes_values;
        file_hashes_values.reserve(file_hashes.size());
        for (auto& e : file_hashes) {
            file_hashes_values.push_back(e);
        }
        j["file_hashes"] = file_hashes_values;
        j["message"] = message;
        return j.dump();
    }
    std::shared_ptr<PassportElementErrorFiles> PassportElementErrorFiles::from_json(const json& data) {
        auto result(std::make_shared<PassportElementErrorFiles>());
        result->source = data["source"].get<std::string>();
        result->type_ = data["type_"].get<std::string>();
        std::vector<std::vector<std::string>> file_hashes_values;
        file_hashes_values.reserve(file_hashes.size());
        for (auto& e : data["file_hashes"]) {
            file_hashes_values.push_back(std::vector<std::string>::from_json(e));
        }
        result->file_hashes = file_hashes_values;
        result->message = data["message"].get<std::string>();
        return result;
    }
}
