// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PassportElementErrorFile.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PassportElementErrorFile::to_json() const {
        json j;
        j["source"] = source;
        j["type"] = type_;
        j["file_hash"] = file_hash;
        j["message"] = message;
        return j.dump();
    }
    std::shared_ptr<PassportElementErrorFile> PassportElementErrorFile::from_json(const json& data) {
        auto result(std::make_shared<PassportElementErrorFile>());
        result->source = data["source"].get<std::string>();
        result->type_ = data["type_"].get<std::string>();
        result->file_hash = data["file_hash"].get<std::string>();
        result->message = data["message"].get<std::string>();
        return result;
    }
}
