// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "PassportElementErrorUnspecified.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json PassportElementErrorUnspecified::to_json() const {
        json j;
        j["source"] = source;
        j["type"] = type_;
        j["element_hash"] = element_hash;
        j["message"] = message;
        return j.dump();
    }
    std::shared_ptr<PassportElementErrorUnspecified> PassportElementErrorUnspecified::from_json(const json& data) {
        auto result(std::make_shared<PassportElementErrorUnspecified>());
        result->source = data["source"].get<std::string>();
        result->type_ = data["type_"].get<std::string>();
        result->element_hash = data["element_hash"].get<std::string>();
        result->message = data["message"].get<std::string>();
        return result;
    }
}
