// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "Poll.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json Poll::to_json() const {
        json j;
        j["id"] = id;
        j["question"] = question;
        std::vector<json> question_entities_values;
        question_entities_values.reserve(question_entities.size());
        for (auto& e : question_entities) {
            question_entities_values.push_back(e->to_json());
        }
        j["question_entities"] = question_entities_values;
        std::vector<json> options_values;
        options_values.reserve(options.size());
        for (auto& e : options) {
            options_values.push_back(e->to_json());
        }
        j["options"] = options_values;
        j["total_voter_count"] = total_voter_count;
        j["is_closed"] = is_closed;
        j["is_anonymous"] = is_anonymous;
        j["type"] = type_;
        j["allows_multiple_answers"] = allows_multiple_answers;
        j["correct_option_id"] = correct_option_id;
        j["explanation"] = explanation;
        std::vector<json> explanation_entities_values;
        explanation_entities_values.reserve(explanation_entities.size());
        for (auto& e : explanation_entities) {
            explanation_entities_values.push_back(e->to_json());
        }
        j["explanation_entities"] = explanation_entities_values;
        j["open_period"] = open_period;
        j["close_date"] = close_date;
        return j.dump();
    }
    std::shared_ptr<Poll> Poll::from_json(const json& data) {
        auto result(std::make_shared<Poll>());
        result->id = data["id"].get<std::string>();
        result->question = data["question"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> question_entities_values;
        question_entities_values.reserve(question_entities.size());
        for (auto& e : data["question_entities"]) {
            question_entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->question_entities = question_entities_values;
        std::vector<std::vector<std::shared_ptr<PollOption>>> options_values;
        options_values.reserve(options.size());
        for (auto& e : data["options"]) {
            options_values.push_back(std::vector<std::shared_ptr<PollOption>>::from_json(e));
        }
        result->options = options_values;
        result->total_voter_count = data["total_voter_count"].get<std::int64_t>();
        result->is_closed = data["is_closed"].get<bool>();
        result->is_anonymous = data["is_anonymous"].get<bool>();
        result->type_ = data["type_"].get<std::string>();
        result->allows_multiple_answers = data["allows_multiple_answers"].get<bool>();
        result->correct_option_id = data["correct_option_id"].get<std::int64_t>();
        result->explanation = data["explanation"].get<std::string>();
        std::vector<std::vector<std::shared_ptr<MessageEntity>>> explanation_entities_values;
        explanation_entities_values.reserve(explanation_entities.size());
        for (auto& e : data["explanation_entities"]) {
            explanation_entities_values.push_back(std::vector<std::shared_ptr<MessageEntity>>::from_json(e));
        }
        result->explanation_entities = explanation_entities_values;
        result->open_period = data["open_period"].get<std::int64_t>();
        result->close_date = data["close_date"].get<std::int64_t>();
        return result;
    }
}
