// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "ReactionType.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The reaction is based on a custom emoji.
     *
     * @param type Type of the reaction, always “custom_emoji”
     * @param custom_emoji_id Custom emoji identifier
     */
    struct ReactionTypeCustomEmoji : public ReactionType {
        virtual ~ReactionTypeCustomEmoji() = default;
        // Type of the reaction, always “custom_emoji”
        std::string type_;

        // Custom emoji identifier
        std::string custom_emoji_id;

        json to_json() const override;
        static std::shared_ptr<ReactionTypeCustomEmoji> from_json(const json& data);
    };
}
