// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "ReactionType.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The reaction is paid.
     *
     * @param type Type of the reaction, always “paid”
     */
    struct ReactionTypePaid : public ReactionType {
        virtual ~ReactionTypePaid() = default;
        // Type of the reaction, always “paid”
        std::string type_;

        json to_json() const override;
        static std::shared_ptr<ReactionTypePaid> from_json(const json& data);
    };
}
