// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "ReplyKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const ReplyKeyboardMarkup& value) {
        j = json::object();
        j["keyboard"] = value.keyboard;
        j["is_persistent"] = value.is_persistent;
        j["resize_keyboard"] = value.resize_keyboard;
        j["one_time_keyboard"] = value.one_time_keyboard;
        j["input_field_placeholder"] = value.input_field_placeholder;
        j["selective"] = value.selective;
    }

    void from_json(const json& j, ReplyKeyboardMarkup& value) {
        if (j.contains("keyboard")) {
            j.at("keyboard").get_to(value.keyboard);
        }
        if (j.contains("is_persistent")) {
            j.at("is_persistent").get_to(value.is_persistent);
        }
        if (j.contains("resize_keyboard")) {
            j.at("resize_keyboard").get_to(value.resize_keyboard);
        }
        if (j.contains("one_time_keyboard")) {
            j.at("one_time_keyboard").get_to(value.one_time_keyboard);
        }
        if (j.contains("input_field_placeholder")) {
            j.at("input_field_placeholder").get_to(value.input_field_placeholder);
        }
        if (j.contains("selective")) {
            j.at("selective").get_to(value.selective);
        }
    }
}
