// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "RevenueWithdrawalStateSucceeded.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json RevenueWithdrawalStateSucceeded::to_json() const {
        json j;
        j["type"] = type_;
        j["date"] = date;
        j["url"] = url;
        return j.dump();
    }
    std::shared_ptr<RevenueWithdrawalStateSucceeded> RevenueWithdrawalStateSucceeded::from_json(const json& data) {
        auto result(std::make_shared<RevenueWithdrawalStateSucceeded>());
        result->type_ = data["type_"].get<std::string>();
        result->date = data["date"].get<std::int64_t>();
        result->url = data["url"].get<std::string>();
        return result;
    }
}
