// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "RevenueWithdrawalState.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The withdrawal succeeded.
     *
     * @param type Type of the state, always “succeeded”
     * @param date Date the withdrawal was completed in Unix time
     * @param url An HTTPS URL that can be used to see transaction details
     */
    struct RevenueWithdrawalStateSucceeded : public RevenueWithdrawalState {
        virtual ~RevenueWithdrawalStateSucceeded() = default;
        // Type of the state, always “succeeded”
        std::string type_;

        // Date the withdrawal was completed in Unix time
        std::int64_t date;

        // An HTTPS URL that can be used to see transaction details
        std::string url;

        json to_json() const override;
        static std::shared_ptr<RevenueWithdrawalStateSucceeded> from_json(const json& data);
    };
}
