// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "RevenueWithdrawalStatePending.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json RevenueWithdrawalStatePending::to_json() const {
        json j;
        j["type"] = type_;
        return j.dump();
    }
    std::shared_ptr<RevenueWithdrawalStatePending> RevenueWithdrawalStatePending::from_json(const json& data) {
        auto result(std::make_shared<RevenueWithdrawalStatePending>());
        result->type_ = data["type_"].get<std::string>();
        return result;
    }
}
