// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "RevenueWithdrawalState.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The withdrawal is in progress.
     *
     * @param type Type of the state, always “pending”
     */
    struct RevenueWithdrawalStatePending : public RevenueWithdrawalState {
        virtual ~RevenueWithdrawalStatePending() = default;
        // Type of the state, always “pending”
        std::string type_;

        json to_json() const override;
        static std::shared_ptr<RevenueWithdrawalStatePending> from_json(const json& data);
    };
}
