// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    struct LinkPreviewOptions;
    struct SuggestedPostParameters;
    struct ReplyParameters;
    struct KeyboardOption;

    using json = nlohmann::json;

    /**
     * Use this method to send text messages. On success, the sent Message is returned.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_thread_id Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
     * @param direct_messages_topic_id Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
     * @param text Text of the message to be sent, 1-4096 characters after entities parsing
     * @param parse_mode Mode for parsing entities in the message text. See formatting options for more details.
     * @param entities A JSON-serialized list of special entities that appear in message text, which can be specified instead of parse_mode
     * @param link_preview_options Link preview generation options for the message
     * @param disable_notification Sends the message silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the sent message from forwarding and saving
     * @param allow_paid_broadcast Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
     * @param message_effect_id Unique identifier of the message effect to be added to the message; for private chats only
     * @param suggested_post_parameters A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
     * @param reply_parameters Description of the message to reply to
     * @param reply_markup Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
     */
    struct SendMessageRequest {
        // Unique identifier of the business connection on behalf of which the message will be sent
        BusinessConnectionId business_connection_id;

        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
        MessageThreadId message_thread_id;

        // Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
        std::int64_t direct_messages_topic_id;

        // Text of the message to be sent, 1-4096 characters after entities parsing
        std::string text;

        // Mode for parsing entities in the message text. See formatting options for more details.
        ParseMode parse_mode;

        // A JSON-serialized list of special entities that appear in message text, which can be specified instead of parse_mode
        std::vector<std::shared_ptr<MessageEntity>> entities;

        // Link preview generation options for the message
        std::shared_ptr<LinkPreviewOptions> link_preview_options;

        // Sends the message silently. Users will receive a notification with no sound.
        bool disable_notification;

        // Protects the contents of the sent message from forwarding and saving
        bool protect_content;

        // Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
        bool allow_paid_broadcast;

        // Unique identifier of the message effect to be added to the message; for private chats only
        MessageEffectId message_effect_id;

        // A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
        std::shared_ptr<SuggestedPostParameters> suggested_post_parameters;

        // Description of the message to reply to
        std::shared_ptr<ReplyParameters> reply_parameters;

        // Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
        std::shared_ptr<KeyboardOption> reply_markup;
    };
}
