// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SentWebAppMessage.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SentWebAppMessage& value) {
        j = json::object();
        j["inline_message_id"] = value.inline_message_id;
    }

    void from_json(const json& j, SentWebAppMessage& value) {
        if (j.contains("inline_message_id")) {
            j.at("inline_message_id").get_to(value.inline_message_id);
        }
    }
}
