// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    struct AcceptedGiftTypes;

    using json = nlohmann::json;

    /**
     * Changes the privacy settings pertaining to incoming gifts in a managed business account. Requires the can_change_gift_settings business bot right. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param show_gift_button Pass True, if a button for sending a gift to the user or by the business account must always be shown in the input field
     * @param accepted_gift_types Types of gifts accepted by the business account
     */
    struct SetBusinessAccountGiftSettingsRequest {
        // Unique identifier of the business connection
        BusinessConnectionId business_connection_id;

        // Pass True, if a button for sending a gift to the user or by the business account must always be shown in the input field
        bool show_gift_button;

        // Types of gifts accepted by the business account
        std::shared_ptr<AcceptedGiftTypes> accepted_gift_types;
    };
}
