// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    struct InputProfilePhoto;

    using json = nlohmann::json;

    /**
     * Changes the profile photo of a managed business account. Requires the can_edit_profile_photo business bot right. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param photo The new profile photo to set
     * @param is_public Pass True to set the public photo, which will be visible even if the main photo is hidden by the business account's privacy settings. An account can have only one public photo.
     */
    struct SetBusinessAccountProfilePhotoRequest {
        // Unique identifier of the business connection
        BusinessConnectionId business_connection_id;

        // The new profile photo to set
        std::shared_ptr<InputProfilePhoto> photo;

        // Pass True to set the public photo, which will be visible even if the main photo is hidden by the business account's privacy settings. An account can have only one public photo.
        bool is_public;
    };
}
