// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SharedUser.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SharedUser& value) {
        j = json::object();
        j["user_id"] = value.user_id;
        j["first_name"] = value.first_name;
        j["last_name"] = value.last_name;
        j["username"] = value.username;
        j["photo"] = value.photo;
    }

    void from_json(const json& j, SharedUser& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("username")) {
            j.at("username").get_to(value.username);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
    }
}
