// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "StarTransaction.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Contains a list of Telegram Star transactions.
     *
     * @param transactions The list of transactions
     */
    struct StarTransactions : public TelegramModel {
        virtual ~StarTransactions() = default;
        // The list of transactions
        std::vector<std::shared_ptr<StarTransaction>> transactions;
    };
}
