// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "StarTransaction.hpp"
#include "TransactionPartner.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json StarTransaction::to_json() const {
        json j;
        j["id"] = id;
        j["amount"] = amount;
        j["nanostar_amount"] = nanostar_amount;
        j["date"] = date;
        j["source"] = source->to_json();
        j["receiver"] = receiver->to_json();
        return j.dump();
    }
    std::shared_ptr<StarTransaction> StarTransaction::from_json(const json& data) {
        auto result(std::make_shared<StarTransaction>());
        result->id = data["id"].get<std::string>();
        result->amount = data["amount"].get<std::int64_t>();
        result->nanostar_amount = data["nanostar_amount"].get<std::int64_t>();
        result->date = data["date"].get<std::int64_t>();
        result->source = std::shared_ptr<TransactionPartner>::from_json(data["source"]);
        result->receiver = std::shared_ptr<TransactionPartner>::from_json(data["receiver"]);
        return result;
    }
}
