// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct InlineKeyboardMarkup;

    using json = nlohmann::json;

    /**
     * Use this method to stop a poll which was sent by the bot. On success, the stopped Poll is returned.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message to be edited was sent
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Identifier of the original message with the poll
     * @param reply_markup A JSON-serialized object for a new message inline keyboard.
     */
    struct StopPollRequest {
        // Unique identifier of the business connection on behalf of which the message to be edited was sent
        BusinessConnectionId business_connection_id;

        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        ChatId chat_id;

        // Identifier of the original message with the poll
        MessageId message_id;

        // A JSON-serialized object for a new message inline keyboard.
        std::shared_ptr<InlineKeyboardMarkup> reply_markup;
    };
}
