// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "StoryAreaTypeLink.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json StoryAreaTypeLink::to_json() const {
        json j;
        j["type"] = type_;
        j["url"] = url;
        return j.dump();
    }
    std::shared_ptr<StoryAreaTypeLink> StoryAreaTypeLink::from_json(const json& data) {
        auto result(std::make_shared<StoryAreaTypeLink>());
        result->type_ = data["type_"].get<std::string>();
        result->url = data["url"].get<std::string>();
        return result;
    }
}
