// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "StoryArea.hpp"
#include "StoryAreaPosition.hpp"
#include "StoryAreaType.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json StoryArea::to_json() const {
        json j;
        j["position"] = position->to_json();
        j["type"] = type_->to_json();
        return j.dump();
    }
    std::shared_ptr<StoryArea> StoryArea::from_json(const json& data) {
        auto result(std::make_shared<StoryArea>());
        result->position = StoryAreaPosition::from_json(data["position"]);
        result->type_ = StoryAreaType::from_json(data["type_"]);
        return result;
    }
}
