// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "StoryAreaTypeWeather.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json StoryAreaTypeWeather::to_json() const {
        json j;
        j["type"] = type_;
        j["temperature"] = temperature;
        j["emoji"] = emoji;
        j["background_color"] = background_color;
        return j.dump();
    }
    std::shared_ptr<StoryAreaTypeWeather> StoryAreaTypeWeather::from_json(const json& data) {
        auto result(std::make_shared<StoryAreaTypeWeather>());
        result->type_ = data["type_"].get<std::string>();
        result->temperature = data["temperature"].get<double>();
        result->emoji = data["emoji"].get<std::string>();
        result->background_color = data["background_color"].get<std::int64_t>();
        return result;
    }
}
