// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct StoryAreaPosition;
    struct StoryAreaType;

    using json = nlohmann::json;

    /**
     * Describes a clickable area on a story media.
     *
     * @param position Position of the area
     * @param type Type of the area
     */
    struct StoryArea : public TelegramModel {
        virtual ~StoryArea() = default;
        // Position of the area
        std::shared_ptr<StoryAreaPosition> position;

        // Type of the area
        std::shared_ptr<StoryAreaType> type_;
    };
}
