// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuccessfulPayment.hpp"
#include "OrderInfo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json SuccessfulPayment::to_json() const {
        json j;
        j["currency"] = currency;
        j["total_amount"] = total_amount;
        j["invoice_payload"] = invoice_payload;
        j["subscription_expiration_date"] = subscription_expiration_date;
        j["is_recurring"] = is_recurring;
        j["is_first_recurring"] = is_first_recurring;
        j["shipping_option_id"] = shipping_option_id;
        j["order_info"] = order_info->to_json();
        j["telegram_payment_charge_id"] = telegram_payment_charge_id;
        j["provider_payment_charge_id"] = provider_payment_charge_id;
        return j.dump();
    }
    std::shared_ptr<SuccessfulPayment> SuccessfulPayment::from_json(const json& data) {
        auto result(std::make_shared<SuccessfulPayment>());
        result->currency = data["currency"].get<std::string>();
        result->total_amount = data["total_amount"].get<std::int64_t>();
        result->invoice_payload = data["invoice_payload"].get<std::string>();
        result->subscription_expiration_date = data["subscription_expiration_date"].get<std::int64_t>();
        result->is_recurring = data["is_recurring"].get<bool>();
        result->is_first_recurring = data["is_first_recurring"].get<bool>();
        result->shipping_option_id = data["shipping_option_id"].get<std::string>();
        result->order_info = OrderInfo::from_json(data["order_info"]);
        result->telegram_payment_charge_id = data["telegram_payment_charge_id"].get<std::string>();
        result->provider_payment_charge_id = data["provider_payment_charge_id"].get<std::string>();
        return result;
    }
}
