// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuccessfulPayment.hpp"
#include "OrderInfo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SuccessfulPayment& value) {
        j = json::object();
        j["currency"] = value.currency;
        j["total_amount"] = value.total_amount;
        j["invoice_payload"] = value.invoice_payload;
        j["subscription_expiration_date"] = value.subscription_expiration_date;
        j["is_recurring"] = value.is_recurring;
        j["is_first_recurring"] = value.is_first_recurring;
        j["shipping_option_id"] = value.shipping_option_id;
        j["order_info"] = value.order_info;
        j["telegram_payment_charge_id"] = value.telegram_payment_charge_id;
        j["provider_payment_charge_id"] = value.provider_payment_charge_id;
    }

    void from_json(const json& j, SuccessfulPayment& value) {
        if (j.contains("currency")) {
            j.at("currency").get_to(value.currency);
        }
        if (j.contains("total_amount")) {
            j.at("total_amount").get_to(value.total_amount);
        }
        if (j.contains("invoice_payload")) {
            j.at("invoice_payload").get_to(value.invoice_payload);
        }
        if (j.contains("subscription_expiration_date")) {
            j.at("subscription_expiration_date").get_to(value.subscription_expiration_date);
        }
        if (j.contains("is_recurring")) {
            j.at("is_recurring").get_to(value.is_recurring);
        }
        if (j.contains("is_first_recurring")) {
            j.at("is_first_recurring").get_to(value.is_first_recurring);
        }
        if (j.contains("shipping_option_id")) {
            j.at("shipping_option_id").get_to(value.shipping_option_id);
        }
        if (j.contains("order_info")) {
            j.at("order_info").get_to(value.order_info);
        }
        if (j.contains("telegram_payment_charge_id")) {
            j.at("telegram_payment_charge_id").get_to(value.telegram_payment_charge_id);
        }
        if (j.contains("provider_payment_charge_id")) {
            j.at("provider_payment_charge_id").get_to(value.provider_payment_charge_id);
        }
    }
}
