// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuggestedPostRefunded.hpp"
#include "Message.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json SuggestedPostRefunded::to_json() const {
        json j;
        j["suggested_post_message"] = suggested_post_message->to_json();
        j["reason"] = reason;
        return j.dump();
    }
    std::shared_ptr<SuggestedPostRefunded> SuggestedPostRefunded::from_json(const json& data) {
        auto result(std::make_shared<SuggestedPostRefunded>());
        result->suggested_post_message = Message::from_json(data["suggested_post_message"]);
        result->reason = data["reason"].get<std::string>();
        return result;
    }
}
