// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    struct Message;
    struct SuggestedPostPrice;

    using json = nlohmann::json;

    /**
     * Describes a service message about the approval of a suggested post.
     *
     * @param suggested_post_message Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     * @param price Optional. Amount paid for the post
     * @param send_date Date when the post will be published
     */
    struct SuggestedPostApproved : public TelegramModel {
        virtual ~SuggestedPostApproved() = default;
        // Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        std::shared_ptr<Message> suggested_post_message;

        // Optional. Amount paid for the post
        std::shared_ptr<SuggestedPostPrice> price;

        // Date when the post will be published
        std::int64_t send_date;

        json to_json() const override;
        static std::shared_ptr<SuggestedPostApproved> from_json(const json& data);
    };
}
