// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuggestedPostPaid.hpp"
#include "Message.hpp"
#include "StarAmount.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json SuggestedPostPaid::to_json() const {
        json j;
        j["suggested_post_message"] = suggested_post_message->to_json();
        j["currency"] = currency;
        j["amount"] = amount;
        j["star_amount"] = star_amount->to_json();
        return j.dump();
    }
    std::shared_ptr<SuggestedPostPaid> SuggestedPostPaid::from_json(const json& data) {
        auto result(std::make_shared<SuggestedPostPaid>());
        result->suggested_post_message = std::shared_ptr<Message>::from_json(data["suggested_post_message"]);
        result->currency = data["currency"].get<std::string>();
        result->amount = data["amount"].get<std::int64_t>();
        result->star_amount = std::shared_ptr<StarAmount>::from_json(data["star_amount"]);
        return result;
    }
}
