// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuggestedPostPrice.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json SuggestedPostPrice::to_json() const {
        json j;
        j["currency"] = currency;
        j["amount"] = amount;
        return j.dump();
    }
    std::shared_ptr<SuggestedPostPrice> SuggestedPostPrice::from_json(const json& data) {
        auto result(std::make_shared<SuggestedPostPrice>());
        result->currency = data["currency"].get<std::string>();
        result->amount = data["amount"].get<std::int64_t>();
        return result;
    }
}
