// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "SuggestedPostParameters.hpp"
#include "SuggestedPostPrice.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json SuggestedPostParameters::to_json() const {
        json j;
        j["price"] = price->to_json();
        j["send_date"] = send_date;
        return j.dump();
    }
    std::shared_ptr<SuggestedPostParameters> SuggestedPostParameters::from_json(const json& data) {
        auto result(std::make_shared<SuggestedPostParameters>());
        result->price = SuggestedPostPrice::from_json(data["price"]);
        result->send_date = data["send_date"].get<std::int64_t>();
        return result;
    }
}
