// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "MessageEntity.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object contains information about the quoted part of a message that is replied to by the given message.
     *
     * @param text Text of the quoted part of a message that is replied to by the given message
     * @param entities Optional. Special entities that appear in the quote. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are kept in quotes.
     * @param position Approximate quote position in the original message in UTF-16 code units as specified by the sender
     * @param is_manual Optional. True, if the quote was chosen manually by the message sender. Otherwise, the quote was added automatically by the server.
     */
    struct TextQuote : public TelegramModel {
        virtual ~TextQuote() = default;
        // Text of the quoted part of a message that is replied to by the given message
        std::string text;

        // Optional. Special entities that appear in the quote. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are kept in quotes.
        std::vector<std::shared_ptr<MessageEntity>> entities;

        // Approximate quote position in the original message in UTF-16 code units as specified by the sender
        std::int64_t position;

        // Optional. True, if the quote was chosen manually by the message sender. Otherwise, the quote was added automatically by the server.
        bool is_manual;

        json to_json() const override;
        static std::shared_ptr<TextQuote> from_json(const json& data);
    };
}
