// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "TransactionPartnerUser.hpp"
#include "User.hpp"
#include "AffiliateInfo.hpp"
#include "Gift.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const TransactionPartnerUser& value) {
        j = json::object();
        j["type"] = value.type_;
        j["transaction_type"] = value.transaction_type;
        j["user"] = value.user;
        j["affiliate"] = value.affiliate;
        j["invoice_payload"] = value.invoice_payload;
        j["subscription_period"] = value.subscription_period;
        j["paid_media"] = value.paid_media;
        j["paid_media_payload"] = value.paid_media_payload;
        j["gift"] = value.gift;
        j["premium_subscription_duration"] = value.premium_subscription_duration;
    }

    void from_json(const json& j, TransactionPartnerUser& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("transaction_type")) {
            j.at("transaction_type").get_to(value.transaction_type);
        }
        if (j.contains("user")) {
            j.at("user").get_to(value.user);
        }
        if (j.contains("affiliate")) {
            j.at("affiliate").get_to(value.affiliate);
        }
        if (j.contains("invoice_payload")) {
            j.at("invoice_payload").get_to(value.invoice_payload);
        }
        if (j.contains("subscription_period")) {
            j.at("subscription_period").get_to(value.subscription_period);
        }
        if (j.contains("paid_media")) {
            j.at("paid_media").get_to(value.paid_media);
        }
        if (j.contains("paid_media_payload")) {
            j.at("paid_media_payload").get_to(value.paid_media_payload);
        }
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("premium_subscription_duration")) {
            j.at("premium_subscription_duration").get_to(value.premium_subscription_duration);
        }
    }
}
