// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TransactionPartner.hpp"

namespace tgbot {

    struct User;

    using json = nlohmann::json;

    /**
     * Describes the affiliate program that issued the affiliate commission received via this transaction.
     *
     * @param type Type of the transaction partner, always “affiliate_program”
     * @param sponsor_user Optional. Information about the bot that sponsored the affiliate program
     * @param commission_per_mille The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the affiliate program sponsor from referred users
     */
    struct TransactionPartnerAffiliateProgram : public TransactionPartner {
        virtual ~TransactionPartnerAffiliateProgram() = default;
        // Type of the transaction partner, always “affiliate_program”
        std::string type_;

        // Optional. Information about the bot that sponsored the affiliate program
        std::shared_ptr<User> sponsor_user;

        // The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the affiliate program sponsor from referred users
        std::int64_t commission_per_mille;
    };
}
