// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TransactionPartner.hpp"

namespace tgbot {

    struct RevenueWithdrawalState;

    using json = nlohmann::json;

    /**
     * Describes a withdrawal transaction with Fragment.
     *
     * @param type Type of the transaction partner, always “fragment”
     * @param withdrawal_state Optional. State of the transaction if the transaction is outgoing
     */
    struct TransactionPartnerFragment : public TransactionPartner {
        virtual ~TransactionPartnerFragment() = default;
        // Type of the transaction partner, always “fragment”
        std::string type_;

        // Optional. State of the transaction if the transaction is outgoing
        std::shared_ptr<RevenueWithdrawalState> withdrawal_state;

        json to_json() const override;
        static std::shared_ptr<TransactionPartnerFragment> from_json(const json& data);
    };
}
