// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "TransactionPartnerFragment.hpp"
#include "RevenueWithdrawalState.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json TransactionPartnerFragment::to_json() const {
        json j;
        j["type"] = type_;
        j["withdrawal_state"] = withdrawal_state->to_json();
        return j.dump();
    }
    std::shared_ptr<TransactionPartnerFragment> TransactionPartnerFragment::from_json(const json& data) {
        auto result(std::make_shared<TransactionPartnerFragment>());
        result->type_ = data["type_"].get<std::string>();
        result->withdrawal_state = std::shared_ptr<RevenueWithdrawalState>::from_json(data["withdrawal_state"]);
        return result;
    }
}
