// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Use this method to upload a file with a sticker for later use in the createNewStickerSet, addStickerToSet, or replaceStickerInSet methods (the file can be used multiple times). Returns the uploaded File on success.
     *
     * @param user_id User identifier of sticker file owner
     * @param sticker A file with the sticker in .WEBP, .PNG, .TGS, or .WEBM format. See https://core.telegram.org/stickers for technical requirements. More information on Sending Files »
     * @param sticker_format Format of the sticker, must be one of “static”, “animated”, “video”
     */
    struct UploadStickerFileRequest {
        // User identifier of sticker file owner
        UserId user_id;

        // A file with the sticker in .WEBP, .PNG, .TGS, or .WEBM format. See https://core.telegram.org/stickers for technical requirements. More information on Sending Files »
        std::shared_ptr<InputFile> sticker;

        // Format of the sticker, must be one of “static”, “animated”, “video”
        std::string sticker_format;
    };
}
