// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "PhotoSize.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represent a user's profile pictures.
     *
     * @param total_count Total number of profile pictures the target user has
     * @param photos Requested profile pictures (in up to 4 sizes each)
     */
    struct UserProfilePhotos : public TelegramModel {
        virtual ~UserProfilePhotos() = default;
        // Total number of profile pictures the target user has
        std::int64_t total_count;

        // Requested profile pictures (in up to 4 sizes each)
        std::vector<std::vector<std::shared_ptr<PhotoSize>>> photos;

        json to_json() const override;
        static std::shared_ptr<UserProfilePhotos> from_json(const json& data);
    };
}
