// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "UserProfilePhotos.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json UserProfilePhotos::to_json() const {
        json j;
        j["total_count"] = total_count;
        std::vector<json> photos_values;
        photos_values.reserve(photos.size());
        for (auto& e : photos) {
            photos_values.push_back(e->to_json());
        }
        j["photos"] = photos_values;
        return j.dump();
    }
    std::shared_ptr<UserProfilePhotos> UserProfilePhotos::from_json(const json& data) {
        auto result(std::make_shared<UserProfilePhotos>());
        result->total_count = data["total_count"].get<std::int64_t>();
        std::vector<std::vector<std::vector<std::shared_ptr<PhotoSize>>>> photos_values;
        photos_values.reserve(photos.size());
        for (auto& e : data["photos"]) {
            photos_values.push_back(std::vector<std::vector<std::shared_ptr<PhotoSize>>>::from_json(e));
        }
        result->photos = photos_values;
        return result;
    }
}
