// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Verifies a user on behalf of the organization which is represented by the bot. Returns True on success.
     *
     * @param user_id Unique identifier of the target user
     * @param custom_description Custom description for the verification; 0-70 characters. Must be empty if the organization isn't allowed to provide a custom verification description.
     */
    struct VerifyUserRequest {
        // Unique identifier of the target user
        UserId user_id;

        // Custom description for the verification; 0-70 characters. Must be empty if the organization isn't allowed to provide a custom verification description.
        std::string custom_description;
    };
}
