// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "User.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about new members invited to a video chat.
     *
     * @param users New members that were invited to the video chat
     */
    struct VideoChatParticipantsInvited : public TelegramModel {
        virtual ~VideoChatParticipantsInvited() = default;
        // New members that were invited to the video chat
        std::vector<std::shared_ptr<User>> users;

        json to_json() const override;
        static std::shared_ptr<VideoChatParticipantsInvited> from_json(const json& data);
    };
}
