// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "TelegramModel.hpp"
#include "PhotoSize.hpp"

namespace tgbot {

    struct PhotoSize;

    using json = nlohmann::json;

    /**
     * This object represents a video file.
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param width Video width as defined by the sender
     * @param height Video height as defined by the sender
     * @param duration Duration of the video in seconds as defined by the sender
     * @param thumbnail Optional. Video thumbnail
     * @param cover Optional. Available sizes of the cover of the video in the message
     * @param start_timestamp Optional. Timestamp in seconds from which the video will play in the message
     * @param file_name Optional. Original filename as defined by the sender
     * @param mime_type Optional. MIME type of the file as defined by the sender
     * @param file_size Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
     */
    struct Video : public TelegramModel {
        virtual ~Video() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id;

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id;

        // Video width as defined by the sender
        std::int64_t width;

        // Video height as defined by the sender
        std::int64_t height;

        // Duration of the video in seconds as defined by the sender
        std::int64_t duration;

        // Optional. Video thumbnail
        std::shared_ptr<PhotoSize> thumbnail;

        // Optional. Available sizes of the cover of the video in the message
        std::vector<std::shared_ptr<PhotoSize>> cover;

        // Optional. Timestamp in seconds from which the video will play in the message
        std::int64_t start_timestamp;

        // Optional. Original filename as defined by the sender
        std::string file_name;

        // Optional. MIME type of the file as defined by the sender
        std::string mime_type;

        // Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
        std::int64_t file_size;
    };
}
