// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "VideoNote.hpp"
#include "PhotoSize.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json VideoNote::to_json() const {
        json j;
        j["file_id"] = file_id;
        j["file_unique_id"] = file_unique_id;
        j["length"] = length;
        j["duration"] = duration;
        j["thumbnail"] = thumbnail->to_json();
        j["file_size"] = file_size;
        return j.dump();
    }
    std::shared_ptr<VideoNote> VideoNote::from_json(const json& data) {
        auto result(std::make_shared<VideoNote>());
        result->file_id = data["file_id"].get<std::string>();
        result->file_unique_id = data["file_unique_id"].get<std::string>();
        result->length = data["length"].get<std::int64_t>();
        result->duration = data["duration"].get<std::int64_t>();
        result->thumbnail = std::shared_ptr<PhotoSize>::from_json(data["thumbnail"]);
        result->file_size = data["file_size"].get<std::int64_t>();
        return result;
    }
}
