// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "WebAppData.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json WebAppData::to_json() const {
        json j;
        j["data"] = data;
        j["button_text"] = button_text;
        return j.dump();
    }
    std::shared_ptr<WebAppData> WebAppData::from_json(const json& data) {
        auto result(std::make_shared<WebAppData>());
        result->data = data["data"].get<std::string>();
        result->button_text = data["button_text"].get<std::string>();
        return result;
    }
}
