// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "WebAppInfo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json WebAppInfo::to_json() const {
        json j;
        j["url"] = url;
        return j.dump();
    }
    std::shared_ptr<WebAppInfo> WebAppInfo::from_json(const json& data) {
        auto result(std::make_shared<WebAppInfo>());
        result->url = data["url"].get<std::string>();
        return result;
    }
}
