// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "WebhookInfo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    json WebhookInfo::to_json() const {
        json j;
        j["url"] = url;
        j["has_custom_certificate"] = has_custom_certificate;
        j["pending_update_count"] = pending_update_count;
        j["ip_address"] = ip_address;
        j["last_error_date"] = last_error_date;
        j["last_error_message"] = last_error_message;
        j["last_synchronization_error_date"] = last_synchronization_error_date;
        j["max_connections"] = max_connections;
        std::vector<json> allowed_updates_values;
        allowed_updates_values.reserve(allowed_updates.size());
        for (auto& e : allowed_updates) {
            allowed_updates_values.push_back(e);
        }
        j["allowed_updates"] = allowed_updates_values;
        return j.dump();
    }
    std::shared_ptr<WebhookInfo> WebhookInfo::from_json(const json& data) {
        auto result(std::make_shared<WebhookInfo>());
        result->url = data["url"].get<std::string>();
        result->has_custom_certificate = data["has_custom_certificate"].get<bool>();
        result->pending_update_count = data["pending_update_count"].get<std::int64_t>();
        result->ip_address = data["ip_address"].get<std::string>();
        result->last_error_date = data["last_error_date"].get<std::int64_t>();
        result->last_error_message = data["last_error_message"].get<std::string>();
        result->last_synchronization_error_date = data["last_synchronization_error_date"].get<std::int64_t>();
        result->max_connections = data["max_connections"].get<std::int64_t>();
        std::vector<std::vector<std::string>> allowed_updates_values;
        allowed_updates_values.reserve(allowed_updates.size());
        for (auto& e : data["allowed_updates"]) {
            allowed_updates_values.push_back(std::vector<std::string>::from_json(e));
        }
        result->allowed_updates = allowed_updates_values;
        return result;
    }
}
