import java.io.File

val BASIC_JSON_TYPES_IN_CPP: Set<String> = setOf(
    "std::int64_t",
    "bool",
    "std::string",
    "double",
    "long long"
)

val BASIC_TG_TYPES: Set<String> = setOf(
    "UserId",
    "ChatId",
    "MessageId",
    "BusinessConnectionId",
    "MessageThreadId",
    "MessageEffectId"
)

private val CPP_BASE_INCLUDES = listOf(
    "#include <cstdint>",
    "#include <optional>",
    "#include <string>",
    "#include <vector>",
    "#include <memory>",
    "#include <nlohmann/json.hpp>",
    "#include <stdexcept>"
)

private data class CppModelFile(
    val name: String,
    val headerContent: String,
    val sourceContent: String? = null
)

private fun buildCppHeader(
    forwardDeclarations: Collection<String>,
    includes: Collection<String>,
    body: String
): String = buildString {
    appendLine("// Auto-generated Telegram Bot API models for C++")
    appendLine("// Generated by telegram-api-generator. Do not edit manually.\n")
    appendLine("#pragma once")
    includes.distinct().forEach { appendLine(it) }
    appendLine()
    appendLine("namespace tgbot {")
    if (forwardDeclarations.isNotEmpty()) {
        appendLine()
        forwardDeclarations.distinct().forEach { appendLine("    $it") }
    }
    appendLine()
    if (includes.any { it.contains("nlohmann/json.hpp") }) {
        appendLine("    using json = nlohmann::json;")
        appendLine()
    }
    appendLine(withIndent(body.trimEnd(), "    "))
    appendLine("}")
}

private fun buildCppSource(
    headerName: String,
    includes: Collection<String>,
    body: String
): String = buildString {
    appendLine("// Auto-generated Telegram Bot API models for C++")
    appendLine("// Generated by telegram-api-generator. Do not edit manually.\n")
    appendLine("#include \"$headerName.hpp\"")
    includes.distinct().forEach { appendLine(it) }
    appendLine()
    appendLine("namespace tgbot {")
    appendLine(withIndent(body.trimEnd(), "    "))
    appendLine("}")
}

private fun stripCppWrappers(type: String): String {
    var result = type.trim()
    var changed: Boolean
    do {
        changed = false
        listOf("std::vector<", "std::shared_ptr<", "std::optional<").forEach { prefix ->
            if (result.startsWith(prefix) && result.endsWith(">")) {
                result = result.removePrefix(prefix).removeSuffix(">")
                changed = true
            }
        }
    } while (changed)
    return result
}

private fun extractCustomTypes(
    cppType: String,
    customTypeNames: Set<String>,
    currentName: String? = null
): Set<String> {
    val baseType = stripCppWrappers(cppType)
    return buildSet {
        if (baseType in customTypeNames && baseType != currentName) {
            add(baseType)
        }
    }
}

private fun collectCustomTypes(
    fields: List<DocField>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = fields.flatMap { field ->
    extractCustomTypes(field.toCppFieldType(className), customTypeNames, className)
}.toSet()

private fun collectPointerTypes(
    fields: List<DocField>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = fields.mapNotNull { field ->
    val fieldType = field.toCppFieldType(className)
    if (fieldType.startsWith("std::shared_ptr<")) {
        val baseType = stripCppWrappers(fieldType)
        if (baseType in customTypeNames && baseType != className) {
            baseType
        } else null
    } else null
}.toSet()

private fun collectValueTypes(
    fields: List<DocField>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = fields.mapNotNull { field ->
    val fieldType = field.toCppFieldType(className)
    if (!fieldType.startsWith("std::shared_ptr<") && 
        !fieldType.startsWith("std::vector<") &&
        !BASIC_JSON_TYPES_IN_CPP.contains(fieldType) &&
        !BASIC_TG_TYPES.contains(fieldType)) {
        val baseType = stripCppWrappers(fieldType)
        if (baseType in customTypeNames && baseType != className) {
            baseType
        } else null
    } else null
}.toSet()

private fun collectVectorElementTypes(
    fields: List<DocField>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = fields.mapNotNull { field ->
    val fieldType = field.toCppFieldType(className)
    if (fieldType.startsWith("std::vector<")) {
        val elementType = stripCppWrappers(fieldType)
        if (elementType in customTypeNames && elementType != className) {
            elementType
        } else null
    } else null
}.toSet()

private fun collectCustomTypesFromParameters(
    parameters: List<DocParameter>,
    customTypeNames: Set<String>
): Set<String> = parameters.flatMap { parameter ->
    extractCustomTypes(parameter.toCppFieldType(null), customTypeNames)
}.toSet()

private fun collectPointerTypesFromParameters(
    parameters: List<DocParameter>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = parameters.mapNotNull { param ->
    val fieldType = param.toCppFieldType(null)
    if (fieldType.startsWith("std::shared_ptr<")) {
        val baseType = stripCppWrappers(fieldType)
        if (baseType in customTypeNames && baseType != className) {
            baseType
        } else null
    } else null
}.toSet()

private fun collectValueTypesFromParameters(
    parameters: List<DocParameter>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = parameters.mapNotNull { param ->
    val fieldType = param.toCppFieldType(null)
    if (!fieldType.startsWith("std::shared_ptr<") && 
        !fieldType.startsWith("std::vector<") &&
        !BASIC_JSON_TYPES_IN_CPP.contains(fieldType) &&
        !BASIC_TG_TYPES.contains(fieldType)) {
        val baseType = stripCppWrappers(fieldType)
        if (baseType in customTypeNames && baseType != className) {
            baseType
        } else null
    } else null
}.toSet()

private fun collectVectorElementTypesFromParameters(
    parameters: List<DocParameter>,
    className: String?,
    customTypeNames: Set<String>
): Set<String> = parameters.mapNotNull { param ->
    val fieldType = param.toCppFieldType(null)
    if (fieldType.startsWith("std::vector<")) {
        val elementType = stripCppWrappers(fieldType)
        if (elementType in customTypeNames && elementType != className) {
            elementType
        } else null
    } else null
}.toSet()

private fun generateTelegramModelFile(): CppModelFile {
    val valueClasses = listOf(
        """
struct ChatId {
    std::string stringValue;
    std::int64_t longValue() const { return std::stoll(stringValue); }
};
""".trimIndent(),
        """
struct UserId {
    std::int64_t longValue;
    ChatId toChatId() const { return ChatId{std::to_string(longValue)}; }
};
""".trimIndent(),
        """
struct MessageId {
    std::int64_t longValue;
};
""".trimIndent(),
        """
struct BusinessConnectionId {
    std::string stringValue;
};
""".trimIndent(),
        """
struct MessageThreadId {
    std::int64_t longValue;
};
""".trimIndent(),
        """
struct MessageEffectId {
    std::string stringValue;
};
""".trimIndent(),
        """
struct ParseMode {
    std::string stringValue;
};
""".trimIndent()
    )

    val body = buildString {
        appendLine(
            """
struct TelegramModel {
    virtual ~TelegramModel() = default;
};
""".trimIndent()
        )
        appendLine()
        valueClasses.forEachIndexed { index, valueClass ->
            appendLine(valueClass)
            if (index != valueClasses.lastIndex) {
                appendLine()
            }
        }

        // Free json serializers for value wrapper types (nlohmann::json ADL-based API)
        appendLine()
        appendLine("// JSON serialization for value wrapper types")
        appendLine("void to_json(json& j, const ChatId& value) { j = value.stringValue; }")
        appendLine("void from_json(const json& j, ChatId& value) { j.get_to(value.stringValue); }")
        appendLine()
        appendLine("void to_json(json& j, const UserId& value) { j = value.longValue; }")
        appendLine("void from_json(const json& j, UserId& value) { j.get_to(value.longValue); }")
        appendLine()
        appendLine("void to_json(json& j, const MessageId& value) { j = value.longValue; }")
        appendLine("void from_json(const json& j, MessageId& value) { j.get_to(value.longValue); }")
        appendLine()
        appendLine("void to_json(json& j, const BusinessConnectionId& value) { j = value.stringValue; }")
        appendLine("void from_json(const json& j, BusinessConnectionId& value) { j.get_to(value.stringValue); }")
        appendLine()
        appendLine("void to_json(json& j, const MessageThreadId& value) { j = value.longValue; }")
        appendLine("void from_json(const json& j, MessageThreadId& value) { j.get_to(value.longValue); }")
        appendLine()
        appendLine("void to_json(json& j, const MessageEffectId& value) { j = value.stringValue; }")
        appendLine("void from_json(const json& j, MessageEffectId& value) { j.get_to(value.stringValue); }")
        appendLine()
        appendLine("void to_json(json& j, const ParseMode& value) { j = value.stringValue; }")
        appendLine("void from_json(const json& j, ParseMode& value) { j.get_to(value.stringValue); }")
        appendLine()

        // Generic JSON serialization for std::shared_ptr<T> so model fields can use pointers
        appendLine("template <typename T>")
        appendLine("void to_json(json& j, const std::shared_ptr<T>& value) {")
        appendLine("    if (!value) {")
        appendLine("        j = nullptr;")
        appendLine("    } else {")
        appendLine("        j = *value;")
        appendLine("    }")
        appendLine("}")
        appendLine()
        appendLine("template <typename T>")
        appendLine("void from_json(const json& j, std::shared_ptr<T>& value) {")
        appendLine("    if (j.is_null()) {")
        appendLine("        value.reset();")
        appendLine("    } else {")
        appendLine("        value = std::make_shared<T>(j.get<T>());")
        appendLine("    }")
        appendLine("}")
    }.trimEnd()

    val headerContent = buildCppHeader(
        forwardDeclarations = emptyList(),
        includes = CPP_BASE_INCLUDES,
        body = body
    )
    return CppModelFile(name = "TelegramModel", headerContent = headerContent, sourceContent = null)
}

private fun TelegramType.superTypeNameOrBase(): String =
    when (val parent = superType) {
        null -> "TelegramModel"
        else -> parent.name
    }

private fun generateSuperTypeFiles(
    customTypeNames: Set<String>,
    allTypes: List<TelegramType>
): List<CppModelFile> {
    return TelegramType.allSuper.map { superType ->
        val parentName = superType.superTypeNameOrBase()
        val subtypes = allTypes.filter { it.superType?.name == superType.name }

        // Header: forward declare subtypes, include only base class
        val forwardDeclarations = subtypes.map { "struct ${it.name};" }
        val headerIncludes = CPP_BASE_INCLUDES + listOf("#include \"$parentName.hpp\"")

        val headerBody = buildString {
            appendLine("struct ${superType.name} : public $parentName {")
            appendLine("    virtual ~${superType.name}() = default;")
            appendLine("};")
        }

        CppModelFile(
            name = superType.name,
            headerContent = buildCppHeader(
                forwardDeclarations = forwardDeclarations,
                includes = headerIncludes,
                body = headerBody
            ),
            sourceContent = null
        )
    }
}

private fun DocType.toCppFile(
    customTypeNames: Set<String>,
    valueClassNames: Set<String>
): CppModelFile {
    val superType = TelegramType.from(name).superType
    val superTypeName = superType?.name ?: "TelegramModel"
    
    // Header: forward declare pointer types, include base class and value types
    val pointerTypes = collectPointerTypes(docFields, name, customTypeNames)
    val valueTypes = collectValueTypes(docFields, name, customTypeNames)
    val vectorElementTypes = collectVectorElementTypes(docFields, name, customTypeNames)
    
    val forwardDeclarations = pointerTypes.map { "struct $it;" }
    val includeTelegramModel = superTypeName == "TelegramModel" ||
        valueTypes.any { it in valueClassNames } ||
        vectorElementTypes.any { it in valueClassNames }
    val headerIncludes = buildList {
        addAll(CPP_BASE_INCLUDES)
        add("#include \"$superTypeName.hpp\"")
        if (includeTelegramModel && superTypeName != "TelegramModel") {
            add("#include \"TelegramModel.hpp\"")
        }
        addAll(valueTypes.filterNot { it in valueClassNames }.map { "#include \"$it.hpp\"" })
        addAll(vectorElementTypes.filterNot { it in valueClassNames }.map { "#include \"$it.hpp\"" })
    }

    val headerBody = buildString {
        appendLine(toCppDoc().trimEnd())
        appendLine(toCppStructDeclaration().trimEnd())
    }

    // Source: include all full definitions and implement to_json()
    val sourceIncludes = pointerTypes.map { "#include \"$it.hpp\"" } +
        listOf("#include <nlohmann/json.hpp>")

    val sourceBody = buildString {
        appendLine(toCppStructImplementation())
    }

    return CppModelFile(
        name = name,
        headerContent = buildCppHeader(
            forwardDeclarations = forwardDeclarations,
            includes = headerIncludes,
            body = headerBody
        ),
        sourceContent = buildCppSource(
            headerName = name,
            includes = sourceIncludes,
            body = sourceBody
        )
    )
}

private fun DocMethod.toCppRequestStructDeclaration() = buildString {
    val structName = requestStructName()
    appendLine("struct $structName {")
    if (docParameters.isEmpty()) {
        appendLine("    // Empty struct")
    } else {
        docParameters.forEachIndexed { index, parameter ->
            val fieldName = parameter.cppFieldName()
            val comment = parameter.description.cleanHtml().takeIf { it.isNotBlank() }
            if (comment != null) {
                appendLine("    // ${comment.replace("\n", " ")}")
            }

            val fieldType = parameter.toCppFieldType(null)
            appendLine("    ${fieldType} $fieldName;")

            if (index != docParameters.lastIndex) appendLine()
        }
    }
    append("};")
}

private fun DocMethod.toCppRequestFile(
    customTypeNames: Set<String>,
    valueClassNames: Set<String>
): CppModelFile? {
    if (docParameters.isEmpty()) return null
    val structName = requestStructName()
    
    val pointerTypes = collectPointerTypesFromParameters(docParameters, structName, customTypeNames)
    val valueTypes = collectValueTypesFromParameters(docParameters, structName, customTypeNames)
    val vectorElementTypes = collectVectorElementTypesFromParameters(docParameters, structName, customTypeNames)

    // Check if any parameter uses a value class type (ChatId, UserId, etc.)
    // These are filtered out by collectValueTypesFromParameters, so we need to check directly
    val hasValueClassType = docParameters.any { param ->
        val fieldType = param.toCppFieldType(null)
        val baseType = stripCppWrappers(fieldType)
        baseType in valueClassNames
    }
    
    // Also check vector element types for value classes
    val hasValueClassInVector = vectorElementTypes.any { it in valueClassNames }

    val forwardDeclarations = pointerTypes.map { "struct $it;" }
    val headerIncludes = buildList {
        addAll(CPP_BASE_INCLUDES)
        if (hasValueClassType || hasValueClassInVector || valueTypes.any { it in valueClassNames }) {
            add("#include \"TelegramModel.hpp\"")
        }
        addAll(valueTypes.filterNot { it in valueClassNames }.map { "#include \"$it.hpp\"" })
        addAll(vectorElementTypes.filterNot { it in valueClassNames }.map { "#include \"$it.hpp\"" })
    }

    val headerBody = buildString {
        appendLine(toCppDoc(showReturn = false))
        appendLine(toCppRequestStructDeclaration().trimEnd())
    }

    return CppModelFile(
        name = structName,
        headerContent = buildCppHeader(
            forwardDeclarations = forwardDeclarations,
            includes = headerIncludes,
            body = headerBody
        ),
        sourceContent = null
    )
}

private fun List<DocSection>.toCppModelFiles(): List<CppModelFile> {
    val docTypes = sortedDocTypes()
    val docTypeNames = docTypes.map { it.docType.name }.toSet()

    val requestStructNames = flatMap { section ->
        section.docMethods
            .filter { it.docParameters.isNotEmpty() }
            .map { it.requestStructName() }
    }.toSet()

    val superTypeNames = TelegramType.allSuper.map { it.name }.toSet()
    val valueClassNames = setOf(
        "ChatId",
        "UserId",
        "MessageId",
        "BusinessConnectionId",
        "MessageThreadId",
        "MessageEffectId",
        "ParseMode"
    )

    val customTypeNames = docTypeNames + requestStructNames + superTypeNames + valueClassNames + setOf("TelegramModel")

    val allTypes = flatMap { section ->
        section.docTypes.map { TelegramType.from(it.name) }
    }

    val files = mutableListOf<CppModelFile>()
    files += generateTelegramModelFile()
    files += generateSuperTypeFiles(customTypeNames, allTypes)
    files += docTypes.map { it.docType.toCppFile(customTypeNames, valueClassNames) }
    files += flatMap { section ->
        section.docMethods.mapNotNull { it.toCppRequestFile(customTypeNames, valueClassNames) }
    }

    return files
}

fun List<DocSection>.writeCppModelFiles(outputDir: File) {
    if (outputDir.exists()) {
        outputDir.listFiles { _, name -> name.endsWith(".hpp") || name.endsWith(".cpp") }?.forEach { it.delete() }
    }
    outputDir.mkdirs()
    val files = toCppModelFiles()
    files.forEach { file ->
        File(outputDir, "${file.name}.hpp").writeText(file.headerContent)
        if (file.sourceContent != null) {
            File(outputDir, "${file.name}.cpp").writeText(file.sourceContent)
        }
    }
    // Generate CMakeLists.txt
    File(outputDir, "CMakeLists.txt").writeText(generateCppCMakeLists(files))
}

private fun generateCppCMakeLists(files: List<CppModelFile>): String = buildString {
    appendLine("# Auto-generated CMakeLists.txt for Telegram Bot API C++ models")
    appendLine("# Generated by telegram-api-generator. Do not edit manually.")
    appendLine()
    appendLine("cmake_minimum_required(VERSION 3.15)")
    appendLine()
    appendLine("project(TelegramBotAPI_Models")
    appendLine("    VERSION 1.0.0")
    appendLine("    LANGUAGES CXX")
    appendLine("    DESCRIPTION \"Telegram Bot API C++ models\"")
    appendLine(")")
    appendLine()
    appendLine("set(CMAKE_CXX_STANDARD 17)")
    appendLine("set(CMAKE_CXX_STANDARD_REQUIRED ON)")
    appendLine("set(CMAKE_CXX_EXTENSIONS OFF)")
    appendLine()
    appendLine("# Find or include nlohmann/json")
    appendLine("# Option 1: If nlohmann/json is installed system-wide or via find_package")
    appendLine("if(NOT TARGET nlohmann_json::nlohmann_json)")
    appendLine("    find_package(nlohmann_json QUIET)")
    appendLine("endif()")
    appendLine()
    appendLine("# Option 2: Use FetchContent to download nlohmann/json if not found")
    appendLine("if(NOT TARGET nlohmann_json::nlohmann_json)")
    appendLine("    include(FetchContent)")
    appendLine("    FetchContent_Declare(")
    appendLine("        json")
    appendLine("        GIT_REPOSITORY https://github.com/nlohmann/json.git")
    appendLine("        GIT_TAG v3.11.2")
    appendLine("    )")
    appendLine("    FetchContent_MakeAvailable(json)")
    appendLine("endif()")
    appendLine()
    appendLine("# Collect all source files")
    val headerFiles = files.map { "${it.name}.hpp" }.sorted()
    val sourceFiles = files.filter { it.sourceContent != null }.map { "${it.name}.cpp" }.sorted()
    
    appendLine("set(TELEGRAM_MODELS_HEADERS")
    headerFiles.forEach { appendLine("    $it") }
    appendLine(")")
    appendLine()
    
    if (sourceFiles.isNotEmpty()) {
        appendLine("set(TELEGRAM_MODELS_SOURCES")
        sourceFiles.forEach { appendLine("    $it") }
        appendLine(")")
        appendLine()
    }
    
    appendLine("# Create library target")
    if (sourceFiles.isNotEmpty()) {
        appendLine("add_library(TelegramBotAPI_Models STATIC")
        appendLine("    ${'$'}{TELEGRAM_MODELS_SOURCES}")
        appendLine(")")
        appendLine()
        appendLine("target_include_directories(TelegramBotAPI_Models")
        appendLine("    PUBLIC")
        appendLine("        ${'$'}{CMAKE_CURRENT_SOURCE_DIR}")
        appendLine(")")
        appendLine()
        appendLine("target_link_libraries(TelegramBotAPI_Models")
        appendLine("    PUBLIC")
        appendLine("        nlohmann_json::nlohmann_json")
        appendLine(")")
    } else {
        appendLine("# Header-only library")
        appendLine("add_library(TelegramBotAPI_Models INTERFACE)")
        appendLine()
        appendLine("target_include_directories(TelegramBotAPI_Models")
        appendLine("    INTERFACE")
        appendLine("        ${'$'}{CMAKE_CURRENT_SOURCE_DIR}")
        appendLine(")")
        appendLine()
        appendLine("target_link_libraries(TelegramBotAPI_Models")
        appendLine("    INTERFACE")
        appendLine("        nlohmann_json::nlohmann_json")
        appendLine(")")
    }
    appendLine()
    appendLine("# Install rules (optional)")
    appendLine("install(TARGETS TelegramBotAPI_Models")
    appendLine("    EXPORT TelegramBotAPI_ModelsTargets")
    appendLine("    LIBRARY DESTINATION ${'$'}{CMAKE_INSTALL_LIBDIR}")
    appendLine("    ARCHIVE DESTINATION ${'$'}{CMAKE_INSTALL_LIBDIR}")
    appendLine("    RUNTIME DESTINATION ${'$'}{CMAKE_INSTALL_BINDIR}")
    appendLine("    INCLUDES DESTINATION ${'$'}{CMAKE_INSTALL_INCLUDEDIR}/telegram")
    appendLine(")")
    appendLine()
    appendLine("install(FILES ${'$'}{TELEGRAM_MODELS_HEADERS}")
    appendLine("    DESTINATION ${'$'}{CMAKE_INSTALL_INCLUDEDIR}/telegram")
    appendLine(")")
    appendLine()
    appendLine("install(EXPORT TelegramBotAPI_ModelsTargets")
    appendLine("    FILE TelegramBotAPI_ModelsTargets.cmake")
    appendLine("    NAMESPACE TelegramBotAPI::")
    appendLine("    DESTINATION ${'$'}{CMAKE_INSTALL_LIBDIR}/cmake/TelegramBotAPI_Models")
    appendLine(")")
    appendLine()
    appendLine("# Usage in other projects:")
    appendLine("#   add_subdirectory(path/to/telegram-api-generator/example/cpp)")
    appendLine("#   target_link_libraries(your_target PRIVATE TelegramBotAPI_Models)")
}

private fun List<DocSection>.collectCppClientModelIncludes(): Set<String> {
    val docTypeNames = flatMap { it.docTypes.map { type -> type.name } }.toSet()
    val superTypeNames = TelegramType.allSuper.map { it.name }.toSet()
    val valueClassNames = setOf(
        "ChatId",
        "UserId",
        "MessageId",
        "BusinessConnectionId",
        "MessageThreadId",
        "MessageEffectId",
        "ParseMode"
    )

    val customTypeNames = docTypeNames + superTypeNames + valueClassNames + setOf("TelegramModel")

    val includes = mutableSetOf<String>()

    forEach { section ->
        section.docMethods.forEach { method ->
            includes.addAll(extractCustomTypes(method.returns.toCppType(), customTypeNames))
            method.docParameters.forEach { parameter ->
                includes.addAll(extractCustomTypes(parameter.toCppFieldType(null), customTypeNames))
            }
        }
    }

    return includes
}


private fun comment(text: String, prefix: String = "") = buildString {
    appendLine()
    appendLine("${prefix}// $text")
}

private fun withIndent(text: String, indent: String) =
    text.lines().joinToString("\n") { line ->
        if (line.isEmpty()) ""
        else indent + line
    }

private fun DocType.toCppDoc() = buildString {
    appendLine("/**")
    appendLine(" * ${description.cleanHtml().replace("\n", "\n * ")}")
    appendLine(" *")
    docFields.forEach {
        appendLine(" * @param ${it.name} ${it.description.cleanHtml()}")
    }
    appendLine(" */")
}

private fun DocMethod.toCppDoc(showReturn: Boolean = true) = buildString {
    appendLine("/**")
    appendLine(" * ${description.cleanHtml().replace("\n", "\n * ")}")
    appendLine(" *")
    docParameters.forEach {
        appendLine(" * @param ${it.name} ${it.description.cleanHtml()}")
    }
    if (showReturn) {
        appendLine(" *")
        appendLine(" * @return ${returns.toCppType()}")
    }
    append(" */")
}

private fun generateVectorSerialization(
    fieldType: String,
    fieldName: String,
    jsonFieldName: String
): String = buildString {
    // Extract element type from std::vector<ElementType>
    if (!fieldType.startsWith("std::vector<")) {
        return@buildString
    }

    val elementType = fieldType.removePrefix("std::vector<").removeSuffix(">")

    val jsonPostfix = when {
        BASIC_JSON_TYPES_IN_CPP.contains(elementType) -> ""
        BASIC_TG_TYPES.contains(elementType) -> ".to_json()"
        else -> "->to_json()"
    }

    val tempVarName = "${fieldName}_values"

    appendLine("        std::vector<json> $tempVarName;")
    appendLine("        $tempVarName.reserve($fieldName.size());")
    appendLine("        for (auto& e : $fieldName) {")
    appendLine("            $tempVarName.push_back(e$jsonPostfix);")
    appendLine("        }")
    appendLine("        j[\"$jsonFieldName\"] = $tempVarName;")
}

private fun generateVectorDeserialization(
    fieldType: String,
    fieldName: String,
    jsonFieldName: String
): String = buildString {
    // Extract element type from std::vector<ElementType>
    if (!fieldType.startsWith("std::vector<")) {
        return@buildString
    }

    val elementType = fieldType.removePrefix("std::vector<").removeSuffix(">")

    val jsonPostfix = when {
        BASIC_JSON_TYPES_IN_CPP.contains(elementType) -> ""
        BASIC_TG_TYPES.contains(elementType) -> ".to_json()"
        else -> "->to_json()"
    }

    val tempVarName = "${fieldName}_values"
    appendLine("        std::vector<$fieldType> $tempVarName;")
    appendLine("        $tempVarName.reserve($fieldName.size());")
    appendLine("        for (auto& e : data[\"$fieldName\"]) {")
    if (!BASIC_JSON_TYPES_IN_CPP.contains(fieldName)) {
        appendLine("            $tempVarName.push_back($fieldType::from_json(e));")
    } else {
        appendLine("            $tempVarName.push_back(e.get<$fieldType>());")
    }
    appendLine("        }")
    appendLine("        result->$fieldName = $tempVarName;")
}

private fun DocType.toCppStructDeclaration() = buildString {
    val telegramType = TelegramType.from(name)
    val superType = telegramType.superType
    val superTypeName = when (superType) {
        null -> "TelegramModel"
        else -> superType.name
    }

    appendLine("struct $name : public $superTypeName {")
    appendLine("    virtual ~$name() = default;")
    if (docFields.isEmpty()) {
        appendLine("    // Empty struct")
    } else {
        docFields.forEachIndexed { index, field ->
            val fieldName = field.cppFieldName()
            val comment = field.description.cleanHtml().takeIf { it.isNotBlank() }
            if (comment != null) {
                appendLine("    // ${comment.replace("\n", " ")}")
            }

            val fieldType = field.toCppFieldType(name)
            appendLine("    ${fieldType} $fieldName;")

            if (index != docFields.lastIndex) appendLine()
        }
    }
    append("};")
}


private fun DocType.toCppStructImplementation() = buildString {
    // Free functions for nlohmann::json ADL-based serialization
    appendLine("void to_json(json& j, const $name& value) {")
    if (docFields.isEmpty()) {
        appendLine("    j = json::object();")
    } else {
        appendLine("    j = json::object();")
        docFields.forEach { field ->
            val fieldName = field.cppFieldName()
            val jsonFieldName = field.name
            appendLine("    j[\"$jsonFieldName\"] = value.$fieldName;")
        }
    }
    appendLine("}")
    appendLine()
    appendLine("void from_json(const json& j, $name& value) {")
    if (!docFields.isEmpty()) {
        docFields.forEach { field ->
            val fieldName = field.cppFieldName()
            val jsonFieldName = field.name
            appendLine("    if (j.contains(\"$jsonFieldName\")) {")
            appendLine("        j.at(\"$jsonFieldName\").get_to(value.$fieldName);")
            appendLine("    }")
        }
    }
    appendLine("}")
}


private fun DocField.cppFieldName() = if (name == "type") "type_" else name

private fun DocParameter.cppFieldName() = if (name == "type") "type_" else name

private fun DocField.toCppFieldType(className: String?) =
    type.toCppTypeWithValueClasses(className, name)

private fun DocParameter.toCppFieldType(className: String?) =
    type.toCppTypeWithValueClasses(className, name)

private fun TelegramType.toCppTypeWithValueClasses(
    className: String?,
    propertyName: String?
): String {
    return when (this) {
        is TelegramType.ListType<*> -> "std::vector<${elementType.toCppTypeWithValueClasses(className, propertyName)}>"
        else -> when {
            propertyName == null -> toCppTypeNoValueClasses()
            className == "User" && propertyName == "id" -> "UserId"
            propertyName == "user_id" -> "UserId"
            className == "Chat" && propertyName == "id" -> "ChatId"
            className == "ChatFullInfo" && propertyName == "id" -> "ChatId"
            propertyName == "chat_id" -> "ChatId"
            propertyName.endsWith("_chat_id") -> "ChatId"
            propertyName == "message_id" -> "MessageId"
            propertyName == "message_ids" -> "MessageId"
            className == "BusinessConnection" && propertyName == "id" -> "BusinessConnectionId"
            propertyName == "business_connection_id" -> "BusinessConnectionId"
            propertyName == "message_thread_id" -> "MessageThreadId"
            propertyName == "message_effect_id" -> "MessageEffectId"
            propertyName == "parse_mode" -> "ParseMode"
            else -> toCppTypeNoValueClasses()
        }
    }
}

private fun TelegramType.toCppType(): String = toCppTypeNoValueClasses()

private fun TelegramType.toCppTypeNoValueClasses(): String = when (this) {
    is TelegramType.Declared -> "std::shared_ptr<$name>"
    is TelegramType.ListType<*> -> "std::vector<${elementType.toCppTypeNoValueClasses()}>"

    TelegramType.Integer -> "std::int64_t"
    TelegramType.StringType -> "std::string"
    TelegramType.Boolean -> "bool"
    TelegramType.Float -> "double"

    TelegramType.CallbackGame,
    TelegramType.InputFile,
    TelegramType.ForumTopicClosed,
    TelegramType.ForumTopicReopened,
    TelegramType.GeneralForumTopicHidden,
    TelegramType.GeneralForumTopicUnhidden,
    TelegramType.GiveawayCreated,
    TelegramType.ParseMode,
    TelegramType.VoiceChatStarted,
    TelegramType.VideoChatStarted -> "std::shared_ptr<$name>"

    is TelegramType.Super -> "std::shared_ptr<$name>"

    is TelegramType.WithAlternative -> when (this) {
        TelegramType.WithAlternative.InputFileOrString -> "std::string"
        TelegramType.WithAlternative.IntegerOrString -> "std::string"
    }
}

fun List<DocSection>.toCppClient() = buildString {
    appendLine("// Auto-generated Telegram Bot API client for C++")
    appendLine("// Generated by telegram-api-generator. Do not edit manually.\n")
    appendLine("#pragma once")
    collectCppClientModelIncludes().sorted().forEach { model ->
        appendLine("#include \"cpp/$model.hpp\"")
    }
    appendLine("#include <boost/beast/core.hpp>")
    appendLine("#include <boost/beast/http.hpp>")
    appendLine("#include <boost/beast/ssl.hpp>")
    appendLine("#include <boost/beast/version.hpp>")
    appendLine("#include <boost/asio/connect.hpp>")
    appendLine("#include <boost/asio/ip/tcp.hpp>")
    appendLine("#include <boost/asio/ssl/stream.hpp>")
    appendLine("#include <nlohmann/json.hpp>")
    appendLine("#include <optional>")
    appendLine("#include <iostream>")
    appendLine("#include <string>\n")
    appendLine("namespace telegram {")
    appendLine()
    appendLine("using json = nlohmann::json;")
    appendLine()
    appendLine("template<typename T>")
    appendLine("struct TelegramResponse {")
    appendLine("    bool ok;")
    appendLine("    std::optional<T> result;")
    appendLine("};")
    appendLine()
    appendLine("class TelegramClient {")
    appendLine("private:")
    appendLine("    std::string api_key_;")
    appendLine("    boost::asio::io_context ioc_;")
    appendLine("    boost::asio::ssl::context ctx_{boost::asio::ssl::context::tlsv12_client};")
    appendLine()
    appendLine("    std::string makeRequest(const std::string& method, const std::string& body = \"\") {")
    appendLine("        namespace beast = boost::beast;")
    appendLine("        namespace http = beast::http;")
    appendLine("        namespace net = boost::asio;")
    appendLine("        using tcp = boost::asio::ip::tcp;")
    appendLine()
    appendLine("        try {")
    appendLine("            tcp::resolver resolver{ioc_};")
    appendLine("            beast::ssl_stream<beast::tcp_stream> stream{ioc_, ctx_};")
    appendLine()
    appendLine("            auto const results = resolver.resolve(\"api.telegram.org\", \"443\");")
    appendLine("            beast::get_lowest_layer(stream).connect(results);")
    appendLine("            stream.handshake(boost::asio::ssl::stream_base::client);")
    appendLine()
    appendLine("            std::string target = \"/bot\" + api_key_ + \"/\" + method;")
    appendLine("            http::request<http::string_body> req{http::verb::post, target, 11};")
    appendLine("            req.set(http::field::host, \"api.telegram.org\");")
    appendLine("            req.set(http::field::user_agent, BOOST_BEAST_VERSION_STRING);")
    appendLine("            req.set(http::field::content_type, \"application/json\");")
    appendLine("            req.body() = body.empty() ? \"{}\" : body;")
    appendLine("            req.prepare_payload();")
    appendLine()
    appendLine("            http::write(stream, req);")
    appendLine()
    appendLine("            beast::flat_buffer buffer;")
    appendLine("            http::response<http::dynamic_body> res;")
    appendLine("            http::read(stream, buffer, res);")
    appendLine()
    appendLine("            beast::error_code ec;")
    appendLine("            stream.shutdown(ec);")
    appendLine()
    appendLine("            return beast::buffers_to_string(res.body().data());")
    appendLine("        } catch (std::exception const& e) {")
    appendLine("            throw std::runtime_error(\"Request failed: \" + std::string(e.what()));")
    appendLine("        }")
    appendLine("    }")
    appendLine()
    appendLine("    template<typename T>")
    appendLine("    TelegramResponse<T> parseResponse(const std::string& response_str) {")
    appendLine("        auto j = json::parse(response_str);")
    appendLine("        TelegramResponse<T> result;")
    appendLine("        result.ok = j[\"ok\"].get<bool>();")
    appendLine("        if (result.ok && j.contains(\"result\")) {")
    appendLine("            result.result = j[\"result\"].get<T>();")
    appendLine("        }")
    appendLine("        return result;")
    appendLine("    }")
    appendLine()
    appendLine("public:")
    appendLine("    explicit TelegramClient(const std::string& api_key)")
    appendLine("        : api_key_(api_key) {")
    appendLine("        ctx_.set_default_verify_paths();")
    appendLine("    }")

    this@toCppClient.forEach { section ->
        if (section.docMethods.isNotEmpty()) {
            appendLine(comment(section.name, prefix = "    "))
            section.docMethods.forEach { method ->
                appendLine(withIndent(method.toCppClientMethod(), "    "))
                appendLine()
            }
        }
    }
    appendLine("};")
    appendLine()
    appendLine("} // namespace telegram")
}

private fun DocMethod.toCppClientMethod() = buildString {
    val structName = requestStructName()
    val returnType = returns.toCppType()
    val returnTypeWithVector = when (returns) {
        is TelegramType.ListType<*> -> "std::vector<${returns.elementType.toCppType()}>"
        else -> returnType
    }
    
    appendLine(toCppDoc(showReturn = true))
    if (docParameters.isEmpty()) {
        append("TelegramResponse<$returnTypeWithVector> $name() {")
        appendLine()
        appendLine("    std::string response = makeRequest(\"$name\");")
        appendLine("    return parseResponse<$returnTypeWithVector>(response);")
        append("}")
    } else {
        append("TelegramResponse<$returnTypeWithVector> $name(")
        docParameters.forEachIndexed { index, parameter ->
            val paramType = parameter.toCppFieldType(null)
            val paramName = parameter.cppFieldName()
            if (index == docParameters.lastIndex) {
                appendLine("    $paramType $paramName")
            } else {
                appendLine("    $paramType $paramName,")
            }
        }
        appendLine(") {")
        appendLine("    json j;")
        docParameters.forEach { parameter ->
            val fieldName = parameter.cppFieldName()
            val jsonFieldName = parameter.name
            appendLine("    j[\"$jsonFieldName\"] = $fieldName;")
        }
        appendLine("    std::string body = j.dump();")
        appendLine("    std::string response = makeRequest(\"$name\", body);")
        appendLine("    return parseResponse<$returnTypeWithVector>(response);")
        append("}")
    }
}

private fun DocMethod.requestStructName() =
    name.replaceFirstChar { it.uppercaseChar() } + "Request"


private data class DocTypeWithSection(
    val docType: DocType,
    val sectionName: String?
)

private fun List<DocSection>.sortedDocTypes(): List<DocTypeWithSection> {
    val docTypesWithSection = flatMap { section ->
        section.docTypes.map { docType -> docType to section.name }
    }
    if (docTypesWithSection.isEmpty()) return emptyList()

    val docTypeMap = docTypesWithSection.associate { (docType, _) -> docType.name to docType }
    val sectionByType = docTypesWithSection.associate { (docType, sectionName) -> docType.name to sectionName }
    val dependencies = docTypeMap.mapValues { (_, docType) ->
        docType.dependencies(docTypeMap.keys)
    }

    val visited = mutableSetOf<String>()
    val visiting = mutableSetOf<String>()
    val order = mutableListOf<String>()

    fun dfs(name: String) {
        if (name !in docTypeMap) return
        if (name in visited) return
        if (!visiting.add(name)) return // cycle detected, keep original insertion order later

        dependencies[name]?.forEach { dependency ->
            dfs(dependency)
        }

        visiting.remove(name)
        visited.add(name)
        order.add(name)
    }

    docTypeMap.keys.forEach { dfs(it) }
    val remaining = docTypeMap.keys.filterNot { it in order.toSet() }
    order.addAll(remaining)

    return order.map { name ->
        DocTypeWithSection(
            docType = docTypeMap.getValue(name),
            sectionName = sectionByType[name]
        )
    }
}

private fun DocType.dependencies(docTypeNames: Set<String>): Set<String> =
    docFields.flatMap { field ->
        field.type.collectDocTypeNames(docTypeNames)
    }.toSet()

private fun TelegramType.collectDocTypeNames(docTypeNames: Set<String>): List<String> = when (this) {
    is TelegramType.Declared -> listOfNotNull(name.takeIf { it in docTypeNames })
    is TelegramType.ListType<*> -> elementType.collectDocTypeNames(docTypeNames)
    is TelegramType.Super -> listOfNotNull(name.takeIf { it in docTypeNames })
    is TelegramType.WithAlternative -> emptyList()
    else -> emptyList()
}

private fun String.cleanHtml(): String {
    return this
        .replace(Regex("<[^>]+>"), "") // Remove HTML tags
        .replace("&nbsp;", " ")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .trim()
}


