fun List<DocSection>.toCppModels() = buildString {
    appendLine("// Auto-generated Telegram Bot API models for C++")
    appendLine("// Generated by telegram-api-generator. Do not edit manually.\n")
    appendLine("#pragma once")
    appendLine("#include <cstdint>")
    appendLine("#include <optional>")
    appendLine("#include <string>")
    appendLine("#include <vector>\n")
    appendLine("namespace telegram {")
    appendLine(comment("--- Parameters & Responses ---", prefix = "    "))
    this@toCppModels.forEach { section ->
        if (section.docTypes.isNotEmpty()) {
            appendLine(comment(section.name, prefix = "    "))
            section.docTypes.forEach { type ->
                appendLine(withIndent(type.toCppDoc(), "    "))
                appendLine(withIndent(type.toCppStruct(), "    "))
                appendLine()
            }
        }
    }
    appendLine(comment("--- Requests ---", prefix = "    "))
    this@toCppModels.forEach { section ->
        if (section.docMethods.isNotEmpty()) {
            appendLine(comment(section.name, prefix = "    "))
            section.docMethods.forEach { method ->
                if (method.docParameters.isNotEmpty()) {
                    appendLine(withIndent(method.toCppDoc(showReturn = false), "    "))
                    appendLine(withIndent(method.toCppStruct(), "    "))
                    appendLine()
                }
            }
        }
    }
    appendLine("} // namespace telegram")
}

private fun comment(text: String, prefix: String = "") = buildString {
    appendLine()
    appendLine("${prefix}// $text")
}

private fun withIndent(text: String, indent: String) =
    text.lines().joinToString("\n") { line ->
        if (line.isEmpty()) ""
        else indent + line
    }

private fun DocType.toCppDoc() = buildString {
    appendLine("/**")
    appendLine(" * ${description.cleanHtml().replace("\n", "\n * ")}")
    appendLine(" *")
    docFields.forEach {
        appendLine(" * @param ${it.name} ${it.description.cleanHtml()}")
    }
    appendLine(" */")
}

private fun DocMethod.toCppDoc(showReturn: Boolean = true) = buildString {
    appendLine("/**")
    appendLine(" * ${description.cleanHtml().replace("\n", "\n * ")}")
    appendLine(" *")
    docParameters.forEach {
        appendLine(" * @param ${it.name} ${it.description.cleanHtml()}")
    }
    if (showReturn) {
        appendLine(" *")
        appendLine(" * @return ${returns.toCppType()}")
    }
    append(" */")
}

private fun DocType.toCppStruct() = buildString {
    appendLine("struct $name {")
    if (docFields.isEmpty()) {
        appendLine("    // Empty struct")
    } else {
        docFields.forEachIndexed { index, field ->
            val fieldName = field.cppFieldName()
            val comment = field.description.cleanHtml().takeIf { it.isNotBlank() }
            if (comment != null) {
                appendLine("    // ${comment.replace("\n", " ")}")
            }
            appendLine("    ${field.toCppFieldType()} $fieldName;")
            if (index != docFields.lastIndex) appendLine()
        }
    }
    append("};")
}

private fun DocMethod.toCppStruct() = buildString {
    val structName = name.replaceFirstChar { it.uppercaseChar() } + "Request"
    appendLine("struct $structName {")
    if (docParameters.isEmpty()) {
        appendLine("    // Empty struct")
    } else {
        docParameters.forEachIndexed { index, parameter ->
            val fieldName = parameter.cppFieldName()
            val comment = parameter.description.cleanHtml().takeIf { it.isNotBlank() }
            if (comment != null) {
                appendLine("    // ${comment.replace("\n", " ")}")
            }
            appendLine("    ${parameter.toCppFieldType()} $fieldName;")
            if (index != docParameters.lastIndex) appendLine()
        }
    }
    append("};")
}

private fun DocField.cppFieldName() = if (name == "type") "type_" else name

private fun DocParameter.cppFieldName() = if (name == "type") "type_" else name

private fun DocField.toCppFieldType() =
    if (required) type.toCppType() else "std::optional<${type.toCppType()}>"

private fun DocParameter.toCppFieldType() =
    if (required) type.toCppType() else "std::optional<${type.toCppType()}>"

private fun TelegramType.toCppType(): String = when (this) {
    is TelegramType.Declared -> name
    is TelegramType.ListType<*> -> "std::vector<${elementType.toCppType()}>"

    TelegramType.Integer -> "std::int64_t"
    TelegramType.StringType -> "std::string"
    TelegramType.Boolean -> "bool"
    TelegramType.Float -> "double"

    TelegramType.CallbackGame,
    TelegramType.InputFile,
    TelegramType.ForumTopicClosed,
    TelegramType.ForumTopicReopened,
    TelegramType.GeneralForumTopicHidden,
    TelegramType.GeneralForumTopicUnhidden,
    TelegramType.GiveawayCreated,
    TelegramType.ParseMode,
    TelegramType.VoiceChatStarted,
    TelegramType.VideoChatStarted -> name

    is TelegramType.Super -> name

    is TelegramType.WithAlternative -> when (this) {
        TelegramType.WithAlternative.InputFileOrString -> "std::string"
        TelegramType.WithAlternative.IntegerOrString -> "std::string"
    }
}

fun List<DocSection>.toCppClient() = buildString {
    appendLine("// Auto-generated Telegram Bot API client for C++")
    appendLine("// Generated by telegram-api-generator. Do not edit manually.\n")
    appendLine("#pragma once")
    appendLine("#include \"TelegramModels.hpp\"")
    appendLine("#include <boost/beast/core.hpp>")
    appendLine("#include <boost/beast/http.hpp>")
    appendLine("#include <boost/beast/ssl.hpp>")
    appendLine("#include <boost/beast/version.hpp>")
    appendLine("#include <boost/asio/connect.hpp>")
    appendLine("#include <boost/asio/ip/tcp.hpp>")
    appendLine("#include <boost/asio/ssl/stream.hpp>")
    appendLine("#include <nlohmann/json.hpp>")
    appendLine("#include <iostream>")
    appendLine("#include <string>\n")
    appendLine("namespace telegram {")
    appendLine()
    appendLine("using json = nlohmann::json;")
    appendLine()
    appendLine("template<typename T>")
    appendLine("struct TelegramResponse {")
    appendLine("    bool ok;")
    appendLine("    std::optional<T> result;")
    appendLine("};")
    appendLine()
    appendLine("class TelegramClient {")
    appendLine("private:")
    appendLine("    std::string api_key_;")
    appendLine("    boost::asio::io_context ioc_;")
    appendLine("    boost::asio::ssl::context ctx_{boost::asio::ssl::context::tlsv12_client};")
    appendLine()
    appendLine("    std::string makeRequest(const std::string& method, const std::string& body = \"\") {")
    appendLine("        namespace beast = boost::beast;")
    appendLine("        namespace http = beast::http;")
    appendLine("        namespace net = boost::asio;")
    appendLine("        using tcp = boost::asio::ip::tcp;")
    appendLine()
    appendLine("        try {")
    appendLine("            tcp::resolver resolver{ioc_};")
    appendLine("            beast::ssl_stream<beast::tcp_stream> stream{ioc_, ctx_};")
    appendLine()
    appendLine("            auto const results = resolver.resolve(\"api.telegram.org\", \"443\");")
    appendLine("            beast::get_lowest_layer(stream).connect(results);")
    appendLine("            stream.handshake(boost::asio::ssl::stream_base::client);")
    appendLine()
    appendLine("            std::string target = \"/bot\" + api_key_ + \"/\" + method;")
    appendLine("            http::request<http::string_body> req{http::verb::post, target, 11};")
    appendLine("            req.set(http::field::host, \"api.telegram.org\");")
    appendLine("            req.set(http::field::user_agent, BOOST_BEAST_VERSION_STRING);")
    appendLine("            req.set(http::field::content_type, \"application/json\");")
    appendLine("            req.body() = body.empty() ? \"{}\" : body;")
    appendLine("            req.prepare_payload();")
    appendLine()
    appendLine("            http::write(stream, req);")
    appendLine()
    appendLine("            beast::flat_buffer buffer;")
    appendLine("            http::response<http::dynamic_body> res;")
    appendLine("            http::read(stream, buffer, res);")
    appendLine()
    appendLine("            beast::error_code ec;")
    appendLine("            stream.shutdown(ec);")
    appendLine()
    appendLine("            return beast::buffers_to_string(res.body().data());")
    appendLine("        } catch (std::exception const& e) {")
    appendLine("            throw std::runtime_error(\"Request failed: \" + std::string(e.what()));")
    appendLine("        }")
    appendLine("    }")
    appendLine()
    appendLine("    template<typename T>")
    appendLine("    TelegramResponse<T> parseResponse(const std::string& response_str) {")
    appendLine("        auto j = json::parse(response_str);")
    appendLine("        TelegramResponse<T> result;")
    appendLine("        result.ok = j[\"ok\"].get<bool>();")
    appendLine("        if (result.ok && j.contains(\"result\")) {")
    appendLine("            result.result = j[\"result\"].get<T>();")
    appendLine("        }")
    appendLine("        return result;")
    appendLine("    }")
    appendLine()
    appendLine("public:")
    appendLine("    explicit TelegramClient(const std::string& api_key)")
    appendLine("        : api_key_(api_key) {")
    appendLine("        ctx_.set_default_verify_paths();")
    appendLine("    }")

    this@toCppClient.forEach { section ->
        if (section.docMethods.isNotEmpty()) {
            appendLine(comment(section.name, prefix = "    "))
            section.docMethods.forEach { method ->
                appendLine(withIndent(method.toCppClientMethod(), "    "))
                appendLine()
            }
        }
    }
    appendLine("};")
    appendLine()
    appendLine("} // namespace telegram")
}

private fun DocMethod.toCppClientMethod() = buildString {
    val structName = name.replaceFirstChar { it.uppercaseChar() } + "Request"
    val returnType = returns.toCppType()
    val returnTypeWithVector = when (returns) {
        is TelegramType.ListType<*> -> "std::vector<${returns.elementType.toCppType()}>"
        else -> returnType
    }
    
    appendLine(toCppDoc(showReturn = true))
    if (docParameters.isEmpty()) {
        append("TelegramResponse<$returnTypeWithVector> $name() {")
        appendLine()
        appendLine("    std::string response = makeRequest(\"$name\");")
        appendLine("    return parseResponse<$returnTypeWithVector>(response);")
        append("}")
    } else {
        append("TelegramResponse<$returnTypeWithVector> $name(")
        docParameters.forEachIndexed { index, parameter ->
            val paramType = parameter.toCppFieldType()
            val paramName = parameter.cppFieldName()
            if (index == docParameters.lastIndex) {
                appendLine("    $paramType $paramName")
            } else {
                appendLine("    $paramType $paramName,")
            }
        }
        appendLine(") {")
        appendLine("    json j;")
        docParameters.forEach { parameter ->
            val fieldName = parameter.cppFieldName()
            val jsonFieldName = parameter.name
            if (parameter.required) {
                appendLine("    j[\"$jsonFieldName\"] = $fieldName;")
            } else {
                appendLine("    if ($fieldName.has_value()) {")
                appendLine("        j[\"$jsonFieldName\"] = $fieldName.value();")
                appendLine("    }")
            }
        }
        appendLine("    std::string body = j.dump();")
        appendLine("    std::string response = makeRequest(\"$name\", body);")
        appendLine("    return parseResponse<$returnTypeWithVector>(response);")
        append("}")
    }
}

private fun String.cleanHtml(): String {
    return this
        .replace(Regex("<[^>]+>"), "") // Remove HTML tags
        .replace("&nbsp;", " ")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .trim()
}
