// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/BackgroundFill.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The background is a gradient fill.
     *
     * @param type Type of the background fill, always “gradient”
     * @param top_color Top color of the gradient in the RGB24 format
     * @param bottom_color Bottom color of the gradient in the RGB24 format
     * @param rotation_angle Clockwise rotation angle of the background fill in degrees; 0-359
     */
    struct BackgroundFillGradient : public BackgroundFill {
        typedef std::shared_ptr<BackgroundFillGradient> Ptr;

        virtual ~BackgroundFillGradient() = default;
        // Type of the background fill, always “gradient”
        std::string type_;

        // Top color of the gradient in the RGB24 format
        int64_t top_color;

        // Bottom color of the gradient in the RGB24 format
        int64_t bottom_color;

        // Clockwise rotation angle of the background fill in degrees; 0-359
        int64_t rotation_angle;
    };
    void to_json(json& j, const BackgroundFillGradient& value);
    void from_json(const json& j, BackgroundFillGradient& value);
}
