// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes the birthdate of a user.
     *
     * @param day Day of the user's birth; 1-31
     * @param month Month of the user's birth; 1-12
     * @param year Optional. Year of the user's birth
     */
    struct Birthdate : public TelegramModel {
        typedef std::shared_ptr<Birthdate> Ptr;

        virtual ~Birthdate() = default;
        // Day of the user's birth; 1-31
        int64_t day;

        // Month of the user's birth; 1-12
        int64_t month;

        // Optional. Year of the user's birth
        int64_t year;
    };
    void to_json(json& j, const Birthdate& value);
    void from_json(const json& j, Birthdate& value);
}
