// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/BotCommandScope.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents the scope of bot commands, covering all group and supergroup chat administrators.
     *
     * @param type Scope type, must be all_chat_administrators
     */
    struct BotCommandScopeAllChatAdministrators : public BotCommandScope {
        typedef std::shared_ptr<BotCommandScopeAllChatAdministrators> Ptr;

        virtual ~BotCommandScopeAllChatAdministrators() = default;
        // Scope type, must be all_chat_administrators
        std::string type_;
    };
    void to_json(json& j, const BotCommandScopeAllChatAdministrators& value);
    void from_json(const json& j, BotCommandScopeAllChatAdministrators& value);
}
