// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents the bot's name.
     *
     * @param name The bot's name
     */
    struct BotName : public TelegramModel {
        typedef std::shared_ptr<BotName> Ptr;

        virtual ~BotName() = default;
        // The bot's name
        std::string name;
    };
    void to_json(json& j, const BotName& value);
    void from_json(const json& j, BotName& value);
}
