// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace tgbot {

    using json = nlohmann::json;

    struct CallbackGame {
        typedef std::shared_ptr<CallbackGame> Ptr;
    };

    void to_json(json& j, const CallbackGame& value);
    void from_json(const json& j, CallbackGame& value);")
}
