// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object describes the background of a gift.
     *
     * @param center_color Center color of the background in RGB format
     * @param edge_color Edge color of the background in RGB format
     * @param text_color Text color of the background in RGB format
     */
    struct GiftBackground : public TelegramModel {
        typedef std::shared_ptr<GiftBackground> Ptr;

        virtual ~GiftBackground() = default;
        // Center color of the background in RGB format
        int64_t center_color;

        // Edge color of the background in RGB format
        int64_t edge_color;

        // Text color of the background in RGB format
        int64_t text_color;
    };
    void to_json(json& j, const GiftBackground& value);
    void from_json(const json& j, GiftBackground& value);
}
