// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"
#include "types/WebAppInfo.hpp"
#include "types/LoginUrl.hpp"
#include "types/SwitchInlineQueryChosenChat.hpp"
#include "types/CopyTextButton.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents one button of an inline keyboard. Exactly one of the optional fields must be used to specify type of the button.
     *
     * @param text Label text on the button
     * @param url Optional. HTTP or tg:// URL to be opened when the button is pressed. Links tg://user?id=<user_id> can be used to mention a user by their identifier without using a username, if this is allowed by their privacy settings.
     * @param callback_data Optional. Data to be sent in a callback query to the bot when the button is pressed, 1-64 bytes
     * @param web_app Optional. Description of the Web App that will be launched when the user presses the button. The Web App will be able to send an arbitrary message on behalf of the user using the method answerWebAppQuery. Available only in private chats between a user and the bot. Not supported for messages sent on behalf of a Telegram Business account.
     * @param login_url Optional. An HTTPS URL used to automatically authorize the user. Can be used as a replacement for the Telegram Login Widget.
     * @param switch_inline_query Optional. If set, pressing the button will prompt the user to select one of their chats, open that chat and insert the bot's username and the specified inline query in the input field. May be empty, in which case just the bot's username will be inserted. Not supported for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
     * @param switch_inline_query_current_chat Optional. If set, pressing the button will insert the bot's username and the specified inline query in the current chat's input field. May be empty, in which case only the bot's username will be inserted.This offers a quick way for the user to open your bot in inline mode in the same chat - good for selecting something from multiple options. Not supported in channels and for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
     * @param switch_inline_query_chosen_chat Optional. If set, pressing the button will prompt the user to select one of their chats of the specified type, open that chat and insert the bot's username and the specified inline query in the input field. Not supported for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
     * @param copy_text Optional. Description of the button that copies the specified text to the clipboard.
     * @param callback_game Optional. Description of the game that will be launched when the user presses the button.NOTE: This type of button must always be the first button in the first row.
     * @param pay Optional. Specify True, to send a Pay button. Substrings “” and “XTR” in the buttons's text will be replaced with a Telegram Star icon.NOTE: This type of button must always be the first button in the first row and can only be used in invoice messages.
     */
    struct InlineKeyboardButton : public TelegramModel {
        typedef std::shared_ptr<InlineKeyboardButton> Ptr;

        virtual ~InlineKeyboardButton() = default;
        // Label text on the button
        std::string text;

        // Optional. HTTP or tg:// URL to be opened when the button is pressed. Links tg://user?id=<user_id> can be used to mention a user by their identifier without using a username, if this is allowed by their privacy settings.
        std::string url;

        // Optional. Data to be sent in a callback query to the bot when the button is pressed, 1-64 bytes
        std::string callback_data;

        // Optional. Description of the Web App that will be launched when the user presses the button. The Web App will be able to send an arbitrary message on behalf of the user using the method answerWebAppQuery. Available only in private chats between a user and the bot. Not supported for messages sent on behalf of a Telegram Business account.
        WebAppInfo::Ptr web_app;

        // Optional. An HTTPS URL used to automatically authorize the user. Can be used as a replacement for the Telegram Login Widget.
        LoginUrl::Ptr login_url;

        // Optional. If set, pressing the button will prompt the user to select one of their chats, open that chat and insert the bot's username and the specified inline query in the input field. May be empty, in which case just the bot's username will be inserted. Not supported for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
        std::string switch_inline_query;

        // Optional. If set, pressing the button will insert the bot's username and the specified inline query in the current chat's input field. May be empty, in which case only the bot's username will be inserted.This offers a quick way for the user to open your bot in inline mode in the same chat - good for selecting something from multiple options. Not supported in channels and for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
        std::string switch_inline_query_current_chat;

        // Optional. If set, pressing the button will prompt the user to select one of their chats of the specified type, open that chat and insert the bot's username and the specified inline query in the input field. Not supported for messages sent in channel direct messages chats and on behalf of a Telegram Business account.
        SwitchInlineQueryChosenChat::Ptr switch_inline_query_chosen_chat;

        // Optional. Description of the button that copies the specified text to the clipboard.
        CopyTextButton::Ptr copy_text;

        // Optional. Description of the game that will be launched when the user presses the button.NOTE: This type of button must always be the first button in the first row.
        CallbackGame::Ptr callback_game;

        // Optional. Specify True, to send a Pay button. Substrings “” and “XTR” in the buttons's text will be replaced with a Telegram Star icon.NOTE: This type of button must always be the first button in the first row and can only be used in invoice messages.
        bool pay;
    };
    void to_json(json& j, const InlineKeyboardButton& value);
    void from_json(const json& j, InlineKeyboardButton& value);
}
