// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/InlineQueryResult.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Represents a location on a map. By default, the location will be sent by the user. Alternatively, you can use input_message_content to send a message with the specified content instead of the location.
     *
     * @param type Type of the result, must be location
     * @param id Unique identifier for this result, 1-64 Bytes
     * @param latitude Location latitude in degrees
     * @param longitude Location longitude in degrees
     * @param title Location title
     * @param horizontal_accuracy Optional. The radius of uncertainty for the location, measured in meters; 0-1500
     * @param live_period Optional. Period in seconds during which the location can be updated, should be between 60 and 86400, or 0x7FFFFFFF for live locations that can be edited indefinitely.
     * @param heading Optional. For live locations, a direction in which the user is moving, in degrees. Must be between 1 and 360 if specified.
     * @param proximity_alert_radius Optional. For live locations, a maximum distance for proximity alerts about approaching another chat member, in meters. Must be between 1 and 100000 if specified.
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the location
     * @param thumbnail_url Optional. Url of the thumbnail for the result
     * @param thumbnail_width Optional. Thumbnail width
     * @param thumbnail_height Optional. Thumbnail height
     */
    struct InlineQueryResultLocation : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultLocation> Ptr;

        virtual ~InlineQueryResultLocation() = default;
        // Type of the result, must be location
        std::string type_;

        // Unique identifier for this result, 1-64 Bytes
        std::string id;

        // Location latitude in degrees
        double latitude;

        // Location longitude in degrees
        double longitude;

        // Location title
        std::string title;

        // Optional. The radius of uncertainty for the location, measured in meters; 0-1500
        double horizontal_accuracy;

        // Optional. Period in seconds during which the location can be updated, should be between 60 and 86400, or 0x7FFFFFFF for live locations that can be edited indefinitely.
        int64_t live_period;

        // Optional. For live locations, a direction in which the user is moving, in degrees. Must be between 1 and 360 if specified.
        int64_t heading;

        // Optional. For live locations, a maximum distance for proximity alerts about approaching another chat member, in meters. Must be between 1 and 100000 if specified.
        int64_t proximity_alert_radius;

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup;

        // Optional. Content of the message to be sent instead of the location
        InputMessageContent::Ptr input_message_content;

        // Optional. Url of the thumbnail for the result
        std::string thumbnail_url;

        // Optional. Thumbnail width
        int64_t thumbnail_width;

        // Optional. Thumbnail height
        int64_t thumbnail_height;
    };
    void to_json(json& j, const InlineQueryResultLocation& value);
    void from_json(const json& j, InlineQueryResultLocation& value);
}
