// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents a point on the map.
     *
     * @param latitude Latitude as defined by the sender
     * @param longitude Longitude as defined by the sender
     * @param horizontal_accuracy Optional. The radius of uncertainty for the location, measured in meters; 0-1500
     * @param live_period Optional. Time relative to the message sending date, during which the location can be updated; in seconds. For active live locations only.
     * @param heading Optional. The direction in which user is moving, in degrees; 1-360. For active live locations only.
     * @param proximity_alert_radius Optional. The maximum distance for proximity alerts about approaching another chat member, in meters. For sent live locations only.
     */
    struct Location : public TelegramModel {
        typedef std::shared_ptr<Location> Ptr;

        virtual ~Location() = default;
        // Latitude as defined by the sender
        double latitude;

        // Longitude as defined by the sender
        double longitude;

        // Optional. The radius of uncertainty for the location, measured in meters; 0-1500
        double horizontal_accuracy;

        // Optional. Time relative to the message sending date, during which the location can be updated; in seconds. For active live locations only.
        int64_t live_period;

        // Optional. The direction in which user is moving, in degrees; 1-360. For active live locations only.
        int64_t heading;

        // Optional. The maximum distance for proximity alerts about approaching another chat member, in meters. For sent live locations only.
        int64_t proximity_alert_radius;
    };
    void to_json(json& j, const Location& value);
    void from_json(const json& j, Location& value);
}
