// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/PaidMedia.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes the paid media added to a message.
     *
     * @param star_count The number of Telegram Stars that must be paid to buy access to the media
     * @param paid_media Information about the paid media
     */
    struct PaidMediaInfo : public PaidMedia {
        typedef std::shared_ptr<PaidMediaInfo> Ptr;

        virtual ~PaidMediaInfo() = default;
        // The number of Telegram Stars that must be paid to buy access to the media
        int64_t star_count;

        // Information about the paid media
        std::vector<PaidMedia::Ptr> paid_media;
    };
    void to_json(json& j, const PaidMediaInfo& value);
    void from_json(const json& j, PaidMediaInfo& value);
}
