// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/PaidMedia.hpp"
#include "types/Video.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * The paid media is a video.
     *
     * @param type Type of the paid media, always “video”
     * @param video The video
     */
    struct PaidMediaVideo : public PaidMedia {
        typedef std::shared_ptr<PaidMediaVideo> Ptr;

        virtual ~PaidMediaVideo() = default;
        // Type of the paid media, always “video”
        std::string type_;

        // The video
        Video::Ptr video;
    };
    void to_json(json& j, const PaidMediaVideo& value);
    void from_json(const json& j, PaidMediaVideo& value);
}
