// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    struct RevenueWithdrawalState : public TelegramModel {
        typedef std::shared_ptr<RevenueWithdrawalState> Ptr;
        virtual ~RevenueWithdrawalState() = default;
    };

    void to_json(json& j, const RevenueWithdrawalState& value);
    void from_json(const json& j, RevenueWithdrawalState& value);
}
