// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"
#include "types/StarTransaction.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Contains a list of Telegram Star transactions.
     *
     * @param transactions The list of transactions
     */
    struct StarTransactions : public TelegramModel {
        typedef std::shared_ptr<StarTransactions> Ptr;

        virtual ~StarTransactions() = default;
        // The list of transactions
        std::vector<StarTransaction::Ptr> transactions;
    };
    void to_json(json& j, const StarTransactions& value);
    void from_json(const json& j, StarTransactions& value);
}
