// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * Describes the position of a clickable area within a story.
     *
     * @param x_percentage The abscissa of the area's center, as a percentage of the media width
     * @param y_percentage The ordinate of the area's center, as a percentage of the media height
     * @param width_percentage The width of the area's rectangle, as a percentage of the media width
     * @param height_percentage The height of the area's rectangle, as a percentage of the media height
     * @param rotation_angle The clockwise rotation angle of the rectangle, in degrees; 0-360
     * @param corner_radius_percentage The radius of the rectangle corner rounding, as a percentage of the media width
     */
    struct StoryAreaPosition : public TelegramModel {
        typedef std::shared_ptr<StoryAreaPosition> Ptr;

        virtual ~StoryAreaPosition() = default;
        // The abscissa of the area's center, as a percentage of the media width
        double x_percentage;

        // The ordinate of the area's center, as a percentage of the media height
        double y_percentage;

        // The width of the area's rectangle, as a percentage of the media width
        double width_percentage;

        // The height of the area's rectangle, as a percentage of the media height
        double height_percentage;

        // The clockwise rotation angle of the rectangle, in degrees; 0-360
        double rotation_angle;

        // The radius of the rectangle corner rounding, as a percentage of the media width
        double corner_radius_percentage;
    };
    void to_json(json& j, const StoryAreaPosition& value);
    void from_json(const json& j, StoryAreaPosition& value);
}
