// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"
#include "types/Chat.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents a story.
     *
     * @param chat Chat that posted the story
     * @param id Unique identifier for the story in the chat
     */
    struct Story : public TelegramModel {
        typedef std::shared_ptr<Story> Ptr;

        virtual ~Story() = default;
        // Chat that posted the story
        Chat::Ptr chat;

        // Unique identifier for the story in the chat
        int64_t id;
    };
    void to_json(json& j, const Story& value);
    void from_json(const json& j, Story& value);
}
