// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object represents an inline button that switches the current user to inline mode in a chosen chat, with an optional default inline query.
     *
     * @param query Optional. The default inline query to be inserted in the input field. If left empty, only the bot's username will be inserted
     * @param allow_user_chats Optional. True, if private chats with users can be chosen
     * @param allow_bot_chats Optional. True, if private chats with bots can be chosen
     * @param allow_group_chats Optional. True, if group and supergroup chats can be chosen
     * @param allow_channel_chats Optional. True, if channel chats can be chosen
     */
    struct SwitchInlineQueryChosenChat : public TelegramModel {
        typedef std::shared_ptr<SwitchInlineQueryChosenChat> Ptr;

        virtual ~SwitchInlineQueryChosenChat() = default;
        // Optional. The default inline query to be inserted in the input field. If left empty, only the bot's username will be inserted
        std::string query;

        // Optional. True, if private chats with users can be chosen
        bool allow_user_chats;

        // Optional. True, if private chats with bots can be chosen
        bool allow_bot_chats;

        // Optional. True, if group and supergroup chats can be chosen
        bool allow_group_chats;

        // Optional. True, if channel chats can be chosen
        bool allow_channel_chats;
    };
    void to_json(json& j, const SwitchInlineQueryChosenChat& value);
    void from_json(const json& j, SwitchInlineQueryChosenChat& value);
}
