// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <stdexcept>
#include "types/TelegramModel.hpp"
#include "types/Sticker.hpp"

namespace tgbot {

    using json = nlohmann::json;

    /**
     * This object describes the model of a unique gift.
     *
     * @param name Name of the model
     * @param sticker The sticker that represents the unique gift
     * @param rarity_per_mille The number of unique gifts that receive this model for every 1000 gifts upgraded
     */
    struct UniqueGiftModel : public TelegramModel {
        typedef std::shared_ptr<UniqueGiftModel> Ptr;

        virtual ~UniqueGiftModel() = default;
        // Name of the model
        std::string name;

        // The sticker that represents the unique gift
        Sticker::Ptr sticker;

        // The number of unique gifts that receive this model for every 1000 gifts upgraded
        int64_t rarity_per_mille;
    };
    void to_json(json& j, const UniqueGiftModel& value);
    void from_json(const json& j, UniqueGiftModel& value);
}
