// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/CreateNewStickerSetRequest.hpp"
#include "types/InputSticker.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const CreateNewStickerSetRequest& value) {
        j = json{
            {"user_id", value.user_id},
            {"name", value.name},
            {"title", value.title},
            {"stickers", value.stickers},
            {"sticker_type", value.sticker_type},
            {"needs_repainting", value.needs_repainting}
        };
    }

    void from_json(const json& j, CreateNewStickerSetRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("stickers")) {
            j.at("stickers").get_to(value.stickers);
        }
        if (j.contains("sticker_type")) {
            j.at("sticker_type").get_to(value.sticker_type);
        }
        if (j.contains("needs_repainting")) {
            j.at("needs_repainting").get_to(value.needs_repainting);
        }
    }
}
