// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/DeleteChatPhotoRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const DeleteChatPhotoRequest& value) {
        j = json{
            {"chat_id", value.chat_id}
        };
    }

    void from_json(const json& j, DeleteChatPhotoRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
    }
}
