// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/DeleteStickerSetRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const DeleteStickerSetRequest& value) {
        j = json{
            {"name", value.name}
        };
    }

    void from_json(const json& j, DeleteStickerSetRequest& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
    }
}
