// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/EditChatSubscriptionInviteLinkRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const EditChatSubscriptionInviteLinkRequest& value) {
        j = json{
            {"chat_id", value.chat_id},
            {"invite_link", value.invite_link},
            {"name", value.name}
        };
    }

    void from_json(const json& j, EditChatSubscriptionInviteLinkRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("invite_link")) {
            j.at("invite_link").get_to(value.invite_link);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
    }
}
