// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/EditMessageLiveLocationRequest.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const EditMessageLiveLocationRequest& value) {
        j = json{
            {"latitude", value.latitude},
            {"longitude", value.longitude},
            {"business_connection_id", value.business_connection_id},
            {"chat_id", value.chat_id},
            {"message_id", value.message_id},
            {"inline_message_id", value.inline_message_id},
            {"live_period", value.live_period},
            {"horizontal_accuracy", value.horizontal_accuracy},
            {"heading", value.heading},
            {"proximity_alert_radius", value.proximity_alert_radius},
            {"reply_markup", value.reply_markup}
        };
    }

    void from_json(const json& j, EditMessageLiveLocationRequest& value) {
        if (j.contains("latitude")) {
            j.at("latitude").get_to(value.latitude);
        }
        if (j.contains("longitude")) {
            j.at("longitude").get_to(value.longitude);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("inline_message_id")) {
            j.at("inline_message_id").get_to(value.inline_message_id);
        }
        if (j.contains("live_period")) {
            j.at("live_period").get_to(value.live_period);
        }
        if (j.contains("horizontal_accuracy")) {
            j.at("horizontal_accuracy").get_to(value.horizontal_accuracy);
        }
        if (j.contains("heading")) {
            j.at("heading").get_to(value.heading);
        }
        if (j.contains("proximity_alert_radius")) {
            j.at("proximity_alert_radius").get_to(value.proximity_alert_radius);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
