// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/EditStoryRequest.hpp"
#include "types/InputStoryContent.hpp"
#include "types/MessageEntity.hpp"
#include "types/StoryArea.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const EditStoryRequest& value) {
        j = json{
            {"business_connection_id", value.business_connection_id},
            {"story_id", value.story_id},
            {"content", value.content},
            {"caption", value.caption},
            {"parse_mode", value.parse_mode},
            {"caption_entities", value.caption_entities},
            {"areas", value.areas}
        };
    }

    void from_json(const json& j, EditStoryRequest& value) {
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("story_id")) {
            j.at("story_id").get_to(value.story_id);
        }
        if (j.contains("content")) {
            j.at("content").get_to(value.content);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("areas")) {
            j.at("areas").get_to(value.areas);
        }
    }
}
