// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetMyShortDescriptionRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const GetMyShortDescriptionRequest& value) {
        j = json{
            {"language_code", value.language_code}
        };
    }

    void from_json(const json& j, GetMyShortDescriptionRequest& value) {
        if (j.contains("language_code")) {
            j.at("language_code").get_to(value.language_code);
        }
    }
}
