// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetStarTransactionsRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const GetStarTransactionsRequest& value) {
        j = json{
            {"offset", value.offset},
            {"limit", value.limit}
        };
    }

    void from_json(const json& j, GetStarTransactionsRequest& value) {
        if (j.contains("offset")) {
            j.at("offset").get_to(value.offset);
        }
        if (j.contains("limit")) {
            j.at("limit").get_to(value.limit);
        }
    }
}
