// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/RefundStarPaymentRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const RefundStarPaymentRequest& value) {
        j = json{
            {"user_id", value.user_id},
            {"telegram_payment_charge_id", value.telegram_payment_charge_id}
        };
    }

    void from_json(const json& j, RefundStarPaymentRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("telegram_payment_charge_id")) {
            j.at("telegram_payment_charge_id").get_to(value.telegram_payment_charge_id);
        }
    }
}
