// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SendChecklistRequest.hpp"
#include "types/InputChecklist.hpp"
#include "types/ReplyParameters.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SendChecklistRequest& value) {
        j = json{
            {"business_connection_id", value.business_connection_id},
            {"chat_id", value.chat_id},
            {"checklist", value.checklist},
            {"disable_notification", value.disable_notification},
            {"protect_content", value.protect_content},
            {"message_effect_id", value.message_effect_id},
            {"reply_parameters", value.reply_parameters},
            {"reply_markup", value.reply_markup}
        };
    }

    void from_json(const json& j, SendChecklistRequest& value) {
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("checklist")) {
            j.at("checklist").get_to(value.checklist);
        }
        if (j.contains("disable_notification")) {
            j.at("disable_notification").get_to(value.disable_notification);
        }
        if (j.contains("protect_content")) {
            j.at("protect_content").get_to(value.protect_content);
        }
        if (j.contains("message_effect_id")) {
            j.at("message_effect_id").get_to(value.message_effect_id);
        }
        if (j.contains("reply_parameters")) {
            j.at("reply_parameters").get_to(value.reply_parameters);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
