// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SendVenueRequest.hpp"
#include "types/SuggestedPostParameters.hpp"
#include "types/ReplyParameters.hpp"
#include "types/KeyboardOption.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SendVenueRequest& value) {
        j = json{
            {"chat_id", value.chat_id},
            {"latitude", value.latitude},
            {"longitude", value.longitude},
            {"title", value.title},
            {"address", value.address},
            {"business_connection_id", value.business_connection_id},
            {"message_thread_id", value.message_thread_id},
            {"direct_messages_topic_id", value.direct_messages_topic_id},
            {"foursquare_id", value.foursquare_id},
            {"foursquare_type", value.foursquare_type},
            {"google_place_id", value.google_place_id},
            {"google_place_type", value.google_place_type},
            {"disable_notification", value.disable_notification},
            {"protect_content", value.protect_content},
            {"allow_paid_broadcast", value.allow_paid_broadcast},
            {"message_effect_id", value.message_effect_id},
            {"suggested_post_parameters", value.suggested_post_parameters},
            {"reply_parameters", value.reply_parameters},
            {"reply_markup", value.reply_markup}
        };
    }

    void from_json(const json& j, SendVenueRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("latitude")) {
            j.at("latitude").get_to(value.latitude);
        }
        if (j.contains("longitude")) {
            j.at("longitude").get_to(value.longitude);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("address")) {
            j.at("address").get_to(value.address);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("message_thread_id")) {
            j.at("message_thread_id").get_to(value.message_thread_id);
        }
        if (j.contains("direct_messages_topic_id")) {
            j.at("direct_messages_topic_id").get_to(value.direct_messages_topic_id);
        }
        if (j.contains("foursquare_id")) {
            j.at("foursquare_id").get_to(value.foursquare_id);
        }
        if (j.contains("foursquare_type")) {
            j.at("foursquare_type").get_to(value.foursquare_type);
        }
        if (j.contains("google_place_id")) {
            j.at("google_place_id").get_to(value.google_place_id);
        }
        if (j.contains("google_place_type")) {
            j.at("google_place_type").get_to(value.google_place_type);
        }
        if (j.contains("disable_notification")) {
            j.at("disable_notification").get_to(value.disable_notification);
        }
        if (j.contains("protect_content")) {
            j.at("protect_content").get_to(value.protect_content);
        }
        if (j.contains("allow_paid_broadcast")) {
            j.at("allow_paid_broadcast").get_to(value.allow_paid_broadcast);
        }
        if (j.contains("message_effect_id")) {
            j.at("message_effect_id").get_to(value.message_effect_id);
        }
        if (j.contains("suggested_post_parameters")) {
            j.at("suggested_post_parameters").get_to(value.suggested_post_parameters);
        }
        if (j.contains("reply_parameters")) {
            j.at("reply_parameters").get_to(value.reply_parameters);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
