// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetChatAdministratorCustomTitleRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SetChatAdministratorCustomTitleRequest& value) {
        j = json{
            {"chat_id", value.chat_id},
            {"user_id", value.user_id},
            {"custom_title", value.custom_title}
        };
    }

    void from_json(const json& j, SetChatAdministratorCustomTitleRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("custom_title")) {
            j.at("custom_title").get_to(value.custom_title);
        }
    }
}
