// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetMyShortDescriptionRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SetMyShortDescriptionRequest& value) {
        j = json{
            {"short_description", value.short_description},
            {"language_code", value.language_code}
        };
    }

    void from_json(const json& j, SetMyShortDescriptionRequest& value) {
        if (j.contains("short_description")) {
            j.at("short_description").get_to(value.short_description);
        }
        if (j.contains("language_code")) {
            j.at("language_code").get_to(value.language_code);
        }
    }
}
