// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetStickerMaskPositionRequest.hpp"
#include "types/MaskPosition.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SetStickerMaskPositionRequest& value) {
        j = json{
            {"sticker", value.sticker},
            {"mask_position", value.mask_position}
        };
    }

    void from_json(const json& j, SetStickerMaskPositionRequest& value) {
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("mask_position")) {
            j.at("mask_position").get_to(value.mask_position);
        }
    }
}
