// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetStickerEmojiListRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const SetStickerEmojiListRequest& value) {
        j = json{
            {"sticker", value.sticker},
            {"emoji_list", value.emoji_list}
        };
    }

    void from_json(const json& j, SetStickerEmojiListRequest& value) {
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("emoji_list")) {
            j.at("emoji_list").get_to(value.emoji_list);
        }
    }
}
