// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/UnpinChatMessageRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const UnpinChatMessageRequest& value) {
        j = json{
            {"chat_id", value.chat_id},
            {"business_connection_id", value.business_connection_id},
            {"message_id", value.message_id}
        };
    }

    void from_json(const json& j, UnpinChatMessageRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
    }
}
