// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/UploadStickerFileRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const UploadStickerFileRequest& value) {
        j = json{
            {"user_id", value.user_id},
            {"sticker", value.sticker},
            {"sticker_format", value.sticker_format}
        };
    }

    void from_json(const json& j, UploadStickerFileRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("sticker_format")) {
            j.at("sticker_format").get_to(value.sticker_format);
        }
    }
}
