// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/VerifyUserRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const VerifyUserRequest& value) {
        j = json{
            {"user_id", value.user_id},
            {"custom_description", value.custom_description}
        };
    }

    void from_json(const json& j, VerifyUserRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("custom_description")) {
            j.at("custom_description").get_to(value.custom_description);
        }
    }
}
