// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/VerifyChatRequest.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const VerifyChatRequest& value) {
        j = json{
            {"chat_id", value.chat_id},
            {"custom_description", value.custom_description}
        };
    }

    void from_json(const json& j, VerifyChatRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("custom_description")) {
            j.at("custom_description").get_to(value.custom_description);
        }
    }
}
