// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BotCommandScope.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const BotCommandScope& value) { }
    void from_json(const json& j, BotCommandScope& value) { }
}
