// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChatMemberUpdated.hpp"
#include "types/Chat.hpp"
#include "types/User.hpp"
#include "types/ChatMember.hpp"
#include "types/ChatInviteLink.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const ChatMemberUpdated& value) {
        j = json{
            {"chat", value.chat},
            {"from", value.from},
            {"date", value.date},
            {"old_chat_member", value.old_chat_member},
            {"new_chat_member", value.new_chat_member},
            {"invite_link", value.invite_link},
            {"via_join_request", value.via_join_request},
            {"via_chat_folder_invite_link", value.via_chat_folder_invite_link}
        };
    }

    void from_json(const json& j, ChatMemberUpdated& value) {
        if (j.contains("chat")) {
            j.at("chat").get_to(value.chat);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("old_chat_member")) {
            j.at("old_chat_member").get_to(value.old_chat_member);
        }
        if (j.contains("new_chat_member")) {
            j.at("new_chat_member").get_to(value.new_chat_member);
        }
        if (j.contains("invite_link")) {
            j.at("invite_link").get_to(value.invite_link);
        }
        if (j.contains("via_join_request")) {
            j.at("via_join_request").get_to(value.via_join_request);
        }
        if (j.contains("via_chat_folder_invite_link")) {
            j.at("via_chat_folder_invite_link").get_to(value.via_chat_folder_invite_link);
        }
    }
}
