// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ForumTopicReopened.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const ForumTopicReopened& value) { j = json{}; }
    void from_json(const json& j, ForumTopicReopened& value) { }
}
