// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ForumTopicCreated.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const ForumTopicCreated& value) {
        j = json{
            {"name", value.name},
            {"icon_color", value.icon_color},
            {"icon_custom_emoji_id", value.icon_custom_emoji_id},
            {"is_name_implicit", value.is_name_implicit}
        };
    }

    void from_json(const json& j, ForumTopicCreated& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("icon_color")) {
            j.at("icon_color").get_to(value.icon_color);
        }
        if (j.contains("icon_custom_emoji_id")) {
            j.at("icon_custom_emoji_id").get_to(value.icon_custom_emoji_id);
        }
        if (j.contains("is_name_implicit")) {
            j.at("is_name_implicit").get_to(value.is_name_implicit);
        }
    }
}
