// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Gift.hpp"
#include "types/Sticker.hpp"
#include "types/GiftBackground.hpp"
#include "types/Chat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const Gift& value) {
        j = json{
            {"id", value.id},
            {"sticker", value.sticker},
            {"star_count", value.star_count},
            {"upgrade_star_count", value.upgrade_star_count},
            {"is_premium", value.is_premium},
            {"has_colors", value.has_colors},
            {"total_count", value.total_count},
            {"remaining_count", value.remaining_count},
            {"personal_total_count", value.personal_total_count},
            {"personal_remaining_count", value.personal_remaining_count},
            {"background", value.background},
            {"unique_gift_variant_count", value.unique_gift_variant_count},
            {"publisher_chat", value.publisher_chat}
        };
    }

    void from_json(const json& j, Gift& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("star_count")) {
            j.at("star_count").get_to(value.star_count);
        }
        if (j.contains("upgrade_star_count")) {
            j.at("upgrade_star_count").get_to(value.upgrade_star_count);
        }
        if (j.contains("is_premium")) {
            j.at("is_premium").get_to(value.is_premium);
        }
        if (j.contains("has_colors")) {
            j.at("has_colors").get_to(value.has_colors);
        }
        if (j.contains("total_count")) {
            j.at("total_count").get_to(value.total_count);
        }
        if (j.contains("remaining_count")) {
            j.at("remaining_count").get_to(value.remaining_count);
        }
        if (j.contains("personal_total_count")) {
            j.at("personal_total_count").get_to(value.personal_total_count);
        }
        if (j.contains("personal_remaining_count")) {
            j.at("personal_remaining_count").get_to(value.personal_remaining_count);
        }
        if (j.contains("background")) {
            j.at("background").get_to(value.background);
        }
        if (j.contains("unique_gift_variant_count")) {
            j.at("unique_gift_variant_count").get_to(value.unique_gift_variant_count);
        }
        if (j.contains("publisher_chat")) {
            j.at("publisher_chat").get_to(value.publisher_chat);
        }
    }
}
