// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultCachedAudio.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InlineQueryResultCachedAudio& value) {
        j = json{
            {"type", value.type_},
            {"id", value.id},
            {"audio_file_id", value.audio_file_id},
            {"caption", value.caption},
            {"parse_mode", value.parse_mode},
            {"caption_entities", value.caption_entities},
            {"reply_markup", value.reply_markup},
            {"input_message_content", value.input_message_content}
        };
    }

    void from_json(const json& j, InlineQueryResultCachedAudio& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("audio_file_id")) {
            j.at("audio_file_id").get_to(value.audio_file_id);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
    }
}
