// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultContact.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InlineQueryResultContact& value) {
        j = json{
            {"type", value.type_},
            {"id", value.id},
            {"phone_number", value.phone_number},
            {"first_name", value.first_name},
            {"last_name", value.last_name},
            {"vcard", value.vcard},
            {"reply_markup", value.reply_markup},
            {"input_message_content", value.input_message_content},
            {"thumbnail_url", value.thumbnail_url},
            {"thumbnail_width", value.thumbnail_width},
            {"thumbnail_height", value.thumbnail_height}
        };
    }

    void from_json(const json& j, InlineQueryResultContact& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("phone_number")) {
            j.at("phone_number").get_to(value.phone_number);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("vcard")) {
            j.at("vcard").get_to(value.vcard);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("thumbnail_width")) {
            j.at("thumbnail_width").get_to(value.thumbnail_width);
        }
        if (j.contains("thumbnail_height")) {
            j.at("thumbnail_height").get_to(value.thumbnail_height);
        }
    }
}
