// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultDocument.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InlineQueryResultDocument& value) {
        j = json{
            {"type", value.type_},
            {"id", value.id},
            {"title", value.title},
            {"document_url", value.document_url},
            {"mime_type", value.mime_type},
            {"caption", value.caption},
            {"parse_mode", value.parse_mode},
            {"caption_entities", value.caption_entities},
            {"description", value.description},
            {"reply_markup", value.reply_markup},
            {"input_message_content", value.input_message_content},
            {"thumbnail_url", value.thumbnail_url},
            {"thumbnail_width", value.thumbnail_width},
            {"thumbnail_height", value.thumbnail_height}
        };
    }

    void from_json(const json& j, InlineQueryResultDocument& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("document_url")) {
            j.at("document_url").get_to(value.document_url);
        }
        if (j.contains("mime_type")) {
            j.at("mime_type").get_to(value.mime_type);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("thumbnail_width")) {
            j.at("thumbnail_width").get_to(value.thumbnail_width);
        }
        if (j.contains("thumbnail_height")) {
            j.at("thumbnail_height").get_to(value.thumbnail_height);
        }
    }
}
