// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputStoryContentVideo.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputStoryContentVideo& value) {
        j = json{
            {"type", value.type_},
            {"video", value.video},
            {"duration", value.duration},
            {"cover_frame_timestamp", value.cover_frame_timestamp},
            {"is_animation", value.is_animation}
        };
    }

    void from_json(const json& j, InputStoryContentVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("video")) {
            j.at("video").get_to(value.video);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("cover_frame_timestamp")) {
            j.at("cover_frame_timestamp").get_to(value.cover_frame_timestamp);
        }
        if (j.contains("is_animation")) {
            j.at("is_animation").get_to(value.is_animation);
        }
    }
}
