// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputMediaDocument.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputMediaDocument& value) {
        j = json{
            {"type", value.type_},
            {"media", value.media},
            {"thumbnail", value.thumbnail},
            {"caption", value.caption},
            {"parse_mode", value.parse_mode},
            {"caption_entities", value.caption_entities},
            {"disable_content_type_detection", value.disable_content_type_detection}
        };
    }

    void from_json(const json& j, InputMediaDocument& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("disable_content_type_detection")) {
            j.at("disable_content_type_detection").get_to(value.disable_content_type_detection);
        }
    }
}
