// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputMediaAnimation.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputMediaAnimation& value) {
        j = json{
            {"type", value.type_},
            {"media", value.media},
            {"thumbnail", value.thumbnail},
            {"caption", value.caption},
            {"parse_mode", value.parse_mode},
            {"caption_entities", value.caption_entities},
            {"show_caption_above_media", value.show_caption_above_media},
            {"width", value.width},
            {"height", value.height},
            {"duration", value.duration},
            {"has_spoiler", value.has_spoiler}
        };
    }

    void from_json(const json& j, InputMediaAnimation& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("has_spoiler")) {
            j.at("has_spoiler").get_to(value.has_spoiler);
        }
    }
}
