// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputVenueMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputVenueMessageContent& value) {
        j = json{
            {"latitude", value.latitude},
            {"longitude", value.longitude},
            {"title", value.title},
            {"address", value.address},
            {"foursquare_id", value.foursquare_id},
            {"foursquare_type", value.foursquare_type},
            {"google_place_id", value.google_place_id},
            {"google_place_type", value.google_place_type}
        };
    }

    void from_json(const json& j, InputVenueMessageContent& value) {
        if (j.contains("latitude")) {
            j.at("latitude").get_to(value.latitude);
        }
        if (j.contains("longitude")) {
            j.at("longitude").get_to(value.longitude);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("address")) {
            j.at("address").get_to(value.address);
        }
        if (j.contains("foursquare_id")) {
            j.at("foursquare_id").get_to(value.foursquare_id);
        }
        if (j.contains("foursquare_type")) {
            j.at("foursquare_type").get_to(value.foursquare_type);
        }
        if (j.contains("google_place_id")) {
            j.at("google_place_id").get_to(value.google_place_id);
        }
        if (j.contains("google_place_type")) {
            j.at("google_place_type").get_to(value.google_place_type);
        }
    }
}
