// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputSticker.hpp"
#include "types/MaskPosition.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const InputSticker& value) {
        j = json{
            {"sticker", value.sticker},
            {"format", value.format},
            {"emoji_list", value.emoji_list},
            {"mask_position", value.mask_position},
            {"keywords", value.keywords}
        };
    }

    void from_json(const json& j, InputSticker& value) {
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("format")) {
            j.at("format").get_to(value.format);
        }
        if (j.contains("emoji_list")) {
            j.at("emoji_list").get_to(value.emoji_list);
        }
        if (j.contains("mask_position")) {
            j.at("mask_position").get_to(value.mask_position);
        }
        if (j.contains("keywords")) {
            j.at("keywords").get_to(value.keywords);
        }
    }
}
