// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/KeyboardButtonRequestUsers.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const KeyboardButtonRequestUsers& value) {
        j = json{
            {"request_id", value.request_id},
            {"user_is_bot", value.user_is_bot},
            {"user_is_premium", value.user_is_premium},
            {"max_quantity", value.max_quantity},
            {"request_name", value.request_name},
            {"request_username", value.request_username},
            {"request_photo", value.request_photo}
        };
    }

    void from_json(const json& j, KeyboardButtonRequestUsers& value) {
        if (j.contains("request_id")) {
            j.at("request_id").get_to(value.request_id);
        }
        if (j.contains("user_is_bot")) {
            j.at("user_is_bot").get_to(value.user_is_bot);
        }
        if (j.contains("user_is_premium")) {
            j.at("user_is_premium").get_to(value.user_is_premium);
        }
        if (j.contains("max_quantity")) {
            j.at("max_quantity").get_to(value.max_quantity);
        }
        if (j.contains("request_name")) {
            j.at("request_name").get_to(value.request_name);
        }
        if (j.contains("request_username")) {
            j.at("request_username").get_to(value.request_username);
        }
        if (j.contains("request_photo")) {
            j.at("request_photo").get_to(value.request_photo);
        }
    }
}
