// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MaskPosition.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const MaskPosition& value) {
        j = json{
            {"point", value.point},
            {"x_shift", value.x_shift},
            {"y_shift", value.y_shift},
            {"scale", value.scale}
        };
    }

    void from_json(const json& j, MaskPosition& value) {
        if (j.contains("point")) {
            j.at("point").get_to(value.point);
        }
        if (j.contains("x_shift")) {
            j.at("x_shift").get_to(value.x_shift);
        }
        if (j.contains("y_shift")) {
            j.at("y_shift").get_to(value.y_shift);
        }
        if (j.contains("scale")) {
            j.at("scale").get_to(value.scale);
        }
    }
}
