// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Message.hpp"
#include "types/Chat.hpp"
#include "types/DirectMessagesTopic.hpp"
#include "types/User.hpp"
#include "types/MessageOrigin.hpp"
#include "types/ExternalReplyInfo.hpp"
#include "types/TextQuote.hpp"
#include "types/Story.hpp"
#include "types/LinkPreviewOptions.hpp"
#include "types/SuggestedPostInfo.hpp"
#include "types/Animation.hpp"
#include "types/Audio.hpp"
#include "types/Document.hpp"
#include "types/PaidMediaInfo.hpp"
#include "types/Sticker.hpp"
#include "types/Video.hpp"
#include "types/VideoNote.hpp"
#include "types/Voice.hpp"
#include "types/Checklist.hpp"
#include "types/Contact.hpp"
#include "types/Dice.hpp"
#include "types/Game.hpp"
#include "types/Poll.hpp"
#include "types/Venue.hpp"
#include "types/Location.hpp"
#include "types/MessageAutoDeleteTimerChanged.hpp"
#include "types/MaybeInaccessibleMessage.hpp"
#include "types/Invoice.hpp"
#include "types/SuccessfulPayment.hpp"
#include "types/RefundedPayment.hpp"
#include "types/UsersShared.hpp"
#include "types/ChatShared.hpp"
#include "types/GiftInfo.hpp"
#include "types/UniqueGiftInfo.hpp"
#include "types/WriteAccessAllowed.hpp"
#include "types/PassportData.hpp"
#include "types/ProximityAlertTriggered.hpp"
#include "types/ChatBoostAdded.hpp"
#include "types/ChatBackground.hpp"
#include "types/ChecklistTasksDone.hpp"
#include "types/ChecklistTasksAdded.hpp"
#include "types/DirectMessagePriceChanged.hpp"
#include "types/ForumTopicCreated.hpp"
#include "types/ForumTopicEdited.hpp"
#include "types/GiveawayCreated.hpp"
#include "types/Giveaway.hpp"
#include "types/GiveawayWinners.hpp"
#include "types/GiveawayCompleted.hpp"
#include "types/PaidMessagePriceChanged.hpp"
#include "types/SuggestedPostApproved.hpp"
#include "types/SuggestedPostApprovalFailed.hpp"
#include "types/SuggestedPostDeclined.hpp"
#include "types/SuggestedPostPaid.hpp"
#include "types/SuggestedPostRefunded.hpp"
#include "types/VideoChatScheduled.hpp"
#include "types/VideoChatEnded.hpp"
#include "types/VideoChatParticipantsInvited.hpp"
#include "types/WebAppData.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const Message& value) {
        j = json{
            {"message_id", value.message_id},
            {"date", value.date},
            {"chat", value.chat},
            {"message_thread_id", value.message_thread_id},
            {"direct_messages_topic", value.direct_messages_topic},
            {"from", value.from},
            {"sender_chat", value.sender_chat},
            {"sender_boost_count", value.sender_boost_count},
            {"sender_business_bot", value.sender_business_bot},
            {"business_connection_id", value.business_connection_id},
            {"forward_origin", value.forward_origin},
            {"is_topic_message", value.is_topic_message},
            {"is_automatic_forward", value.is_automatic_forward},
            {"reply_to_message", value.reply_to_message},
            {"external_reply", value.external_reply},
            {"quote", value.quote},
            {"reply_to_story", value.reply_to_story},
            {"reply_to_checklist_task_id", value.reply_to_checklist_task_id},
            {"via_bot", value.via_bot},
            {"edit_date", value.edit_date},
            {"has_protected_content", value.has_protected_content},
            {"is_from_offline", value.is_from_offline},
            {"is_paid_post", value.is_paid_post},
            {"media_group_id", value.media_group_id},
            {"author_signature", value.author_signature},
            {"paid_star_count", value.paid_star_count},
            {"text", value.text},
            {"entities", value.entities},
            {"link_preview_options", value.link_preview_options},
            {"suggested_post_info", value.suggested_post_info},
            {"effect_id", value.effect_id},
            {"animation", value.animation},
            {"audio", value.audio},
            {"document", value.document},
            {"paid_media", value.paid_media},
            {"photo", value.photo},
            {"sticker", value.sticker},
            {"story", value.story},
            {"video", value.video},
            {"video_note", value.video_note},
            {"voice", value.voice},
            {"caption", value.caption},
            {"caption_entities", value.caption_entities},
            {"show_caption_above_media", value.show_caption_above_media},
            {"has_media_spoiler", value.has_media_spoiler},
            {"checklist", value.checklist},
            {"contact", value.contact},
            {"dice", value.dice},
            {"game", value.game},
            {"poll", value.poll},
            {"venue", value.venue},
            {"location", value.location},
            {"new_chat_members", value.new_chat_members},
            {"left_chat_member", value.left_chat_member},
            {"new_chat_title", value.new_chat_title},
            {"new_chat_photo", value.new_chat_photo},
            {"delete_chat_photo", value.delete_chat_photo},
            {"group_chat_created", value.group_chat_created},
            {"supergroup_chat_created", value.supergroup_chat_created},
            {"channel_chat_created", value.channel_chat_created},
            {"message_auto_delete_timer_changed", value.message_auto_delete_timer_changed},
            {"migrate_to_chat_id", value.migrate_to_chat_id},
            {"migrate_from_chat_id", value.migrate_from_chat_id},
            {"pinned_message", value.pinned_message},
            {"invoice", value.invoice},
            {"successful_payment", value.successful_payment},
            {"refunded_payment", value.refunded_payment},
            {"users_shared", value.users_shared},
            {"chat_shared", value.chat_shared},
            {"gift", value.gift},
            {"unique_gift", value.unique_gift},
            {"gift_upgrade_sent", value.gift_upgrade_sent},
            {"connected_website", value.connected_website},
            {"write_access_allowed", value.write_access_allowed},
            {"passport_data", value.passport_data},
            {"proximity_alert_triggered", value.proximity_alert_triggered},
            {"boost_added", value.boost_added},
            {"chat_background_set", value.chat_background_set},
            {"checklist_tasks_done", value.checklist_tasks_done},
            {"checklist_tasks_added", value.checklist_tasks_added},
            {"direct_message_price_changed", value.direct_message_price_changed},
            {"forum_topic_created", value.forum_topic_created},
            {"forum_topic_edited", value.forum_topic_edited},
            {"forum_topic_closed", value.forum_topic_closed},
            {"forum_topic_reopened", value.forum_topic_reopened},
            {"general_forum_topic_hidden", value.general_forum_topic_hidden},
            {"general_forum_topic_unhidden", value.general_forum_topic_unhidden},
            {"giveaway_created", value.giveaway_created},
            {"giveaway", value.giveaway},
            {"giveaway_winners", value.giveaway_winners},
            {"giveaway_completed", value.giveaway_completed},
            {"paid_message_price_changed", value.paid_message_price_changed},
            {"suggested_post_approved", value.suggested_post_approved},
            {"suggested_post_approval_failed", value.suggested_post_approval_failed},
            {"suggested_post_declined", value.suggested_post_declined},
            {"suggested_post_paid", value.suggested_post_paid},
            {"suggested_post_refunded", value.suggested_post_refunded},
            {"video_chat_scheduled", value.video_chat_scheduled},
            {"video_chat_started", value.video_chat_started},
            {"video_chat_ended", value.video_chat_ended},
            {"video_chat_participants_invited", value.video_chat_participants_invited},
            {"web_app_data", value.web_app_data},
            {"reply_markup", value.reply_markup}
        };
    }

    void from_json(const json& j, Message& value) {
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("chat")) {
            j.at("chat").get_to(value.chat);
        }
        if (j.contains("message_thread_id")) {
            j.at("message_thread_id").get_to(value.message_thread_id);
        }
        if (j.contains("direct_messages_topic")) {
            j.at("direct_messages_topic").get_to(value.direct_messages_topic);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("sender_chat")) {
            j.at("sender_chat").get_to(value.sender_chat);
        }
        if (j.contains("sender_boost_count")) {
            j.at("sender_boost_count").get_to(value.sender_boost_count);
        }
        if (j.contains("sender_business_bot")) {
            j.at("sender_business_bot").get_to(value.sender_business_bot);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("forward_origin")) {
            j.at("forward_origin").get_to(value.forward_origin);
        }
        if (j.contains("is_topic_message")) {
            j.at("is_topic_message").get_to(value.is_topic_message);
        }
        if (j.contains("is_automatic_forward")) {
            j.at("is_automatic_forward").get_to(value.is_automatic_forward);
        }
        if (j.contains("reply_to_message")) {
            j.at("reply_to_message").get_to(value.reply_to_message);
        }
        if (j.contains("external_reply")) {
            j.at("external_reply").get_to(value.external_reply);
        }
        if (j.contains("quote")) {
            j.at("quote").get_to(value.quote);
        }
        if (j.contains("reply_to_story")) {
            j.at("reply_to_story").get_to(value.reply_to_story);
        }
        if (j.contains("reply_to_checklist_task_id")) {
            j.at("reply_to_checklist_task_id").get_to(value.reply_to_checklist_task_id);
        }
        if (j.contains("via_bot")) {
            j.at("via_bot").get_to(value.via_bot);
        }
        if (j.contains("edit_date")) {
            j.at("edit_date").get_to(value.edit_date);
        }
        if (j.contains("has_protected_content")) {
            j.at("has_protected_content").get_to(value.has_protected_content);
        }
        if (j.contains("is_from_offline")) {
            j.at("is_from_offline").get_to(value.is_from_offline);
        }
        if (j.contains("is_paid_post")) {
            j.at("is_paid_post").get_to(value.is_paid_post);
        }
        if (j.contains("media_group_id")) {
            j.at("media_group_id").get_to(value.media_group_id);
        }
        if (j.contains("author_signature")) {
            j.at("author_signature").get_to(value.author_signature);
        }
        if (j.contains("paid_star_count")) {
            j.at("paid_star_count").get_to(value.paid_star_count);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("entities")) {
            j.at("entities").get_to(value.entities);
        }
        if (j.contains("link_preview_options")) {
            j.at("link_preview_options").get_to(value.link_preview_options);
        }
        if (j.contains("suggested_post_info")) {
            j.at("suggested_post_info").get_to(value.suggested_post_info);
        }
        if (j.contains("effect_id")) {
            j.at("effect_id").get_to(value.effect_id);
        }
        if (j.contains("animation")) {
            j.at("animation").get_to(value.animation);
        }
        if (j.contains("audio")) {
            j.at("audio").get_to(value.audio);
        }
        if (j.contains("document")) {
            j.at("document").get_to(value.document);
        }
        if (j.contains("paid_media")) {
            j.at("paid_media").get_to(value.paid_media);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
        if (j.contains("story")) {
            j.at("story").get_to(value.story);
        }
        if (j.contains("video")) {
            j.at("video").get_to(value.video);
        }
        if (j.contains("video_note")) {
            j.at("video_note").get_to(value.video_note);
        }
        if (j.contains("voice")) {
            j.at("voice").get_to(value.voice);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("has_media_spoiler")) {
            j.at("has_media_spoiler").get_to(value.has_media_spoiler);
        }
        if (j.contains("checklist")) {
            j.at("checklist").get_to(value.checklist);
        }
        if (j.contains("contact")) {
            j.at("contact").get_to(value.contact);
        }
        if (j.contains("dice")) {
            j.at("dice").get_to(value.dice);
        }
        if (j.contains("game")) {
            j.at("game").get_to(value.game);
        }
        if (j.contains("poll")) {
            j.at("poll").get_to(value.poll);
        }
        if (j.contains("venue")) {
            j.at("venue").get_to(value.venue);
        }
        if (j.contains("location")) {
            j.at("location").get_to(value.location);
        }
        if (j.contains("new_chat_members")) {
            j.at("new_chat_members").get_to(value.new_chat_members);
        }
        if (j.contains("left_chat_member")) {
            j.at("left_chat_member").get_to(value.left_chat_member);
        }
        if (j.contains("new_chat_title")) {
            j.at("new_chat_title").get_to(value.new_chat_title);
        }
        if (j.contains("new_chat_photo")) {
            j.at("new_chat_photo").get_to(value.new_chat_photo);
        }
        if (j.contains("delete_chat_photo")) {
            j.at("delete_chat_photo").get_to(value.delete_chat_photo);
        }
        if (j.contains("group_chat_created")) {
            j.at("group_chat_created").get_to(value.group_chat_created);
        }
        if (j.contains("supergroup_chat_created")) {
            j.at("supergroup_chat_created").get_to(value.supergroup_chat_created);
        }
        if (j.contains("channel_chat_created")) {
            j.at("channel_chat_created").get_to(value.channel_chat_created);
        }
        if (j.contains("message_auto_delete_timer_changed")) {
            j.at("message_auto_delete_timer_changed").get_to(value.message_auto_delete_timer_changed);
        }
        if (j.contains("migrate_to_chat_id")) {
            j.at("migrate_to_chat_id").get_to(value.migrate_to_chat_id);
        }
        if (j.contains("migrate_from_chat_id")) {
            j.at("migrate_from_chat_id").get_to(value.migrate_from_chat_id);
        }
        if (j.contains("pinned_message")) {
            j.at("pinned_message").get_to(value.pinned_message);
        }
        if (j.contains("invoice")) {
            j.at("invoice").get_to(value.invoice);
        }
        if (j.contains("successful_payment")) {
            j.at("successful_payment").get_to(value.successful_payment);
        }
        if (j.contains("refunded_payment")) {
            j.at("refunded_payment").get_to(value.refunded_payment);
        }
        if (j.contains("users_shared")) {
            j.at("users_shared").get_to(value.users_shared);
        }
        if (j.contains("chat_shared")) {
            j.at("chat_shared").get_to(value.chat_shared);
        }
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("unique_gift")) {
            j.at("unique_gift").get_to(value.unique_gift);
        }
        if (j.contains("gift_upgrade_sent")) {
            j.at("gift_upgrade_sent").get_to(value.gift_upgrade_sent);
        }
        if (j.contains("connected_website")) {
            j.at("connected_website").get_to(value.connected_website);
        }
        if (j.contains("write_access_allowed")) {
            j.at("write_access_allowed").get_to(value.write_access_allowed);
        }
        if (j.contains("passport_data")) {
            j.at("passport_data").get_to(value.passport_data);
        }
        if (j.contains("proximity_alert_triggered")) {
            j.at("proximity_alert_triggered").get_to(value.proximity_alert_triggered);
        }
        if (j.contains("boost_added")) {
            j.at("boost_added").get_to(value.boost_added);
        }
        if (j.contains("chat_background_set")) {
            j.at("chat_background_set").get_to(value.chat_background_set);
        }
        if (j.contains("checklist_tasks_done")) {
            j.at("checklist_tasks_done").get_to(value.checklist_tasks_done);
        }
        if (j.contains("checklist_tasks_added")) {
            j.at("checklist_tasks_added").get_to(value.checklist_tasks_added);
        }
        if (j.contains("direct_message_price_changed")) {
            j.at("direct_message_price_changed").get_to(value.direct_message_price_changed);
        }
        if (j.contains("forum_topic_created")) {
            j.at("forum_topic_created").get_to(value.forum_topic_created);
        }
        if (j.contains("forum_topic_edited")) {
            j.at("forum_topic_edited").get_to(value.forum_topic_edited);
        }
        if (j.contains("forum_topic_closed")) {
            j.at("forum_topic_closed").get_to(value.forum_topic_closed);
        }
        if (j.contains("forum_topic_reopened")) {
            j.at("forum_topic_reopened").get_to(value.forum_topic_reopened);
        }
        if (j.contains("general_forum_topic_hidden")) {
            j.at("general_forum_topic_hidden").get_to(value.general_forum_topic_hidden);
        }
        if (j.contains("general_forum_topic_unhidden")) {
            j.at("general_forum_topic_unhidden").get_to(value.general_forum_topic_unhidden);
        }
        if (j.contains("giveaway_created")) {
            j.at("giveaway_created").get_to(value.giveaway_created);
        }
        if (j.contains("giveaway")) {
            j.at("giveaway").get_to(value.giveaway);
        }
        if (j.contains("giveaway_winners")) {
            j.at("giveaway_winners").get_to(value.giveaway_winners);
        }
        if (j.contains("giveaway_completed")) {
            j.at("giveaway_completed").get_to(value.giveaway_completed);
        }
        if (j.contains("paid_message_price_changed")) {
            j.at("paid_message_price_changed").get_to(value.paid_message_price_changed);
        }
        if (j.contains("suggested_post_approved")) {
            j.at("suggested_post_approved").get_to(value.suggested_post_approved);
        }
        if (j.contains("suggested_post_approval_failed")) {
            j.at("suggested_post_approval_failed").get_to(value.suggested_post_approval_failed);
        }
        if (j.contains("suggested_post_declined")) {
            j.at("suggested_post_declined").get_to(value.suggested_post_declined);
        }
        if (j.contains("suggested_post_paid")) {
            j.at("suggested_post_paid").get_to(value.suggested_post_paid);
        }
        if (j.contains("suggested_post_refunded")) {
            j.at("suggested_post_refunded").get_to(value.suggested_post_refunded);
        }
        if (j.contains("video_chat_scheduled")) {
            j.at("video_chat_scheduled").get_to(value.video_chat_scheduled);
        }
        if (j.contains("video_chat_started")) {
            j.at("video_chat_started").get_to(value.video_chat_started);
        }
        if (j.contains("video_chat_ended")) {
            j.at("video_chat_ended").get_to(value.video_chat_ended);
        }
        if (j.contains("video_chat_participants_invited")) {
            j.at("video_chat_participants_invited").get_to(value.video_chat_participants_invited);
        }
        if (j.contains("web_app_data")) {
            j.at("web_app_data").get_to(value.web_app_data);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
