// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/OwnedGiftUnique.hpp"
#include "types/UniqueGift.hpp"
#include "types/User.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const OwnedGiftUnique& value) {
        j = json{
            {"type", value.type_},
            {"gift", value.gift},
            {"send_date", value.send_date},
            {"owned_gift_id", value.owned_gift_id},
            {"sender_user", value.sender_user},
            {"is_saved", value.is_saved},
            {"can_be_transferred", value.can_be_transferred},
            {"transfer_star_count", value.transfer_star_count},
            {"next_transfer_date", value.next_transfer_date}
        };
    }

    void from_json(const json& j, OwnedGiftUnique& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("send_date")) {
            j.at("send_date").get_to(value.send_date);
        }
        if (j.contains("owned_gift_id")) {
            j.at("owned_gift_id").get_to(value.owned_gift_id);
        }
        if (j.contains("sender_user")) {
            j.at("sender_user").get_to(value.sender_user);
        }
        if (j.contains("is_saved")) {
            j.at("is_saved").get_to(value.is_saved);
        }
        if (j.contains("can_be_transferred")) {
            j.at("can_be_transferred").get_to(value.can_be_transferred);
        }
        if (j.contains("transfer_star_count")) {
            j.at("transfer_star_count").get_to(value.transfer_star_count);
        }
        if (j.contains("next_transfer_date")) {
            j.at("next_transfer_date").get_to(value.next_transfer_date);
        }
    }
}
