// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/OwnedGift.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const OwnedGift& value) { }
    void from_json(const json& j, OwnedGift& value) { }
}
