// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PhotoSize.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const PhotoSize& value) {
        j = json{
            {"file_id", value.file_id},
            {"file_unique_id", value.file_unique_id},
            {"width", value.width},
            {"height", value.height},
            {"file_size", value.file_size}
        };
    }

    void from_json(const json& j, PhotoSize& value) {
        if (j.contains("file_id")) {
            j.at("file_id").get_to(value.file_id);
        }
        if (j.contains("file_unique_id")) {
            j.at("file_unique_id").get_to(value.file_unique_id);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("file_size")) {
            j.at("file_size").get_to(value.file_size);
        }
    }
}
