// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/RevenueWithdrawalState.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const RevenueWithdrawalState& value) { }
    void from_json(const json& j, RevenueWithdrawalState& value) { }
}
