// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/TextQuote.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const TextQuote& value) {
        j = json{
            {"text", value.text},
            {"position", value.position},
            {"entities", value.entities},
            {"is_manual", value.is_manual}
        };
    }

    void from_json(const json& j, TextQuote& value) {
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("position")) {
            j.at("position").get_to(value.position);
        }
        if (j.contains("entities")) {
            j.at("entities").get_to(value.entities);
        }
        if (j.contains("is_manual")) {
            j.at("is_manual").get_to(value.is_manual);
        }
    }
}
