// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/UniqueGiftColors.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const UniqueGiftColors& value) {
        j = json{
            {"model_custom_emoji_id", value.model_custom_emoji_id},
            {"symbol_custom_emoji_id", value.symbol_custom_emoji_id},
            {"light_theme_main_color", value.light_theme_main_color},
            {"light_theme_other_colors", value.light_theme_other_colors},
            {"dark_theme_main_color", value.dark_theme_main_color},
            {"dark_theme_other_colors", value.dark_theme_other_colors}
        };
    }

    void from_json(const json& j, UniqueGiftColors& value) {
        if (j.contains("model_custom_emoji_id")) {
            j.at("model_custom_emoji_id").get_to(value.model_custom_emoji_id);
        }
        if (j.contains("symbol_custom_emoji_id")) {
            j.at("symbol_custom_emoji_id").get_to(value.symbol_custom_emoji_id);
        }
        if (j.contains("light_theme_main_color")) {
            j.at("light_theme_main_color").get_to(value.light_theme_main_color);
        }
        if (j.contains("light_theme_other_colors")) {
            j.at("light_theme_other_colors").get_to(value.light_theme_other_colors);
        }
        if (j.contains("dark_theme_main_color")) {
            j.at("dark_theme_main_color").get_to(value.dark_theme_main_color);
        }
        if (j.contains("dark_theme_other_colors")) {
            j.at("dark_theme_other_colors").get_to(value.dark_theme_other_colors);
        }
    }
}
