// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/UniqueGift.hpp"
#include "types/UniqueGiftModel.hpp"
#include "types/UniqueGiftSymbol.hpp"
#include "types/UniqueGiftBackdrop.hpp"
#include "types/UniqueGiftColors.hpp"
#include "types/Chat.hpp"
#include <nlohmann/json.hpp>

namespace tgbot {
    void to_json(json& j, const UniqueGift& value) {
        j = json{
            {"gift_id", value.gift_id},
            {"base_name", value.base_name},
            {"name", value.name},
            {"number", value.number},
            {"model", value.model},
            {"symbol", value.symbol},
            {"backdrop", value.backdrop},
            {"is_premium", value.is_premium},
            {"is_from_blockchain", value.is_from_blockchain},
            {"colors", value.colors},
            {"publisher_chat", value.publisher_chat}
        };
    }

    void from_json(const json& j, UniqueGift& value) {
        if (j.contains("gift_id")) {
            j.at("gift_id").get_to(value.gift_id);
        }
        if (j.contains("base_name")) {
            j.at("base_name").get_to(value.base_name);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("number")) {
            j.at("number").get_to(value.number);
        }
        if (j.contains("model")) {
            j.at("model").get_to(value.model);
        }
        if (j.contains("symbol")) {
            j.at("symbol").get_to(value.symbol);
        }
        if (j.contains("backdrop")) {
            j.at("backdrop").get_to(value.backdrop);
        }
        if (j.contains("is_premium")) {
            j.at("is_premium").get_to(value.is_premium);
        }
        if (j.contains("is_from_blockchain")) {
            j.at("is_from_blockchain").get_to(value.is_from_blockchain);
        }
        if (j.contains("colors")) {
            j.at("colors").get_to(value.colors);
        }
        if (j.contains("publisher_chat")) {
            j.at("publisher_chat").get_to(value.publisher_chat);
        }
    }
}
